### ISSUE TITLE
Window screencast support

### ISSUE THREAD

**Issue by YaLTeR** [YaLTeR/niri#116]
Right now we only support monitor screencasts. Will need to be careful handling window resizes.

**Comment by YaLTeR** [comment]
Window screencasts are now implemented and merged to main, pls test

**Comment by RangerMauve** [comment]
How do I enable this capability? I'm on 25.02 with [xdg-desktop-portal-wlr](https://github.com/emersion/xdg-desktop-portal-wlr)

**Comment by RangerMauve** [comment]
Oh! My bad it's a xdg-desktop-portal-wlr issue
