### ISSUE TITLE
Menus from tray icons open behind windows

### ISSUE THREAD

**Issue by axtloss** [YaLTeR/niri#139]
Trying to use the menu of a tray icon makes the tray icon open behind the currently focused window, making it impossible to use the menu

![image](https://github.com/YaLTeR/niri/assets/60044824/37e50e5b-9a35-441c-9c4a-2b827cb4f483)

### System Information

* niri version:  niri 0.1.0 (016d3f7)

* GPU: NVIDIA GeForce RTX 3060 Mobile + Intel CometLake-H GT2

* CPU: Intel i5-10300H

**Comment by YaLTeR** [comment]
Yeah, that's a limitation currently. Put waybar on the top layer in its config to fix it.

**Comment by YaLTeR** [comment]
Presumably that fixed it.
