### ISSUE TITLE
Newm characteristics would be a good starting point

### ISSUE THREAD

**Issue by CRAG666** [YaLTeR/niri#15]
As the title says, there is TWM very similar to this that maybe I can give it a route which to follow.
https://github.com/jbuchermn/newm
https://www.youtube.com/watch?v=mDw-hMW0b70

**Comment by CRAG666** [comment]
@YaLTeR pleace check my video https://www.youtube.com/watch?v=mDw-hMW0b70

**Comment by AlexD97** [comment]
> I've seen it, yeah. But the scrollable tiling approach is a bit different in that rather than being a 2D grid, every workspace scrolls independently of the rest.
> 
> Do you have any idea in particular in mind?

It's hard to explain what I like about newm but I'll try my best. The primary advantage of using newm is that you can arrange your windows in such a way that related windows are adjacent. For instance, imagine you're writing a text file in your editor and need to simultaneously access your web browser, a specific email, and your terminal. Typically, you might view your text editor in full screen. However, there are times when you require additional information from your email, combined with content from the web. In these instances, it's helpful to view all four windows simultaneously. newm facilitates effortless switching between these different views.
