### ISSUE TITLE
focus-ring is really a background color

### ISSUE THREAD

**Issue by russelltg** [YaLTeR/niri#150]
focus-ring is awesome to have, but it doesn't play nice with transparent windows, it acts like a background color. Easy to repro with alacritty.

### System Information

* niri version: niri 0.1.0 (dd96755)

* GPU: Intel TigerLake-H GT1

* CPU: Intel i9-11900H

**Comment by kchibisov** [comment]
Use `prefer-no-csd`.

**Comment by YaLTeR** [comment]
Yeah, focus ring and border draw as background rectangles for CSD windows because they can have arbitrary window shapes. If you set `prefer-no-csd` in the niri config and then the window agrees to use SSD, the focus ring and border will draw strictly around the window.

**Comment by YaLTeR** [comment]
I added a clarifying comment into the config

**Comment by nebulosa2007** [comment]
Could you please clarify what 'SSD' means? I assume it's 'server-side decoration', but there is no such definitions in the config file.

**Comment by YaLTeR** [comment]
Good catch, improved the wording to mention the same thing as the prefer-no-csd comment.

**Comment by nebulosa2007** [comment]
It's weird, but after setting `prefer-no-csd` I can't switch to `alacritty` window when clicking by mouse on the right of left egdes of screen. Tried with `foot` but have no luck too

**Comment by YaLTeR** [comment]
That's because with CSD, alacritty draws a 1 px border, but it doesn't include it in the window geometry, so it sticks out on the side.

You can set left and right struts to get the same effect without this sticking out.

**Comment by nebulosa2007** [comment]
> You can set left and right struts to get the same effect without this client-side sticking out.

That's good that is a solution, please advise how I can to do it?

Other apps keep switching - tried firefox, a few kde apps, gtk apps, but not console emulators.

**Comment by nebulosa2007** [comment]
Not quite the same as before, but with `left 1 right 1` it looks acceptable
Thanks!

**Comment by nebulosa2007** [comment]
UPD: Commented out `prefer-no-csd` again, because when you click on the left edge of the screen, it switches to the desired window, but also scrolls it (e.g. in firefox) to the point you clicked on. it's more frustrating than disabling transparency for the console emulators. :)

**Comment by lpnh** [comment]
A small note for anyone that, like me, is wondering why Alacritty's opacity isn't being applied even after setting `prefer-no-csd` in the config. Make sure you do *not* have a  `decorations = "None"` line in your `alacritty.toml` config file:

```
[window]
# decorations = "None" (ensure to comment this out or remove)
opacity = 0.9
```

**Comment by nebulosa2007** [comment]
Finally, got opacity for console emulator - `focus-ring` off, `border` on,  `prefer-no-csd` uncomment and
```
 struts {
        left 1
        right 1
```

`Alacritty` settings above

or for `foot.ini`:
```
[colors]
alpha = 0.9
background = 000000
```

But in that case I think I can't set dim for inactive windows..
