### ISSUE TITLE
DRI / Mesa / OpenGL version mismatch on NixOS

### ISSUE THREAD

**Issue by jeLee6gi** [YaLTeR/niri#153]
I can launch niri only as a window inside another wayland session. When I try to launch it from tty I get a black screen and this output:

> 2024-02-01T11:54:57.482092Z  INFO niri: starting version 0.1.0 (unknown commit)
> 2024-02-01T11:54:57.497488Z DEBUG niri_config: loaded config from "/home/user/.config/niri/config.kdl"
> 2024-02-01T11:54:57.536293Z  INFO niri::backend::tty: using as the render node: "/dev/dri/renderD128"
> 2024-02-01T11:54:57.552694Z DEBUG niri::backend::tty: device added: 57856 "/dev/dri/card0"
> DRI driver not from this Mesa build ('23.3.3' vs '23.1.9')
> failed to bind extensions
> DRI driver not from this Mesa build ('23.3.3' vs '23.1.9')
> failed to bind extensions
> DRI driver not from this Mesa build ('23.3.3' vs '23.1.9')
> failed to bind extensions
> DRI driver not from this Mesa build ('23.3.3' vs '23.1.9')
> failed to bind extensions
> 2024-02-01T11:54:57.862559Z  WARN niri::backend::tty: error adding device: No such file or directory (os error 2)
> 2024-02-01T11:54:57.862585Z  INFO niri: listening on Wayland socket: wayland-2
> 2024-02-01T11:54:57.862599Z  INFO niri: IPC listening on: /run/user/1000/niri.wayland-2.13820.sock
> 2024-02-01T11:54:58.871381Z DEBUG niri::backend::tty: pausing session

### System Information

* niri version: niri 0.1.0 (unknown commit)

* GPU: AMD RX Vega 8

* CPU: AMD Ryzen 7 PRO 5850U

**Comment by YaLTeR** [comment]
Uh is this on nix? I happened across this issue earlier today: https://github.com/sodiboo/niri-flake/issues/4 which suggests it might be a nix package issue

**Comment by YaLTeR** [comment]
Alright.

**Comment by sodiboo** [comment]
> After switching to the flake and following the suggestion in [sodiboo/niri-flake#4](https://github.com/sodiboo/niri-flake/issues/4) my issue went away.

The latest version of my flake should address this issue "properly"/"permanently". You no longer need to override the `nixpkgs` input. See: https://github.com/sodiboo/niri-flake/issues/4#issuecomment-1939312820
