### ISSUE TITLE
gesture doesn't respect natural-scroll setting

### ISSUE THREAD

**Issue by superiums** [YaLTeR/niri#154]
### System Information

* niri version: v0.1.0-17-g2e50f8d-modified

* GPU:  amd 4800u

* CPU: amd 4800u

when i turn off (commented) natural-scroll for touchpad, the gesture still use natural-scroll ( 3 finger swipe down,  leed to previous workspace ).

**Comment by YaLTeR** [comment]
Good catch, fixed in b23dd4b800285f120ad556d77c2357b17c1ea6a2
