### ISSUE TITLE
DISPLAY environment variable error?

### ISSUE THREAD

**Issue by swyknox** [YaLTeR/niri#159]
### System Information

* niri version: niri 0.1.0 (dba522b)
* GPU: AMD ATI Radeon Vega Series / Radeon Vega Mobile Series
* CPU: AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx (8) @ 2.100GHz

---

Well, I don't know if I'm doing this in the right place, forgive me if I do.
I'm getting the following error when trying to run Steam (flatpak) on niri:

![Screnshot-2024-02-02-21-31-36](https://github.com/YaLTeR/niri/assets/52772425/385ed991-2668-4bad-99b5-8d4650a19508)

Even exporting DISPLAY, I couldn't get it to work.

**Comment by YaLTeR** [comment]
This is because niri doesn't support rootless Xwayland. You can run Steam in rootful Xwayland as described here: https://github.com/YaLTeR/niri/wiki/Xwayland
