### ISSUE TITLE
Scaling is not applied for the cursor

### ISSUE THREAD

**Issue by kchibisov** [YaLTeR/niri#16]

**Comment by kchibisov** [comment]
Blocked on https://github.com/Smithay/smithay/pull/1152

**Comment by YaLTeR** [comment]
For client cursors what this needs, I believe, is sending output_enter / output_leave to cursor (and DnD) surfaces. I think if [this helper used by Space in Smithay](https://github.com/Smithay/smithay/blob/74ef59a3f8b6a1f86a74388590f2f852040354e4/src/desktop/space/wayland/mod.rs#L32) was made public, it could be used to do that.

**Comment by YaLTeR** [comment]
Trying to do this: https://github.com/Smithay/smithay/pull/1153

**Comment by YaLTeR** [comment]
Fixed for client cursors in 382c049b5a67194761b75181bcd0506791602060.
