### ISSUE TITLE
Firefox drag cursor sometimes gets stuck

### ISSUE THREAD

**Issue by YaLTeR** [YaLTeR/niri#160]
![image_20240203064838.png](https://github.com/YaLTeR/niri/assets/1794388/35520362-c050-4d69-950a-fc01bdf9dd82)

Until you DnD a tab or something, which fixes it.

**Comment by FreeFull** [comment]
Specifically, it seems to always get stuck when you select and drag some text on a web page.

**Comment by YaLTeR** [comment]
I think this was fixed by the recent changes in Smithay that were applied in 279659ac90eef4082157f427f006c9a4c5a02ac2.

**Comment by FreeFull** [comment]
It still happens to me with the latest git version of niri

**Comment by YaLTeR** [comment]
Huh. For me it changes to the regular cursor when I drag text around in Firefox.

**Comment by kchibisov** [comment]
Yeah, it's still stuck with the latest git the way it was before.

**Comment by lpnh** [comment]
Looks like the issue has been fixed. 🎉

**Comment by FreeFull** [comment]
Yeah, I can't get it to happen any more. Not sure if niri fixed it, or the recent Firefox update, though.

**Comment by YaLTeR** [comment]
I think it was fixed here: https://github.com/Smithay/smithay/commit/0f2437e586bec0460a3de045f40355ffafba17cb
