### ISSUE TITLE
pre-build binaries / packages

### ISSUE THREAD

**Issue by c33s** [YaLTeR/niri#170]
i would love to try niri on my debian system but having no pre-build binaries is holding me back. 

building multiplatform binaries and adding it to the release assests would be so awesome

**Comment by YaLTeR** [comment]
Hey! With a compositor it's not really very feasible to build multiplatform binaries as there are a lot of system dependencies. I made a COPR for Fedora, which is the distro that I use, so someone would have to make a repo for Debian I assume.

**Comment by frankier** [comment]
See https://github.com/YaLTeR/niri/pull/2681 as a sort "maybe it could be this easy?" PR.
