### ISSUE TITLE
Hidden firefox windows with tabs doing some animations consume high CPU usage

### ISSUE THREAD

**Issue by kchibisov** [YaLTeR/niri#18]
The strangest part is that when window is in focus, the CPU usage goes to normal most of the time.

**Comment by kchibisov** [comment]
While discussing it, I remembered that firefox tends to do things like that

```
wl_surface.frame();
wl_surface.commit();
```

Without any buffer attached. Such requests shouldn't trigger any rendering, from what I can say, since they likely are used to drive the `requestAnimationFrame` event on the web for the underlying apps. Yet those apps may not even render in the end.

**Comment by YaLTeR** [comment]
Fixed in https://github.com/YaLTeR/niri/commit/404661ed8d9efc60d70547287d81953c1025a95b by introducing per-surface frame callback throttling to one callback per monitor refresh cycle.

**Comment by YaLTeR** [comment]
Hidden windows still receive frame callbacks, I'll deal with that later. But it will no longer cause busy looping.

**Comment by YaLTeR** [comment]
https://github.com/YaLTeR/niri/commit/5b6b3fcfbe61695b0e5d27e8a08592a9ebd412b0 makes it so hidden windows no longer receive frame callbacks.
