### ISSUE TITLE
`niri msg action` not working

### ISSUE THREAD

**Issue by KiaraGrouwstra** [YaLTeR/niri#183]
having just updated niri, i got to try `niri msg action`, but have yet to get it to actually respond to commands.

```
$ niri msg action focus-workspace-up
$ niri msg action focus-workspace-down
$ niri msg action center-column
$ niri msg action spawn -- kitty
$ niri msg action close-window
```

any of these commands for me exited silently (0 status code) without giving further info.
for what it's worth, the commands did work for me from `config.kdl`.

### System Information

* niri version: #182

**Comment by YaLTeR** [comment]
Did you restart the compositor itself?

**Comment by KiaraGrouwstra** [comment]
my apologies, that did it!

**Comment by YaLTeR** [comment]
I should add error reporting back to the IPC client

**Comment by YaLTeR** [comment]
Added error reporting in 0931447ec178ed503ff0a085896ec6908cf1292e.
