### ISSUE TITLE
Opera doesn't show up

### ISSUE THREAD

**Issue by NoahFraiture** [YaLTeR/niri#187]
Hey, when I try to open Opera it doesn't show up in niri. When I open niri inside plasma, opera will open in background and when I start it with niri as WM it doesn't show up at all. Only firefox works
### System Information

* niri version: 
* 0.1.1

* GPU: 
* Nvidia RTX 4060

* CPU:
13th Gen Intel(R) Core(TM) i7-13700H

**Comment by YaLTeR** [comment]
Does it use Wayland? That sounds like it uses X11 which niri doesn't do.

**Comment by nebulosa2007** [comment]
> Does it use Wayland? That sounds like it uses X11 which niri doesn't do.

I think the same. 

Try [this](https://forums.opera.com/topic/49172/status-of-wayland-support-and-how-to-enable/5):
1. `opera --enable-features=UseOzonePlatform --ozone-platform=wayland %U`
2. set the (opera://flags/#ozone-platform-hint) flag to "Wayland."

First step work for `Electron` apps too

**Comment by NoahFraiture** [comment]
Indeed it works thank you !
