### ISSUE TITLE
GTK theming issue using niri-session vs niri

### ISSUE THREAD

**Issue by KiaraGrouwstra** [YaLTeR/niri#193]
hey there,
i'd so far accidentally been running `niri` over `niri-session`, and now that i tried the latter i've come across some differences among the two. while `niri-session` fixed XDG autostart for me (as expected), it seems that GTK prompts, like context menus in firefox as well as vscodium's "are you sure you wish to close this unsaved file" dialog, no longer use my GTK dark theme like they did using `niri`.
while this might also touch upon e.g. `xdg-desktop-portal-gnome`, is this a known issue by any chance?

**Comment by YaLTeR** [comment]
This might be caused by GTK now reading settings from the portal (but not sure). If that's the case, the portal will forward the GNOME settings, i.e. to set the dark style preference you'd need to do

```
dconf write /org/gnome/desktop/interface/color-scheme '"prefer-dark"'
```

**Comment by sodiboo** [comment]
nix sidenote that is not necessarily relevant to the issue, but to the user experiencing it: dconf can be configured in home-manager using `dconf.settings`, and [they also mentioned using stylix](https://github.com/sodiboo/niri-flake/issues/5#issuecomment-1942867126), in which case the proper solution should be `stylix.polarity = "dark"` in the nix configuration, which [sets dconf settings for you](https://github.com/danth/stylix/blob/50cae37cfe23e5ad202ed53f48529139dfa0d008/modules/gnome/hm.nix#L22-L25) (along with also affecting the general stylix theme, i guess)

**Comment by KiaraGrouwstra** [comment]
interesting, i have in fact had that set (indeed thru stylix since using that). i might wanna investigate a bit more.

**Comment by YaLTeR** [comment]
I guess this is not a niri issue per se. If there's something concrete we can document it on the wiki.

**Comment by KiaraGrouwstra** [comment]
i'll close until further indication this wasn't about my setup.
