### ISSUE TITLE
Output not treated as disconnected when powered off

### ISSUE THREAD

**Issue by EdenQwQ** [YaLTeR/niri#199]
When I power off my secondary monitor (unplug its power supply), niri doesn't seem to treat it as disconnected. Windows in it would not appear in the primary monitor, and the cursor can still go beyond the screen. `niri msg outputs` also show it as in use.
The expected "disconnect" behavior only happens when I unplug the HDMI port.

### System Information

* niri version: niri 0.1.1 (unknown commit)

* GPU: Intel Iris Xe

* CPU: Intel i5-12500H

**Comment by EdenQwQ** [comment]
Here is the log when I power the monitor off and replug it. I can move focus to the "disconnected" monitor and move a window from it to the primary monitor even though it is recorded as "disconnected" in the log. Also, the log looks exactly the same when I unplug the HDMI port. But the behavior is totally different.

```
2024-02-15T15:12:09.335871Z DEBUG niri::backend::tty: device changed: 57856
2024-02-15T15:12:09.342452Z DEBUG niri::backend::tty: disconnecting connector: "HDMI-A-1"
2024-02-15T15:12:10.835707Z DEBUG niri::backend::tty: device changed: 57856
2024-02-15T15:12:10.868811Z DEBUG niri::backend::tty: connecting connector: HDMI-A-1
2024-02-15T15:12:10.868823Z DEBUG niri::backend::tty: picking mode: Mode { name: "1920x1080", clock: 148500, size: (1920, 1080), hsync: (2008, 2052, 2200), vsync: (1084, 1089, 1125), hskew: 0, vscan: 0, vrefresh: 60, mode_type: ModeTypeFlags(DRIVER) }
2024-02-15T15:12:10.870643Z DEBUG niri::niri: putting output HDMI-A-1 at x=0 y=0
```

**Comment by YaLTeR** [comment]
So, it's normal that "turning off" a monitor doesn't actually disconnect it. If you try other compositors like mutter you should see the same behavior (or at least I see the same on my monitors). Although it is somewhat weird that *unplugging the power supply* would keep it connected. Guess there's some battery in there keeping it on?

When you "turn on" a monitor it usually replugs itself, i.e. quickly disconnects and connects. If you look at the timestamps in the log that you sent, you can see it happens within 1 second.

So yeah, if you want to disable the monitor, you'll need to either physically unplug it, or set `off` in the niri config (which live reloads, so this can be scripted).

**Comment by EdenQwQ** [comment]
> So, it's normal that "turning off" a monitor doesn't actually disconnect it. If you try other compositors like mutter you should see the same behavior (or at least I see the same on my monitors). Although it is somewhat weird that _unplugging the power supply_ would keep it connected. Guess there's some battery in there keeping it on?
> 
> When you "turn on" a monitor it usually replugs itself, i.e. quickly disconnects and connects. If you look at the timestamps in the log that you sent, you can see it happens within 1 second.
> 
> So yeah, if you want to disable the monitor, you'll need to either physically unplug it, or set `off` in the niri config (which live reloads, so this can be scripted).

Alright. That's indeed weird tho.
