### ISSUE TITLE
Chrome(ium) layout strange for new windows

### ISSUE THREAD

**Issue by krgn** [YaLTeR/niri#200]
When creating new `chromium` and `google-chrome-stable` windows (e.g. via `CTRL-n`) they do not adhere to the layout rules (e.g. gaps) and overlap with other windows.  See this screenshot for an example.

![image](https://github.com/YaLTeR/niri/assets/422437/2f314e20-d3f6-4aef-b2b9-29b5c342a516)

One quick fix this is by editing the config, adjusting the gaps value. This causes the layout to be applied to those windows and fix the overlaps.

### System Information

* niri version: rev `fa3bc69f94fdd2a14e21bf0573722fcafbc045ba`

* GPU: `05:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Lucienne (rev c1)`

* CPU: `AMD Ryzen 7 5700U with Radeon Graphics`

**Comment by YaLTeR** [comment]
This is likely a Chromium bug where it sends a wrong geometry. For me resizing it a few times fixed it I think.

**Comment by FreeFull** [comment]
I've noticed the exact same bug in sway, I think it has to do with how Chromium treats server-side decorations. Chromium seems to properly size/position the window when it uses client-side decorations (that is, when prefer-no-csd isn't set).

**Comment by YaLTeR** [comment]
> Chromium seems to properly size

With CSD there's still a small issue it seems, Chromium initially sets its size a bit smaller than requested. But the window geometry remains correct.

**Comment by YaLTeR** [comment]
I documented it here on the wiki: https://github.com/YaLTeR/niri/wiki/VSCode,-Chromium,-WezTerm

**Comment by krgn** [comment]
Thank you for looking into it 🙏🏼
