### ISSUE TITLE
Session lock refused while monitors powered off

### ISSUE THREAD

**Issue by YaLTeR** [YaLTeR/niri#205]
Session lock requires all monitors to be blanked before succeeding, to prevent the possibility of a sensitive frame showing up at a later point, especially when using lock-on-suspend. When the monitors are powered off, niri cannot submit a blank frame, so it fails the lock.

One solution is to just power on the monitors to blank them, and potentially power right back off.

@cmeissl do you think this could be solved without powering on the monitors? I'm thinking of a case like: monitors are powered off, the user presses the suspend button, swayidle runs swaylock before suspending. If we don't power on right away here to blank the monitors, can the old framebuffer show up upon unsuspending (which we need to avoid)?

**Comment by cmeissl** [comment]
Maybe we can add something like `clear_state` on `DrmCompositor`/`DrmSurface` which will remove all active fb without enabling the crtc (probably also disabling it if it is currently enabled). 
But something like this should already be possible with `DrmDevice::reset_state`.

**Comment by cmeissl** [comment]
Thinking about this again I am not sure if there even is an issue to solve on how its currently done.
Drm just guarantees that resources are still valid after a resume, but it should keep its state. So if we disabled the
crtc prior to suspend it should not get activated unless we do so explicitly. As niri no longer just sets the dpms state, but actives a crtc by scheduling a frame with `queue_frame` it should already work correct by rendering a blank frame on `render_frame` if the session is locked.

**Comment by cmeissl** [comment]
But yeah, I guess you are referreing to this part in the spec:

> The locked event must not be sent until a new "locked" frame (either from a session lock surface or the compositor blanking the output) has been presented on all outputs and no security sensitive normal/unlocked content is possibly visible.

**Comment by YaLTeR** [comment]
Made it work in 82fffdea80170571eb5ad176cf0b23eb24b0bc5d.
