### ISSUE TITLE
Unable to bind `Mod+Escape`

### ISSUE THREAD

**Issue by vollowx** [YaLTeR/niri#207]
```kdl
binds {
    Mod+Escape { spawn "swaylock"; }
}
```

This doesn't work. `wev` says that the key's name is `Escape`, so I just used it.

I've also tried `ESC`, didn't work either.

### System Information

* niri version: niri 0.1.1 (256e886)

* GPU: Intel Corporation CometLake-U GT2

* CPU: Intel Core i5-10210U CPU @ 1.60GHz

**Comment by YaLTeR** [comment]
Works here on 0.1.2.

**Comment by vollowx** [comment]
Thanks, so it does! 👍
