### ISSUE TITLE
Merge current window to left column has not animations, but merge to right has

### ISSUE THREAD

**Issue by SR-MyStar** [YaLTeR/niri#215]
### System Information

* niri version: `niri 0.1.2 (0c5e09a)`

* GPU: `Intel Alder Lake-S GT1 [UHD Graphics 730]`

* CPU: `12th Gen Intel i5-12400 (12) @ 4.4GHz`

Merge current window to left column has not animations, but merge to right column has.

https://github.com/YaLTeR/niri/assets/139795416/770af5d1-9013-422c-bf20-6072754663b1

**Comment by YaLTeR** [comment]
This is a side effect of a bit weird and hacky view animation code right now. I will eventually rework it, then this will be fixed.

**Comment by YaLTeR** [comment]
This is now fixed with the introduction of a proper set of animations.
