### ISSUE TITLE
`env` options (similar as hyprland)

### ISSUE THREAD

**Issue by SR-MyStar** [YaLTeR/niri#227]
### Discussed in https://github.com/YaLTeR/niri/discussions/225

<div type='discussions-op-text'>

<sup>Originally posted by **SR-MyStar** February 24, 2024</sup>
I think `niri` needs a way to set environment variables in itself config file.

In hyprland, I'm using `env = QT_QPA_PLATFORMTHEME, qt5ct` to set environment variables for window manager.
In niri, I can write `QT_QPA_PLATFORMTHEME=qt5ct` in `/etc/environment`.

But if I do it, these environment variables are play a part in everywhere for my system.
It doesn't make a difference than I set environment variables in window manager config file if I only use wayland.

but I'm not only use niri and other wayland window manager, I also use `bspwm`(x11 window manager), because some x11 apps are doesn't work use xwayland, they are only work in raw x11 environment, If I write `QT_QPA_PLATFORM=wayland` in `/etc/environment`, in `bspwm`, qt apps are all doesn't work.

So `niri` needs a way to set environment variables only for itself. such as this
```kdl
env {
    QT_QPA_PLATFORMTHEME "qt5ct"
}
```</div>

**Comment by YaLTeR** [comment]
Implemented in https://github.com/YaLTeR/niri/commit/e278e871c357c4832f29629e4f65f57ff0d0ded0
