### ISSUE TITLE
Can use `~` to replace home path

### ISSUE THREAD

**Issue by SR-MyStar** [YaLTeR/niri#228]
### Discussed in https://github.com/YaLTeR/niri/discussions/226

<div type='discussions-op-text'>

<sup>Originally posted by **SR-MyStar** February 24, 2024</sup>
Use
```
spawn-at-startup "~/.config/niri/scripts/at-startup"
binds {
    SUPER+Alt+J { spawn "~/.config/niri/scripts/control/volume" "--dec"; }
}
```
to replace
```
spawn-at-startup "/home/xxx/.config/niri/scripts/at-startup"
binds {
    SUPER+Alt+J { spawn "/home/xxx/.config/niri/scripts/control/volume" "--dec"; }
}
```</div>

**Comment by YaLTeR** [comment]
Implemented in https://github.com/YaLTeR/niri/commit/e278e871c357c4832f29629e4f65f57ff0d0ded0
