### ISSUE TITLE
Firefox tab bar is glitchy and flickering

### ISSUE THREAD

**Issue by phuhl** [YaLTeR/niri#237]
Cannot take a screenshot, because everytime I try it looks ok, so here is a foto from my phone.

![IMG_1942](https://github.com/YaLTeR/niri/assets/16835755/5ea4be87-c8c5-4364-a5c7-1bdbba4ee9e2)

The tab bar seems to be rendering all over itself, it is flickering and unusable.

### System Information

* niri version: niri 0.1.2 (v0.1.2-56-g24537ec)

* GPU: Intel® Iris® Xe Graphics

* CPU: 13th Gen Intel® Core™ i7-1360P (18 MB cache, 12 cores, up to 5.00 GHz Turbo)
https://wiki.archlinux.org/title/Dell_XPS_13_Plus_(9320)

**Comment by YaLTeR** [comment]
Uhh, that might be a Firefox issue with the damage it submits. Does it go away if you resize the window?

**Comment by phuhl** [comment]
Kinda, in Firefox becomes bigger, the new area looks ok-ish (despite black text on black background) but as soon as I hover over or scroll on the tab bar it brakes (hence supporting your hypothesis, I guess). But also, the background color is broken for some reason...

![IMG_1943](https://github.com/YaLTeR/niri/assets/16835755/f971007f-5cdb-43f1-80c2-ab5a052aeba9)

**Comment by YaLTeR** [comment]
Have you seen this happen on other compositors like sway or mutter or weston?

**Comment by phuhl** [comment]
No, I tested sway and river and both work fine with FF

**Comment by phuhl** [comment]
Just figured out, that setting the "Title Bar" check mark in the appearance settings kinda fixes it:

![image](https://github.com/YaLTeR/niri/assets/16835755/3e41da12-8811-4330-abb7-b2952c177eaf)

There is still some flickering, but at least the tabs are usable again

**Comment by YaLTeR** [comment]
Hm, odd. Maybe something weird going on in the GTK theme? Strange that it doesn't happen on other compositors.

**Comment by phuhl** [comment]
I figured it out, I had some custom CSS in the gtk.css file to hide GTK client side window decorations (was needed in river). After removing that, the flickering is gone
