### ISSUE TITLE
DPMS support

### ISSUE THREAD

**Issue by kchibisov** [YaLTeR/niri#24]
probably with just a settings in the config to power display off/on for now.

**Comment by YaLTeR** [comment]
Smithay doesn't have a helper at the moment, but seems simple enough: https://github.com/catacombing/catacomb/blob/438a2a12a96de9276897c7e687daaa8613474b39/src/udev.rs#L536

**Comment by YaLTeR** [comment]
Implemented in 189d1bd97b7aa241b5ad651145ca4d3ef483f505 as a `power-off-monitors` bind, on Mod+Shift+P by default. At least until a better idle tracking solution.

**Comment by tmccombs** [comment]
Is there a way to power off a single monitor?

**Comment by YaLTeR** [comment]
There isn't, only all at once. Wasn't really planning on adding that either.

**Comment by tmccombs** [comment]
Actually, it looks like I can use `niri msg output $output off` to turn a monitor off (or on with the `on` action).

**Comment by Markus328** [comment]
> Actually, it looks like I can use `niri msg output $output off` to turn a monitor off (or on with the `on` action).

This turns out to be a logical disable, it moves all the clients from the output to another
