### ISSUE TITLE
Tray Icon Menu hover has offset to mouse pointer position

### ISSUE THREAD

**Issue by phuhl** [YaLTeR/niri#244]
When hovering over Gammastep tray icon menu points, there seems to be some offset between the mouse and the highlighted menu items: 
![image](https://github.com/YaLTeR/niri/assets/16835755/7531db84-ac9b-4114-8f05-0394962eea5b)

### System Information

* niri version: niri 0.1.2 (v0.1.2-56-g24537ec)

* GPU: Intel® Iris® Xe Graphics

* CPU: 13th Gen Intel® Core™ i7-1360P (18 MB cache, 12 cores, up to 5.00 GHz Turbo)
https://wiki.archlinux.org/title/Dell_XPS_13_Plus_(9320)

* gammastep 2.0.9-2 (installed via arch pacman)

**Comment by 0xDEAD-C0DE** [comment]
@phuhl I little bit off topic here. How are you using gammastep on Archlinux? Doesn't gammastep require wlroots gamma-control protocols? Which is not implemented on niri yet.

**Comment by YaLTeR** [comment]
I'll need to check, maybe some buffer position isn't added properly in Smithay.

**Comment by phuhl** [comment]
True, it is for all tray icon menus, for me, too.

**Comment by rustysec** [comment]
I don't seem to see this behavior in cosmic, would that rule out a Smithay problem?

**Comment by YaLTeR** [comment]
I just checked and there's the same issue both on Anvil and on cosmic-comp. So it's a Smithay issue likely. Looks as if the cursor hotspot is being ignored I think.

**Comment by YaLTeR** [comment]
Found it: https://github.com/Smithay/smithay/pull/1511

**Comment by YaLTeR** [comment]
Should be fixed in https://github.com/YaLTeR/niri/commit/48329244832c061e2920b2d097b53c13dde72e5a

**Comment by phuhl** [comment]
Can confirm, fixed it for me. Thank you!
