### ISSUE TITLE
LibreOffice Impress Froze

### ISSUE THREAD

**Issue by Loungagna** [YaLTeR/niri#250]
When fuzzel was used to launch LibreOffice Impress, the libreoffice animation started (not centered but up left of the screen) and the default LibreOffice Impress window open but was froze (not reaction to the mouse, or Ctrl-O to open a document, etc.)

### System Information

* niri version: niri 0.1.2 (62892d6)

* GPU: AMD ATI c4:00.0 Phoenix1 + AMD ATI Radeon RX 7700S XT/PRO W7600

* CPU: AMD Ryzen 7 7840HS w/ Radeon 780M Graphics (16) @ 5.137GHz

**Comment by YaLTeR** [comment]
When I open it I get this dialog:

![image](https://github.com/YaLTeR/niri/assets/1794388/50af746d-b67a-4d99-b9f5-6e53d1e7f2b0)

While it's open it prevents input from the main window. Maybe you got the dialog somewhere else where it's not immediately visible?
