### ISSUE TITLE
broken musl build after 0.1.3

### ISSUE THREAD

**Issue by pg83** [YaLTeR/niri#252]
```   
Compiling niri v0.1.3 (/home/pg/ix_root/build/cTZPjK5qXpbukrYK/src)ithay
error[E0432]: unresolved import `libc::close_range`io, niri-config, niri, smithay
  --> src/utils/spawning.rs:10:5
   |
10 | use libc::close_range;
   |     ^^^^^^^^^^^^^^^^^ no `close_range` in the root

For more information about this error, try `rustc --explain E0432`.
error: could not compile `niri` (lib) due to previous error
warning: build failed, waiting for other jobs to finish...
```

I think that musl does not implement close_range()

**Comment by YaLTeR** [comment]
Hm, I see. Do you need systemd support? If not then I can patch this out relatively easily.

**Comment by kchibisov** [comment]
systemd doesn't work on musl.

**Comment by pg83** [comment]
> Hm, I see. Do you need systemd support? If not then I can patch this out relatively easily.

No, I do not need systemd, In fact, it is already disabled on my build.

**Comment by YaLTeR** [comment]
Try 1971a41fdd68f0a33bd5db22f776821682c23206, should be fixed I think.

> systemd doesn't work on musl.

postmarketOS might have made it work: https://postmarketos.org/blog/2024/03/05/adding-systemd/

**Comment by kchibisov** [comment]
>postmarketOS might have made it work: https://postmarketos.org/blog/2024/03/05/adding-systemd/

upstream one doesn't work, so if you heavy patch stuff maybe you heavy patch other stuff to work with it.

**Comment by pg83** [comment]
https://github.com/YaLTeR/niri/commit/1971a41fdd68f0a33bd5db22f776821682c23206 fixed my problem, thanks
