### ISSUE TITLE
Screen sharing crashes session

### ISSUE THREAD

**Issue by migue07juegos** [YaLTeR/niri#258]
I launch niri from tty using `dbus-run-session niri --session` since my distro (Void Linux) doesn't use systemd. When I try to share my screen in OBS or in Firefox, it crashes the session when selecting the monitor.

If I restart the session running the same command as before, now it works as expected and I'm able to share my screen.

Another thing is that if i stop pipewire before restarting the session (using `pkill pipewire`) it keeps crashing the session.
### System Information

* niri version: niri 0.1.3 (0c57815)

* GPU:  AMD RX6800

* CPU: AMD Ryzen 7 3800X

[niri.log](https://github.com/YaLTeR/niri/files/14644418/niri.log)

**Comment by YaLTeR** [comment]
Thanks for the report. It appears that when `niri` starts, it cannot connect to PipeWire (there's no error message about it in your log for some reason?), and a missing check later on causes the panic. I will fix the panic, but then screencast will simply not work unless PipeWire is started ahead of time. I'm not sure if it's something niri can influence, or if you need to run it manually on your setup?

**Comment by migue07juegos** [comment]
Thanks for the quick reply! Can confirm the crash is fixed.

Also you're right about pipewire, I used to start it using niri's config `spawn-at-startup "pipewire"`. After removing that, and using a script to launch pipewire before niri it now works as expected.
