### ISSUE TITLE
Animation could end up in transition state

### ISSUE THREAD

**Issue by kchibisov** [YaLTeR/niri#26]
If you do a e.g. `right to left` swipe and during it try to do `left to right` the animation could end up in the not fully transition state, as in 2 animations start to compensate each other.

**Comment by YaLTeR** [comment]
This is more or less intended. Whenever you switch focus, it takes your current camera position and computes the target camera position from it to minimize movement. So when you quickly focus right and left, your original window is still fully on screen, so no camera movement is required, and it just remains "in the middle of the animation".

**Comment by YaLTeR** [comment]
You could change it to use the final, rather than current, camera position to compute the new camera position, which would make it look less like the animations are getting stuck at the expense of more camera movement. Could try that and see how it looks.

**Comment by YaLTeR** [comment]
Actually, there's a separate issue where if an animation frame doesn't result in damage it'll get stuck, which I'll fix soon, but I'm not sure you're talking about that?
