### ISSUE TITLE
Second monitor display

### ISSUE THREAD

**Issue by AleitoG** [YaLTeR/niri#260]
runing niri msg outputs dont recognize  the second monitor at HDMI-1-0 

### System Information

* niri version: niri 0.1.3

* GPU: NVIDIA GTX 1650

* CPU: INTEL CORE I5 12500H

**Comment by YaLTeR** [comment]
That's weird; does it work on other compositors like sway?

**Comment by AleitoG** [comment]
I never try another compositor, this is the first one, my previous setup was using dwm in x11 and i dont have any issues with the monitors , my linux distribution is void-glibc

**Comment by YaLTeR** [comment]
NVIDIA with Wayland is still a bit incomplete, which is why I'm asking to try a different (more established) compositor. It might be an NVIDIA driver issue.

**Comment by megatux** [comment]
I have it working very well now, but not sure if I'm using the integrated Intel or the dedicated GTX 1650. Any tip to know it?

niri 0.1.4 , previous versions had several issues.


```
GPUs:
  GPU 0:
    Name: NVIDIA Corporation TU117M [GeForce GTX 1650 Mobile / Max-Q]
    IDs: D=1f91 V=10de SD=1332 SV=1025
    Driver: nvidia
  GPU 1:
    Name: Intel Corporation CoffeeLake-H GT2 [UHD Graphics 630]
    IDs: D=3e9b V=8086 SD=1331 SV=1025
    Driver: i915
OS: Nobara Linux 39 (GNOME Edition) (linux)
```

**Comment by YaLTeR** [comment]
The niri log should say which device it uses for rendering, I guess that would be nvidia

**Comment by YaLTeR** [comment]
@AleitoG could you try again? And also try on sway or other Wayland compositor?

**Comment by AleitoG** [comment]
> @AleitoG could you try again? And also try on sway or other Wayland compositor?

thanks, I already use the newest version of niri and nvidia drivers (555.42.02_1) as well and the 2nd monitor works properly without another configuration, it's worth say that the nvidia driver version, isn't in production yet, its a beta

**Comment by YaLTeR** [comment]
Is the second monitor connected to NVIDIA or to the Intel iGPU?

**Comment by AleitoG** [comment]
the nvdia gpu, I already update into the last commit ( 2ac8d840343dc964981507353c9128c68361cb6f ) and now its working but with the  mpv papermpvpaper-1.6_1  and at the moment of resize there is a bug that the video seems weird like in the image... 
![WhatsApp Image 2024-05-25 at 5 44 23 PM](https://github.com/YaLTeR/niri/assets/132848197/3f75696b-f2fc-48b9-bf74-da4df6855c3b)

**Comment by YaLTeR** [comment]
Alright, that's probably missing explicit sync  (waiting for a Smithay PR). Looks like there's no niri-specific issue here after all?

**Comment by AleitoG** [comment]
yeah thanks, I fix it using (render-drm-device "/dev/dri/renderD129") on the debug section in the niri config.kdl
