### ISSUE TITLE
Damage for sticky windows is not computed correctly

### ISSUE THREAD

**Issue by phuhl** [YaLTeR/niri#262]
Sticky windows with transparent parts have the wrong background when switching windows below them.  Could not take a screenshot of it, hat to take a foto. Upper notification was produced on a dark background, then I moved focus to emacs (white background). Second notification was produced directly on bright background. Note how the corners of the first are dark, but should be white.

![damage](https://github.com/YaLTeR/niri/assets/16835755/d6e5169c-722c-4c8f-a1ae-a0292d3e3f26)

### System Information

niri version: niri 0.1.3 (v0.1.3-31-g4740682)

GPU: Intel® Iris® Xe Graphics

CPU: 13th Gen Intel® Core™ i7-1360P (18 MB cache, 12 cores, up to 5.00 GHz Turbo)
https://wiki.archlinux.org/title/Dell_XPS_13_Plus_(9320)

**Comment by phuhl** [comment]
The window is a GTK window. Here is the glade file, that produced it: https://github.com/phuhl/linux_notification_center/blob/feature/wayland/notification.glade

**Comment by YaLTeR** [comment]
Weird because I use a semitransparent `mako` for notifications, which also uses layer-shell, and it seems to work fine so far.

**Comment by cmeissl** [comment]
That could be caused by wrongly set opaque regions by the client. Can you provide a WAYLAND_DEBUG log of the client?

**Comment by phuhl** [comment]
How would I obtain those?

**Comment by cmeissl** [comment]
> How would I obtain those?

`libwayland` has an integrated debug output which can be enabled by setting the `WAYLAND_DEBUG` environment variable. Running a client with `WAYLAND_DEBUG=1` or `WAYLAND_DEBUG=client` should print out all requests sent to the compositor and events received from the compositor. For example `WAYLAND_DEBUG=client weston-terminal` would produce an output similar to this: 

```
~ WAYLAND_DEBUG=client weston-terminal
[ 875915.992]  -> wl_display@1.get_registry(new id wl_registry@2)
[ 875916.006]  -> wl_display@1.sync(new id wl_callback@3)
[ 875916.319] wl_display@1.delete_id(3)
[ 875916.337] wl_registry@2.global(1, "wl_compositor", 6)
[ 875916.343]  -> wl_registry@2.bind(1, "wl_compositor", 3, new id [unknown]@4)
[ 875916.347] wl_registry@2.global(2, "wl_subcompositor", 1)
[ 875916.350]  -> wl_registry@2.bind(2, "wl_subcompositor", 1, new id [unknown]@5)
[ 875916.354] wl_registry@2.global(3, "xdg_wm_base", 6)
[ 875916.357]  -> wl_registry@2.bind(3, "xdg_wm_base", 5, new id [unknown]@6)
[ 875916.360] wl_registry@2.global(6, "zwlr_layer_shell_v1", 4)
[ 875916.363] wl_registry@2.global(7, "ext_session_lock_manager_v1", 1)
[ 875916.365] wl_registry@2.global(8, "wl_shm", 1)
[ 875916.368]  -> wl_registry@2.bind(8, "wl_shm", 1, new id [unknown]@7)
[ 875916.371] wl_registry@2.global(9, "zxdg_output_manager_v1", 3)
[ 875916.374] wl_registry@2.global(10, "zwp_tablet_manager_v2", 1)
[ 875916.380]  -> wl_registry@2.bind(10, "zwp_tablet_manager_v2", 1, new id [unknown]@8)
[ 875916.383] wl_registry@2.global(11, "zwp_pointer_gestures_v1", 3)
[ 875916.386] wl_registry@2.global(12, "zwp_relative_pointer_manager_v1", 1)
[ 875916.389]  -> wl_registry@2.bind(12, "zwp_relative_pointer_manager_v1", 1, new id [unknown]@9)
[ 875916.392] wl_registry@2.global(13, "zwp_pointer_constraints_v1", 1)
[ 875916.395]  -> wl_registry@2.bind(13, "zwp_pointer_constraints_v1", 1, new id [unknown]@10)
[ 875916.398] wl_registry@2.global(14, "ext_idle_notifier_v1", 1)
[ 875916.401] wl_registry@2.global(15, "zwp_idle_inhibit_manager_v1", 1)
[ 875916.404] wl_registry@2.global(16, "wl_data_device_manager", 3)
[ 875916.407]  -> wl_registry@2.bind(16, "wl_data_device_manager", 3, new id [unknown]@11)
[ 875916.410] wl_registry@2.global(17, "zwp_primary_selection_device_manager_v1", 1)
[ 875916.413] wl_registry@2.global(18, "zwlr_data_control_manager_v1", 2)
[ 875916.419] wl_registry@2.global(19, "wp_presentation", 1)
[ 875916.422] wl_registry@2.global(20, "wp_security_context_manager_v1", 1)
[ 875916.424] wl_registry@2.global(21, "zwp_text_input_manager_v3", 1)
[ 875916.427] wl_registry@2.global(22, "zwp_input_method_manager_v2", 1)
[ 875916.429] wl_registry@2.global(23, "zwp_virtual_keyboard_manager_v1", 1)
[ 875916.432] wl_registry@2.global(24, "zwlr_foreign_toplevel_manager_v1", 3)
[ 875916.434] wl_registry@2.global(25, "zwlr_screencopy_manager_v1", 1)
[ 875916.437] wl_registry@2.global(26, "wp_viewporter", 1)
[ 875916.440]  -> wl_registry@2.bind(26, "wp_viewporter", 1, new id [unknown]@12)
[ 875916.444] wl_registry@2.global(27, "zxdg_exporter_v2", 1)
[ 875916.452] wl_registry@2.global(28, "zxdg_importer_v2", 1)
```

**Comment by YaLTeR** [comment]
The new niri has a [debug key binding](https://github.com/YaLTeR/niri/wiki/Configuration:-Debug-Options#debug-toggle-opaque-regions) to enable opaque region display. Could you check if this window is covered in blue? In that case the niri behavior is expected, and it would be likely a client bug.

This log seems to imply so as well:
```
[3120925.328]  -> wl_shm_pool@36.create_buffer(new id wl_buffer@37, 0, 500, 86, 2000, 0)
[3120925.956]  -> wl_surface@32.attach(wl_buffer@37, 0, 0)
[3120925.961]  -> wl_surface@32.set_buffer_scale(1)
[3120925.963]  -> wl_surface@32.damage(0, 0, 500, 86)
[3120925.965]  -> wl_compositor@4.create_region(new id wl_region@38)
[3120925.967]  -> wl_region@38.add(0, 0, 500, 86)
[3120925.968]  -> wl_surface@32.set_opaque_region(wl_region@38)
```

**Comment by phuhl** [comment]
Everything seems to be green, including the window and it's corners. Not sure what that means...

**Comment by phuhl** [comment]
![image](https://github.com/YaLTeR/niri/assets/16835755/0aa0e8a6-2a6e-4c98-94e4-bc28649eab49)

**Comment by YaLTeR** [comment]
That's toggle-debug-tint; could you try debug-toggle-opaque-regions instead?

**Comment by phuhl** [comment]
Sorry, didn't read properly. Tried that, yes, the corners are indeed blue. Seems to be a client bug then. Thanks anyways!
