### ISSUE TITLE
attempt to subtract with overflow

### ISSUE THREAD

**Issue by nougatbyte** [YaLTeR/niri#268]
After I applied the patch mentioned in https://github.com/YaLTeR/niri/issues/151#issuecomment-1925796094 I got a new error:
[error.log](https://github.com/YaLTeR/niri/files/14782183/error.log)

I solved it (thx AI ^^) by making sure the division never went below 0 but I dont really know about the language so I'm not sure thats the best way to handle it:

`ensure!(gamma_length != 0, "gamma_length cannot be zero");`

This in conjunction with the patch makes niri finally run on my pi4 :+1: 

### System Information

* niri version: 0.1.3-94-gf5c97fa-modified 

* GPU: Broadcom VideoCore VI

* CPU:  Broadcom Quad-Core Cortex-A72 (ARM v8)

**Comment by YaLTeR** [comment]
Thanks for the report! I added the same check in a7b38192142440c59a4e793cf5de99b9a7f1c2c3 now.
