### ISSUE TITLE
Some configuration keywords are not recognized

### ISSUE THREAD

**Issue by FranMUex** [YaLTeR/niri#271]
Using some options like "focus-follows-mouse" or any of the "WheelScroll" keybinds results in niri validate not recognizing them even though they correctly written and included inside their respective config sections

Here are the respective outputs:

Error: error loading config
    Diagnostic severity: error
    Caused by: error parsing
    Caused by: error parsing KDL

Error: unexpected node `focus-follows-mouse`
    Diagnostic severity: error

Begin snippet for config.kdl starting at line 53, column 1

snippet line 53:     disable-power-key-handling
snippet line 54:     focus-follows-mouse
    label starting at line 54, column 5: unexpected node
snippet line 55: 
    label ending at line 55, column 0: unexpected node
snippet line 56:     // Uncomment this to make the mouse warp to the center of newly focused windows.

----------------------------------------------------------------------------------------------------------------------------------------------------------------

Error: error loading config
    Diagnostic severity: error
    Caused by: error parsing
    Caused by: error parsing KDL

Error: no properties expected for this node
    Diagnostic severity: error

Begin snippet for config.kdl starting at line 497, column 1

snippet line 497:     // You can set a cooldown on any bind, but it's most useful for the wheel.
snippet line 498:     Mod+WheelScrollDown      cooldown-ms=150 { focus-workspace-down; }
    label at line 498, columns 30 to 40: unexpected property
snippet line 499:     //Mod+WheelScrollUp        cooldown-ms=150 { focus-workspace-up; }
Error: invalid keybind
    Diagnostic severity: error

    Caused by: invalid keybind
    Caused by: invalid key: WheelScrollDown
Begin snippet for config.kdl starting at line 497, column 1

snippet line 497:     // You can set a cooldown on any bind, but it's most useful for the wheel.
snippet line 498:     Mod+WheelScrollDown      cooldown-ms=150 { focus-workspace-down; }
    label at line 498, columns 5 to 23: invalid value
snippet line 499:     //Mod+WheelScrollUp        cooldown-ms=150 { focus-workspace-up; }

### System Information

* niri version:  niri 0.1.3 (acd3365)

* GPU:  Intel TigerLake-LP GT2

* CPU: Intel Core i7 1165G7

**Comment by YaLTeR** [comment]
Hey, you're on 0.1.3 but these were added later. Not to worry though, the 0.1.4 release is tomorrow morning :)
