### ISSUE TITLE
called `Option::unwrap()` on a `None` value when starting Xwayland

### ISSUE THREAD

**Issue by nougatbyte** [YaLTeR/niri#274]
When I start Xwayland on niri it crashes.
It happens when niri was started from a tty and when started from gdm3.

I open a terminal in niri and just type "Xwayland" which results in attached crash.
[error.log](https://github.com/YaLTeR/niri/files/14817691/error.log)

I noticed the log mentions card0 as gpu. It should be card1 for me, but it stays this way even when configured

### System Information

* niri version: 
0.1.4

GPU: Broadcom VideoCore VI

CPU: Broadcom Quad-Core Cortex-A72 (ARM v8)

**Comment by nougatbyte** [comment]
I might add that starting cage from niri also results in an error for me:
[cageerror.txt](https://github.com/YaLTeR/niri/files/14817698/cageerror.txt)

cage version is 0.1.4
xwayland version 2.22.1.9-1 arm64

**Comment by YaLTeR** [comment]
Good catch, seems like there needs to be a check at least for DRM leasing.

> I noticed the log mentions card0 as gpu. It should be card1 for me, but it stays this way even when configured

Hmm, could you post the log that happens when you set `render-drm-device` to `/dev/dri/card1`? Also, could you post `ls /dev/dri/`?

**Comment by YaLTeR** [comment]
Actually, it says `using as the render node: "/dev/dri/card1"` in the log which is what you need?

**Comment by YaLTeR** [comment]
Could you please try 4f56ff16f998b32d70488257bcd91617a61a4147 to see if it fixes the crash?

**Comment by nougatbyte** [comment]
Sorry for the late answer, wanted to retest this - hope you didnt invest too much time.

Your change fixed both variants for me. It now works with and without explicitly set GPU in the config. Thank you!

**Comment by YaLTeR** [comment]
Awesome, thanks!
