### ISSUE TITLE
Xwayland window looses focus every ~5 seconds

### ISSUE THREAD

**Issue by nougatbyte** [YaLTeR/niri#279]
When I start Xwayland in niri as described in the wiki it contiually switches between my (only) terminal window and the Xwayland window.
It behaves as if someone presses Mod+Left, Mod+Right, Sleep 5 and so on.

I'm not really sure which logs to supply since there doesnt seem to be a hard error. Could you specify please?
If further debugging is needed I would be able to create a screencast or allow access to the device for you.

### System Information

* niri version: niri 0.1.4 (v0.1.4-5-g2b3a80b)

* GPU: Broadcom VideoCore VI

* CPU: Broadcom Quad-Core Cortex-A72 (ARM v8)

**Comment by YaLTeR** [comment]
What I've noticed is that Xwayland recreates its window every time a client disappears and appears. This sounds like what you describe. You can fix it by starting some X11 WM inside, or some other window that's always present.
