### ISSUE TITLE
Suggestion: Make it configurable by config file.

### ISSUE THREAD

**Issue by xrtxn** [YaLTeR/niri#3]
This feature is an essential part of all compositors imo. It shouldn't be hardcoded into the program.
It may include: 

- [ ]  keyboard options (ex. layout)
- [ ] custom keybinds
- [ ] compositor general settings

**Comment by YaLTeR** [comment]
Yeah, I was planning on doing this, just didn't get around to it yet.

**Comment by YaLTeR** [comment]
I implemented a configuration file and unhardcoded keyboard options and binds. https://github.com/YaLTeR/niri#configuration
