### ISSUE TITLE
Add xdg_activation support

### ISSUE THREAD

**Issue by kchibisov** [YaLTeR/niri#30]
This is quite useful protocol to indicate urgency, transfer focus, and raise windows.

Unfortunately, it's not clear how to implement it in a usable way with the scrolling compositor...

**Comment by YaLTeR** [comment]
> urgency

https://wayland.app/protocols/xdg-activation-v1 doesn't seem to have urgency? Just window activation.

> Unfortunately, it's not clear how to implement it in a usable way with the scrolling compositor...

I guess simply switching to the right workspace and focusing the right window?

**Comment by kchibisov** [comment]
You can implement urgency based on how and when window submits token, and how token is being built. You can see what sway does for example. It's all based on heuristics, so it's up to compositor to decide what mark as urgent, when to transfer focus, etc.
