### ISSUE TITLE
Border gradients don't work on some NVIDIA GPUs

### ISSUE THREAD

**Issue by Damnjelly** [YaLTeR/niri#302]
Border gradients don't work properly. It seems that it does create a gradient but instead of create a linear gradient, it has a direct transition between the 2 colors. Below an example of what i mean.
![image](https://github.com/YaLTeR/niri/assets/13944407/17f95846-7946-4079-be33-832fed409a34)

Layout part of my config file: 
```
layout {
    gaps 18
    struts {
        left 32
        right 32
        top 0
        bottom 0
    }
    focus-ring { off; }
    border {
        width 2
        active-gradient angle=45 from="#ce1270" relative-to="window" to="#dba3e6"
        inactive-color "#6d546d"
    }
    preset-column-widths
    default-column-width { proportion 0.500000; }
    center-focused-column "never"
}
```

### System Information

(using NixOS with the niri flake)

* niri version: niri unstable 2024-04-21 (commit 49f5402669012be33f8cd111311c3e39fd4751c0)

* GPU: NVIDIA GeForce RTX 3070

* CPU: Ryzen 5 5600X

**Comment by YaLTeR** [comment]
Uhh huh, that's weird. Haven't seen that one before. Wonder if it could be Nvidia related

**Comment by YaLTeR** [comment]
Seems to work for me:

![image](https://github.com/YaLTeR/niri/assets/1794388/3473b809-e454-49c6-ba41-d2f07540498b)

Not sure what could be the cause. Do other `angle`s look the same?

**Comment by JorenBergsma** [comment]
Yes they do, except that the angle of the harsh transition is different. On some angles, e.g. the default 180 degrees, you can't see the second color at all

**Comment by xvrqt** [comment]
I am also experiencing this issue (just switched to Niri today - so I'll let you know if I figure something out as I mess around)

**Comment by Quinntyx** [comment]
I also have this issue. 

layout config:
```kdl
layout {
    gaps 32
    center-focused-column "on-overflow"
    preset-column-widths {
        proportion 0.33333
        proportion 0.5
        proportion 0.66667
    }
    focus-ring {
        width 4
        inactive-color "#505050"
        active-gradient from="#80c8ff" to="#000000" angle=45
    }
}
```

# System Information
(using endeavourOS Arch with niri-git from the AUR)
- niri version: niri v0.1.7-46-ge98d1ec
- GPU: NVIDIA RTX 3060 Lite Hash Rate
- CPU: Ryzen 9 5900X

**Comment by deadbody13** [comment]
Tagging this to say I have the same issue. There isn't really a gradient, more like an abrupt change from one color to the next.

Niri Version: main branch
GPU: RTX 3060 Ti
CPU: i5-13600k

**Comment by xvrqt** [comment]
Adding my info here, I'm seeing the above behavior on two machines:

Nyaa
-----------
GPU: Nvidia GeForce RTX 4090
CPU: 13th Gen Intel i9-13900K (32) @ 5.500Ghz
Niri: 0.1.7 (stable)

Spark
------------
GPU: Integrated
CPU:  Apple M1 Pro (Apple Icestorm-M1-Pro (2) @ 2.06 Ghz + Apple Firestorm-M1-Pro (6) @ 3.23 Ghz)
Niri: 0.1.7 (stable)
