### ISSUE TITLE
Window size when restoring Firefox session

### ISSUE THREAD

**Issue by ce-dr** [YaLTeR/niri#303]
Restoring a previous Firefox session will initially also restore the previous window size. But as soon as you focus on something else it will revert back to the size it opened with. This only happens the first time you change focus. Afterwards it works fine.

I also tried it with chromium (flatpak) and couldn't reproduce it there

### Steps to reproduce
- Open a website with Firefox
- Change window size with `maximize-column`
- Close Firefox
- Open Firefox again => opens with 50% width by default
- Restore previous session => size changes automatically to the 100% width of the previous session
- Change focus to a different window => Firefox goes back to the initial 50% 

### System Information

* niri version: niri 0.1.5 (unknown commit)

* GPU: Intel WhiskeyLake-U GT2 [UHD Graphics 620]

* CPU: Intel i7-8565U

**Comment by YaLTeR** [comment]
This is expected and is more of a Firefox issue. Niri always asks the window to assume the right size, including at the initial configure, before the window is first created. Firefox seems to ignore the first few size requests from niri, and creates a smaller window. Then, when niri needs to change something else about the window (like whether it's activated), Firefox finally decides to comply with the size.

**Comment by ce-dr** [comment]
ah alright, thanks! I'll close the ticket in that case, sorry for the false alert.
