### ISSUE TITLE
Suppord on-demand layer-shell keyboard mode

### ISSUE THREAD

**Issue by Olekoop** [YaLTeR/niri#308]
I am trying to use xfce4-panel 4.19.3 as a bar and I am having issues with applications not responding to keyboard inputs.
Key bindings in niri work just fine and mouse input works on both niri and programs (chromium at least).
When trying to diagnose the problem I ran a bash loop to check current focused window and discovered that when xfce4-panel is running "niri msg focused-window" returns no window.
However the border around the program is shown and it can move between windows.
It only happens when the bar is on the same monitor as the programs.
On my second monitor (where bar is not present) the programs respond to keyboard inputs. The windows focus normally.
When the bar is added to that monitor, the issue occurs. When the bar is removed, the problem disappears.
This issue doesn't happen on sway. Applications respond normally.
### System Information

* niri version: niri 0.1.5 (9f692d1)

* GPU: AMD RX 5700XT

* CPU: AMD Ryzen 5 3600

**Comment by YaLTeR** [comment]
Hey, looks like it's [using](https://gitlab.xfce.org/xfce/xfce4-panel/-/blob/e77763bb89a8d6ebdbc39cce18096f6ed4730c49/panel/panel-window.c#L648) on-demand layer-shell keyboard interactivity, which niri doesn't deal with yet.

**Comment by YaLTeR** [comment]
Pushed a workaround that avoids giving keyboard focus to on-demand layer surfaces, should fix this until proper support.

**Comment by YaLTeR** [comment]
Pushed full support for on-demand layer surfaces, please give it a try.
