### ISSUE TITLE
Crash is randomly triggered by keyboard or mouse click events after a period of startup.

### ISSUE THREAD

**Issue by songww** [YaLTeR/niri#316]
Crash is randomly triggered by keyboard or mouse click events after a period of startup.

Virtual keyboard not enabled.

### System Information

* niri version: niri 0.1.5 (v0.1.5-modified)

* GPU: AMD RX 6600

* CPU: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz 

crash logs: 

> 
> 4月 28 16:45:01 alienware niri[64464]: thread 'main' panicked at /home/songww/.cargo/git/checkouts/smithay-b5a338d5236320f6/c5e9a69/src/wayland/virtual_keyboard/virtual_keyboard_handle.rs:63:9:
> 4月 28 16:45:01 alienware niri[64464]: attempt to add with overflow
> 4月 28 16:45:01 alienware niri[64464]: stack backtrace:
> 4月 28 16:45:01 alienware niri[64464]:    0: rust_begin_unwind
> 4月 28 16:45:01 alienware niri[64464]:              at /rustc/fb898629a26e4acec59c928ce3ec00a62675d1cc/library/std/src/panicking.rs:652:5
> 4月 28 16:45:01 alienware niri[64464]:    1: core::panicking::panic_fmt
> 4月 28 16:45:01 alienware niri[64464]:              at /rustc/fb898629a26e4acec59c928ce3ec00a62675d1cc/library/core/src/panicking.rs:72:14
> 4月 28 16:45:01 alienware niri[64464]:    2: core::panicking::panic_const::panic_const_add_overflow
> 4月 28 16:45:01 alienware niri[64464]:              at /rustc/fb898629a26e4acec59c928ce3ec00a62675d1cc/library/core/src/panicking.rs:175:21
> 4月 28 16:45:01 alienware niri[64464]:    3: count_instance
> 4月 28 16:45:01 alienware niri[64464]:              at ./.cargo/git/checkouts/smithay-b5a338d5236320f6/c5e9a69/src/wayland/virtual_keyboard/virtual_keyboard_handle.rs:63:9
> 4月 28 16:45:01 alienware niri[64464]:    4: request<niri::niri::State>
> 4月 28 16:45:01 alienware niri[64464]:              at ./.cargo/git/checkouts/smithay-b5a338d5236320f6/c5e9a69/src/wayland/virtual_keyboard/mod.rs:162:17
> 4月 28 16:45:01 alienware niri[64464]:    5: request
> 4月 28 16:45:01 alienware niri[64464]:              at ./.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/wayland-server-0.31.1/src/dispatch.rs:363:17
> 4月 28 16:45:01 alienware niri[64464]:    6: request<wayland_protocols_misc::zwp_virtual_keyboard_v1::generated::server::zwp_virtual_keyboard_manager_v1::ZwpVirtualKeyboardManagerV1, (), niri::niri::State>
> 4月 28 16:45:01 alienware niri[64464]:              at ./.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/wayland-server-0.31.1/src/dispatch.rs:264:9
> 4月 28 16:45:01 alienware niri[64464]:    7: {closure#0}<niri::niri::State>
> 4月 28 16:45:01 alienware niri[64464]:              at ./.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/wayland-backend-0.3.3/src/sys/server_impl/mod.rs:1557:9
> 4月 28 16:45:01 alienware niri[64464]:    8: with<(alloc::sync::Arc<std::sync::mutex::Mutex<(dyn wayland_backend::sys::server_impl::ErasedState + core::marker::Send)>, alloc::alloc::Global>, *mut core::ffi::c_void), wayland_backend::sys::server_impl::resource_dispatcher::{closure_env#0}<niri::niri::State>, core::option::Option<alloc::sync::Arc<dyn wayland_backend::sys::server::ObjectData<niri::niri::State>, alloc::alloc::Global>>>
> 4月 28 16:45:01 alienware niri[64464]:              at ./.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/scoped-tls-1.0.1/src/lib.rs:171:13
> 4月 28 16:45:01 alienware niri[64464]:    9: resource_dispatcher<niri::niri::State>
> 4月 28 16:45:01 alienware niri[64464]:              at ./.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/wayland-backend-0.3.3/src/sys/server_impl/mod.rs:1554:15
> 4月 28 16:45:01 alienware niri[64464]:   10: <unknown>
> 4月 28 16:45:01 alienware niri[64464]:   11: <unknown>
> 4月 28 16:45:01 alienware niri[64464]:   12: wl_event_loop_dispatch
> 4月 28 16:45:01 alienware niri[64464]:   13: {closure#0}<niri::niri::State>
> 4月 28 16:45:01 alienware niri[64464]:              at ./.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/wayland-backend-0.3.3/src/sys/server_impl/mod.rs:410:13
> 4月 28 16:45:01 alienware niri[64464]:   14: set<(alloc::sync::Arc<std::sync::mutex::Mutex<(dyn wayland_backend::sys::server_impl::ErasedState + core::marker::Send)>, alloc::alloc::Global>, *mut core::ffi::c_void), wayland_backend::sys::server_impl::{impl#21}::dispatch_all_clients::{closure_env#0}<niri::niri::State>, i32>
> 4月 28 16:45:01 alienware niri[64464]:              at ./.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/scoped-tls-1.0.1/src/lib.rs:137:9
> 4月 28 16:45:01 alienware niri[64464]:   15: dispatch_all_clients<niri::niri::State>
> 4月 28 16:45:01 alienware niri[64464]:              at ./.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/wayland-backend-0.3.3/src/sys/server_impl/mod.rs:407:19
> 4月 28 16:45:01 alienware niri[64464]:   16: dispatch_all_clients<niri::niri::State>
> 4月 28 16:45:01 alienware niri[64464]:              at ./.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/wayland-backend-0.3.3/src/sys/../server_api.rs:575:9
> 4月 28 16:45:01 alienware niri[64464]:   17: dispatch_clients<niri::niri::State>
> 4月 28 16:45:01 alienware niri[64464]:              at ./.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/wayland-server-0.31.1/src/display.rs:59:22
> 4月 28 16:45:01 alienware niri[64464]:   18: {closure#14}
> 4月 28 16:45:01 alienware niri[64464]:              at ./workspace/github.com/niri/src/niri.rs:1303:39
> 4月 28 16:45:01 alienware niri[64464]:   19: {closure#0}<niri::niri::State, calloop::sources::generic::Generic<wayland_server::display::Display<niri::niri::State>, std::io::error::Error>,niri::niri::{impl#4}::new::{closure_env#14}>
> 4月 28 16:45:01 alienware niri[64464]:              at ./.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/calloop-0.13.0/src/sources/mod.rs:327:61
> 4月 28 16:45:01 alienware niri[64464]:   20: process_events<wayland_server::display::Display<niri::niri::State>, std::io::error::Error, calloop::sources::{impl#4}::process_events::{closure_env#0}<niri::niri::State, calloop::sources::generic::Generic<wayland_server::display::Display<niri::niri::State>, std::io::error::Error>, niri::niri::{impl#4}::new::{closure_env#14}>>
> 4月 28 16:45:01 alienware niri[64464]:              at ./.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/calloop-0.13.0/src/sources/generic.rs:290:9
> 4月 28 16:45:01 alienware niri[64464]:   21: process_events<niri::niri::State, calloop::sources::generic::Generic<wayland_server::display::Display<niri::niri::State>, std::io::error::Error>, niri::niri::{impl#4}::new::{closure_env#14}>
> 4月 28 16:45:01 alienware niri[64464]:              at ./.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/calloop-0.13.0/src/sources/mod.rs:326:9
> 4月 28 16:45:01 alienware niri[64464]:   22: dispatch_events<niri::niri::State>
> 4月 28 16:45:01 alienware niri[64464]:              at ./.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/calloop-0.13.0/src/loop_logic.rs:445:31
> 4月 28 16:45:01 alienware niri[64464]:   23: dispatch<niri::niri::State, core::option::Option<core::time::Duration>>
> 4月 28 16:45:01 alienware niri[64464]:              at ./.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/calloop-0.13.0/src/loop_logic.rs:559:9
> 4月 28 16:45:01 alienware niri[64464]:   24: run<niri::niri::State, niri::main::{closure_env#4}, core::option::Option<core::time::Duration>>
> 4月 28 16:45:01 alienware niri[64464]:              at ./.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/calloop-0.13.0/src/loop_logic.rs:596:13
> 4月 28 16:45:01 alienware niri[64464]:   25: main
> 4月 28 16:45:01 alienware niri[64464]:              at ./workspace/github.com/niri/src/main.rs:252:5
> 4月 28 16:45:01 alienware niri[64464]:   26: call_once<fn() -> core::result::Result<(), alloc::boxed::Box<dyn core::error::Error, alloc::alloc::Global>>, ()>
> 4月 28 16:45:01 alienware niri[64464]:              at /rustc/fb898629a26e4acec59c928ce3ec00a62675d1cc/library/core/src/ops/function.rs:250:5
> 4月 28 16:45:01 alienware niri[64464]: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
> 4月 28 16:45:02 alienware niri[64464]: 2024-04-28T08:45:02.177320Z DEBUG niri::utils::watcher: exiting watcher thread for /home/songww/.config/niri/config.kdl
> 4月 28 16:45:02 alienware systemd[1075]: niri.service: Main process exited, code=exited, status=101/n/a
> ░░ Subject: Unit process exited
> ░░ Defined-By: systemd
> ░░ Support: https://www.debian.org/support
> ░░
> ░░ An ExecStart= process belonging to unit UNIT has exited.
> ░░
> ░░ The process' exit code is 'exited' and its exit status is 101.
> 4月 28 16:45:02 alienware systemd[1075]: niri.service: Failed with result 'exit-code'.
> ░░ Subject: Unit failed
> ░░ Defined-By: systemd
> ░░ Support: https://www.debian.org/support
> ░░
> ░░ The unit UNIT has entered the 'failed' state with result 'exit-code'.
> 4月 28 16:45:02 alienware systemd[1075]: niri.service: Consumed 3min 30.761s CPU time.
> ░░ Subject: Resources consumed by unit runtime
> ░░ Defined-By: systemd
> ░░ Support: https://www.debian.org/support
> ░░
> ░░ The unit UNIT completed and consumed the indicated resources.
> 4月 28 16:45:08 alienware systemd[1075]: Starting niri.service - A scrollable-tiling Wayland compositor...
> ░░ Subject: UNIT 单元已开始启动
> ░░ Defined-By: systemd
> ░░ Support: https://www.debian.org/support
> ░░
> ░░ UNIT 单元已开始启动。
> 4月 28 16:45:08 alienware niri[88116]: 2024-04-28T08:45:08.701621Z  INFO niri: starting version 0.1.5 (v0.1.5-modified)
> 4月 28 16:45:08 alienware niri[88116]: 2024-04-28T08:45:08.726647Z DEBUG niri_config: loaded config from "/home/songww/.config/niri/config.kdl"
> 4月 28 16:45:09 alienware niri[88116]: 2024-04-28T08:45:09.662345Z  INFO niri::backend::tty: using as the render node: "/dev/dri/renderD129"
> 4月 28 16:45:09 alienware niri[88116]: 2024-04-28T08:45:09.691269Z DEBUG niri::backend::tty: device added: 57856 "/dev/dri/card0"
> 4月 28 16:45:09 alienware niri[88116]: 2024-04-28T08:45:09.725139Z DEBUG niri::backend::tty: device changed: 57856
> 4月 28 16:45:09 alienware niri[88116]: 2024-04-28T08:45:09.732392Z DEBUG niri::backend::tty: device added: 57857 "/dev/dri/card1"
> 4月 28 16:45:10 alienware niri[88116]: 2024-04-28T08:45:10.055331Z DEBUG niri::backend::tty: this is the primary node
> 4月 28 16:45:10 alienware niri[88116]: 2024-04-28T08:45:10.069576Z DEBUG niri::backend::tty: device changed: 57857
> 4月 28 16:45:10 alienware niri[88116]: 2024-04-28T08:45:10.076939Z DEBUG niri::backend::tty: connecting connector: DP-3
> 4月 28 16:45:10 alienware niri[88116]: 2024-04-28T08:45:10.076965Z  WARN niri::backend::tty: configured mode 3840x2160@60 could not be found, falling back to preferred
> 4月 28 16:45:10 alienware niri[88116]: 2024-04-28T08:45:10.076968Z DEBUG niri::backend::tty: picking mode: Mode { name: "3840x2160", clock: 533250, size: (3840, 2160), hsync: (3902, 3950,4000), vsync: (2163, 2168, 2222), hskew: 0, vscan: 0, vrefresh: 60, mode_type: ModeTypeFlags(PREFERRED | DRIVER) }
> 4月 28 16:45:10 alienware niri[88116]: 2024-04-28T08:45:10.077004Z DEBUG niri::backend::tty: set max bpc to 8
> 4月 28 16:45:10 alienware niri[88116]: 2024-04-28T08:45:10.079737Z DEBUG niri::niri: putting output DP-3 at x=0 y=0
> 4月 28 16:45:10 alienware niri[88116]: 2024-04-28T08:45:10.079748Z DEBUG niri::backend::tty: connecting connector: DP-4
> 4月 28 16:45:10 alienware niri[88116]: 2024-04-28T08:45:10.079769Z  WARN niri::backend::tty: configured mode 3840x2160@60 could not be found, falling back to preferred
> 4月 28 16:45:10 alienware niri[88116]: 2024-04-28T08:45:10.079773Z DEBUG niri::backend::tty: picking mode: Mode { name: "3840x2160", clock: 533250, size: (3840, 2160), hsync: (3902, 3950,4000), vsync: (2163, 2168, 2222), hskew: 0, vscan: 0, vrefresh: 60, mode_type: ModeTypeFlags(PREFERRED | DRIVER) }
> 4月 28 16:45:10 alienware niri[88116]: 2024-04-28T08:45:10.079809Z DEBUG niri::backend::tty: set max bpc to 8
> 4月 28 16:45:10 alienware niri[88116]: 2024-04-28T08:45:10.081126Z DEBUG niri::niri: putting output DP-4 at x=1920 y=0
> 4月 28 16:45:10 alienware niri[88116]: 2024-04-28T08:45:10.081231Z DEBUG niri::backend::tty: device added: 57858 "/dev/dri/card2"
> 4月 28 16:45:10 alienware niri[88116]: 2024-04-28T08:45:10.086919Z DEBUG niri::backend::tty: device changed: 57858
> 4月 28 16:45:10 alienware niri[88116]: 2024-04-28T08:45:10.087733Z  INFO niri: listening on Wayland socket: wayland-1
> 4月 28 16:45:10 alienware niri[88116]: 2024-04-28T08:45:10.087739Z  INFO niri: IPC listening on: /run/user/1000/niri.wayland-1.88116.sock
> 4月 28 16:45:10 alienware systemd[1075]: niri.service: Got notification message from PID 88191, but reception only permitted for main PID 88116
> 4月 28 16:45:10 alienware systemd[1075]: Started niri.service - A scrollable-tiling Wayland compositor.
> ░░ Subject: UNIT 单元已结束启动
> ░░ Defined-By: systemd
> ░░ Support: https://www.debian.org/support
> ░░
> ░░ UNIT 单元已结束启动。
> ░░
> ░░ 启动结果为“done”。
> 4月 28 17:23:38 alienware niri[88116]: thread 'main' panicked at /home/songww/.cargo/git/checkouts/smithay-b5a338d5236320f6/c5e9a69/src/wayland/virtual_keyboard/virtual_keyboard_handle.rs:63:9:
> 4月 28 17:23:38 alienware niri[88116]: attempt to add with overflow
> 4月 28 17:23:38 alienware niri[88116]: stack backtrace:
> 4月 28 17:23:38 alienware niri[88116]:    0: rust_begin_unwind
> 4月 28 17:23:38 alienware niri[88116]:              at /rustc/fb898629a26e4acec59c928ce3ec00a62675d1cc/library/std/src/panicking.rs:652:5
> 4月 28 17:23:38 alienware niri[88116]:    1: core::panicking::panic_fmt
> 4月 28 17:23:38 alienware niri[88116]:              at /rustc/fb898629a26e4acec59c928ce3ec00a62675d1cc/library/core/src/panicking.rs:72:14
> 4月 28 17:23:38 alienware niri[88116]:    2: core::panicking::panic_const::panic_const_add_overflow
> 4月 28 17:23:38 alienware niri[88116]:              at /rustc/fb898629a26e4acec59c928ce3ec00a62675d1cc/library/core/src/panicking.rs:175:21
> 4月 28 17:23:38 alienware niri[88116]:    3: count_instance
> 4月 28 17:23:38 alienware niri[88116]:              at ./.cargo/git/checkouts/smithay-b5a338d5236320f6/c5e9a69/src/wayland/virtual_keyboard/virtual_keyboard_handle.rs:63:9
> 4月 28 17:23:38 alienware niri[88116]:    4: request<niri::niri::State>
> 4月 28 17:23:38 alienware niri[88116]:              at ./.cargo/git/checkouts/smithay-b5a338d5236320f6/c5e9a69/src/wayland/virtual_keyboard/mod.rs:162:17
> 4月 28 17:23:38 alienware niri[88116]:    5: request
> 4月 28 17:23:38 alienware niri[88116]:              at ./.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/wayland-server-0.31.1/src/dispatch.rs:363:17
> 4月 28 17:23:38 alienware niri[88116]:    6: request<wayland_protocols_misc::zwp_virtual_keyboard_v1::generated::server::zwp_virtual_keyboard_manager_v1::ZwpVirtualKeyboardManagerV1, (), niri::niri::State>
> 4月 28 17:23:38 alienware niri[88116]:              at ./.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/wayland-server-0.31.1/src/dispatch.rs:264:9
> 4月 28 17:23:38 alienware niri[88116]:    7: {closure#0}<niri::niri::State>
> 4月 28 17:23:38 alienware niri[88116]:              at ./.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/wayland-backend-0.3.3/src/sys/server_impl/mod.rs:1557:9
> 4月 28 17:23:38 alienware niri[88116]:    8: with<(alloc::sync::Arc<std::sync::mutex::Mutex<(dyn wayland_backend::sys::server_impl::ErasedState + core::marker::Send)>, alloc::alloc::Global>, *mut core::ffi::c_void), wayland_backend::sys::server_impl::resource_dispatcher::{closure_env#0}<niri::niri::State>, core::option::Option<alloc::sync::Arc<dyn wayland_backend::sys::server::ObjectData<niri::niri::State>, alloc::alloc::Global>>>
> 4月 28 17:23:38 alienware niri[88116]:              at ./.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/scoped-tls-1.0.1/src/lib.rs:171:13
> 4月 28 17:23:38 alienware niri[88116]:    9: resource_dispatcher<niri::niri::State>
> 4月 28 17:23:38 alienware niri[88116]:              at ./.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/wayland-backend-0.3.3/src/sys/server_impl/mod.rs:1554:15
> 4月 28 17:23:38 alienware niri[88116]:   10: <unknown>
> 4月 28 17:23:38 alienware niri[88116]:   11: <unknown>
> 4月 28 17:23:38 alienware niri[88116]:   12: wl_event_loop_dispatch
> 4月 28 17:23:38 alienware niri[88116]:   13: {closure#0}<niri::niri::State>
> 4月 28 17:23:38 alienware niri[88116]:              at ./.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/wayland-backend-0.3.3/src/sys/server_impl/mod.rs:410:13
> 4月 28 17:23:38 alienware niri[88116]:   14: set<(alloc::sync::Arc<std::sync::mutex::Mutex<(dyn wayland_backend::sys::server_impl::ErasedState + core::marker::Send)>, alloc::alloc::Global>, *mut core::ffi::c_void), wayland_backend::sys::server_impl::{impl#21}::dispatch_all_clients::{closure_env#0}<niri::niri::State>, i32>
> 4月 28 17:23:38 alienware niri[88116]:              at ./.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/scoped-tls-1.0.1/src/lib.rs:137:9
> 4月 28 17:23:38 alienware niri[88116]:   15: dispatch_all_clients<niri::niri::State>
> 4月 28 17:23:38 alienware niri[88116]:              at ./.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/wayland-backend-0.3.3/src/sys/server_impl/mod.rs:407:19
> 4月 28 17:23:38 alienware niri[88116]:   16: dispatch_all_clients<niri::niri::State>
> 4月 28 17:23:38 alienware niri[88116]:              at ./.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/wayland-backend-0.3.3/src/sys/../server_api.rs:575:9
> 4月 28 17:23:38 alienware niri[88116]:   17: dispatch_clients<niri::niri::State>
> 4月 28 17:23:38 alienware niri[88116]:              at ./.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/wayland-server-0.31.1/src/display.rs:59:22
> 4月 28 17:23:38 alienware niri[88116]:   18: {closure#14}
> 4月 28 17:23:38 alienware niri[88116]:              at ./workspace/github.com/niri/src/niri.rs:1303:39
> 4月 28 17:23:38 alienware niri[88116]:   19: {closure#0}<niri::niri::State, calloop::sources::generic::Generic<wayland_server::display::Display<niri::niri::State>, std::io::error::Error>,niri::niri::{impl#4}::new::{closure_env#14}>
> 4月 28 17:23:38 alienware niri[88116]:              at ./.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/calloop-0.13.0/src/sources/mod.rs:327:61
> 4月 28 17:23:38 alienware niri[88116]:   20: process_events<wayland_server::display::Display<niri::niri::State>, std::io::error::Error, calloop::sources::{impl#4}::process_events::{closure_env#0}<niri::niri::State, calloop::sources::generic::Generic<wayland_server::display::Display<niri::niri::State>, std::io::error::Error>, niri::niri::{impl#4}::new::{closure_env#14}>>
> 4月 28 17:23:38 alienware niri[88116]:              at ./.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/calloop-0.13.0/src/sources/generic.rs:290:9
> 4月 28 17:23:38 alienware niri[88116]:   21: process_events<niri::niri::State, calloop::sources::generic::Generic<wayland_server::display::Display<niri::niri::State>, std::io::error::Error>, niri::niri::{impl#4}::new::{closure_env#14}>
> 4月 28 17:23:38 alienware niri[88116]:              at ./.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/calloop-0.13.0/src/sources/mod.rs:326:9
> 4月 28 17:23:38 alienware niri[88116]:   22: dispatch_events<niri::niri::State>
> 4月 28 17:23:38 alienware niri[88116]:              at ./.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/calloop-0.13.0/src/loop_logic.rs:445:31
> 4月 28 17:23:38 alienware niri[88116]:   23: dispatch<niri::niri::State, core::option::Option<core::time::Duration>>
> 4月 28 17:23:38 alienware niri[88116]:              at ./.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/calloop-0.13.0/src/loop_logic.rs:559:9
> 4月 28 17:23:38 alienware niri[88116]:   24: run<niri::niri::State, niri::main::{closure_env#4}, core::option::Option<core::time::Duration>>
> 4月 28 17:23:38 alienware niri[88116]:              at ./.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/calloop-0.13.0/src/loop_logic.rs:596:13
> 4月 28 17:23:38 alienware niri[88116]:   25: main
> 4月 28 17:23:38 alienware niri[88116]:              at ./workspace/github.com/niri/src/main.rs:252:5
> 4月 28 17:23:38 alienware niri[88116]:   26: call_once<fn() -> core::result::Result<(), alloc::boxed::Box<dyn core::error::Error, alloc::alloc::Global>>, ()>
> 4月 28 17:23:38 alienware niri[88116]:              at /rustc/fb898629a26e4acec59c928ce3ec00a62675d1cc/library/core/src/ops/function.rs:250:5
> 4月 28 17:23:38 alienware niri[88116]: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
> 4月 28 17:23:38 alienware niri[88116]: 2024-04-28T09:23:38.841343Z DEBUG niri::utils::watcher: exiting watcher thread for /home/songww/.config/niri/config.kdl
> 4月 28 17:23:39 alienware systemd[1075]: niri.service: Main process exited, code=exited, status=101/n/a
> ░░ Subject: Unit process exited
> ░░ Defined-By: systemd
> ░░ Support: https://www.debian.org/support
> ░░
> ░░ An ExecStart= process belonging to unit UNIT has exited.
> ░░
> ░░ The process' exit code is 'exited' and its exit status is 101.
> 4月 28 17:23:39 alienware systemd[1075]: niri.service: Failed with result 'exit-code'.
> ░░ Subject: Unit failed
> ░░ Defined-By: systemd
> ░░ Support: https://www.debian.org/support
> ░░
> ░░ The unit UNIT has entered the 'failed' state with result 'exit-code'.
> 4月 28 17:23:39 alienware systemd[1075]: niri.service: Consumed 3min 56.849s CPU time.
> ░░ Subject: Resources consumed by unit runtime
> ░░ Defined-By: systemd
> ░░ Support: https://www.debian.org/support
> ░░
> ░░ The unit UNIT completed and consumed the indicated resources.

**Comment by YaLTeR** [comment]
Thanks for the report. Seems to be a Smithay issue, I'll take a look.

**Comment by songww** [comment]
On my machine, after a certain number of toggling the focus window crashes, either by mouse clicks or keyboard shortcuts.

**Comment by YaLTeR** [comment]
Should hopefully be fixed in c0d5001e906198ad67b4edfdbcc216db256c5402.
