### ISSUE TITLE
waybar not shown

### ISSUE THREAD

**Issue by bobblkabb** [YaLTeR/niri#326]
Waybar doesn't appear. debug log:
```
[2024-05-02 21:11:58.592] [debug] Try expanding: $XDG_CONFIG_HOME/waybar/config
[2024-05-02 21:11:58.592] [debug] Try expanding: $XDG_CONFIG_HOME/waybar/config.jsonc
[2024-05-02 21:11:58.592] [debug] Try expanding: $HOME/.config/waybar/config
[2024-05-02 21:11:58.592] [debug] Found config file: $HOME/.config/waybar/config
[2024-05-02 21:11:58.592] [info] Using configuration file /home/mypc/.config/waybar/config
[2024-05-02 21:12:23.619] [error] Error calling StartServiceByName for org.freedesktop.portal.Desktop: Timeout was reached
```
Same when starting with /etc/xdg/waybar/config.jsonc
This is my own config: [waybar-config.txt](https://github.com/YaLTeR/niri/files/15192974/waybar-config.txt)

### System Information

* niri version:  0.15

* Distro: openSUSE Tumbleweed

* GPU: Intel HD Graphics 530 @ 1,10 GHz

* CPU: Intel(R) Core(TM) i5-6500T (4) @ 3,10 GHz

**Comment by bobblkabb** [comment]
Output "HDMI-A-1" (27_8_30 - LG ULTRAWIDE - HDMI-A-1)
```
  Current mode: 3440x1440 @ 49.987 Hz
  Variable refresh rate: not supported
  Physical size: 800x340 mm
  Logical position: 0, 0
  Logical size: 3440x1440
  Scale: 1
  Transform: normal
```
[niri-config.txt](https://github.com/YaLTeR/niri/files/15193029/niri-config.txt)

**Comment by YaLTeR** [comment]
Hey, uhh, maybe it doesn't like the hyprland module or some other module?

**Comment by bobblkabb** [comment]
Commented modules-right and modules-center, so nothing hyprlandy remains. Still

**Comment by YaLTeR** [comment]
Maybe the portals aren't started properly? How are you starting niri?

**Comment by bobblkabb** [comment]
Now as you mention. I use tuigreet/greetd. On my other machine it's started directly via tty.
tuigreet config.toml:
```
[terminal]
vt = 1

[default-session]
command = "tuigreet --cmd niri"
user = "myuser"

```

**Comment by YaLTeR** [comment]
If you use systemd, make it run niri-session. Otherwise make sure a dbus session is started and desktop portals are started

**Comment by bobblkabb** [comment]
I tried:
`command = "tuigreet --cmd dbus-run-session niri"`
without success when starting waybar from shell:
`Couldn't connect to accessibility bus: Failed to connect to socket /run/user/1000/at-spi/bus`

And put this into config.kdl:
```
spawn-at-startup "xdg-desktop-portal"
spawn-at-startup "xdg-desktop-portal-wlr"
spawn-at-startup "xdg-desktop-portal-gnome"
```

How do I make systemd run niri-session?

**Comment by YaLTeR** [comment]
Does `tuigreet --cmd niri-session` maybe work?

**Comment by bobblkabb** [comment]
That's it! Thank you very much for the great support!

**Comment by YaLTeR** [comment]
Nice!
