### ISSUE TITLE
Application launcher does not take `$PATH` into account when spawning.

### ISSUE THREAD

**Issue by LollipopFt** [YaLTeR/niri#328]
I had added `~/bin` to `$PATH` in `.bashrc`. However, when using `Mod+D` to `spawn "bemenu-run"`, the shell scripts in `~/bin` did not appear. When I instead ran `bemenu-run` in terminal, the shell scripts I had added to `$PATH` did appear.

### System Information

* niri version: niri 0.1.5 (6a80078)

* Distro: Linux version 6.8.9-arch1-1 (linux@archlinux)

* GPU: Intel Corporation Iris Plus Graphics G7

* CPU: Intel(R) Core(TM) i7-1065G7

**Comment by YaLTeR** [comment]
niri should use variables set from the shell, including `$PATH`. The script responsible for this is `niri-session` (notice how it tries to run your shell at the top). So you need to make sure that, however you're starting niri, it goes through your shell and runs .bashrc.

**Comment by LollipopFt** [comment]
i found out my problem: i had no `.bash_profile`. thank you for the insight!
