### ISSUE TITLE
Add wlr-screencopy

### ISSUE THREAD

**Issue by kchibisov** [YaLTeR/niri#33]
The implementation with smithay is available in https://github.com/catacombing/catacomb/tree/master/src/protocols/screencopy and could probably be reused. Though it's limited in terms of formats.

**Comment by YaLTeR** [comment]
For new users happening upon this issue: note that niri already has

- built-in screenshots, including with mouse area selection and by window (bound to Print Screen by default)
- PipeWire screencasting through xdg-desktop-portal-gnome which works out of the box with browsers and OBS (you need to run niri as a session, check the README)
- screenshot portal through xdg-desktop-portal-gnome

This already covers a good chunk of wlr-screencopy use cases.

**Comment by sodiboo** [comment]
for my use case, i don't think niri's screenshot capabilities is sufficient.

i'd also like to note that i don't really like how it works, but that's a matter of personal taste and not really a valid issue. i expect mouse selection to be "drag from this corner, release in other corner" to define the bounds. but with niri's current solution, you can still modify it after you release the mouse? and you have to press enter. not what i expect. i don't expect niri to implement a screenshot tool that works exactly how i'd like either, instead it's most logical to use something like `grim` and `slurp`, which i've seen on other wayland compositors

but, my "real" use case for which it is genuinely insufficient, and not just "i don't like it":

I would like to set the background of `swaylock` to be a blurred version of whatever lies beneath. this is, on something like sway, fairly trivial to do. you can do `grim /tmp/screenshot.png`, do some imagemagick junk on the resulting file and `swaylock -i /tmp/screenshot.png`. you can even generalize it to multiple outputs with `grim -o "$output" "$output-screenshot.png"` and `swaylock -i $output:$output-screenshot.png`.

with niri, this is not as easy. the screenshots *can* be somewhat configured to make it easier, but i don't want the same binds that i use to take screenshots for normal screenshotting purposes manually, to be optimized for programmatic use.

most problematic is: i cannot set which monitor the screenshot is taken on. it's just the focused one. i *can* actually abuse the focus monitor commands to rapidly switch between monitors and take screenshots, so there's not actually any *hard* block to my objective. it's possible, just not convenient. but so what? i use one monitor, i don't care.

then, it will save to the clipboard. so i have to store the clipboard first and then restore it. this is fine, whatever. four more lines of script (compared to 0 with something like `grim`)

but, the `niri msg` commands don't seem to actually wait for anything, and there's not a clear way to do this. if i just use `niri msg action screenshot-screen` and then immediately `wl-paste`, i get what the clipboard contained before the screenshot, not the newly taken screenshot. so i must either sleep (something like `sleep 0.1` seems to be consistent and reliable), or i must somehow find out when the screenshot is taken.

niri sends a notification: i use mako, and it's fairly easy to programatically dismiss with `makoctl`. the notification is mostly a nonissue besides the fact that it too cannot be dismissed immediately after.

when i press keys on my keyboard, i generally expect things to happen fast. `sleep` is not an acceptable solution.

what i ultimately do, is use `makoctl list` to list all notifications, and then busy-loop awaiting new screenshots. then, i dismiss these and save the clipboard.

all in all, this is a lot more work for what is a one-liner with `grim`. implementing multiple outputs is possible, with `grim` that's a simple loop, but with niri's current system this requires spamming focus commands.

here's my final "screenshot and save it to a file without bothering the user" script

```sh
wl-paste --no-newline > $dir/clip

{{notifs}} > $dir/existing-notifs
niri msg action screenshot-screen
while
  new_notifs="$({{notifs}} | comm -23 - $dir/existing-notifs | grep -P '^\d+$')"
  [ $? -ne 0 ]
do
  :
done
for i in $(echo "$new_notifs")
do
  makoctl dismiss -n $i
done
wl-paste > $dir/screenshot.png

wl-copy < $dir/clip
rm $dir/clip
```

where `{{notifs}}` is shorthand for a pipeline that prints all notification IDs of "Screenshot captured" posted by niri:
```sh
makoctl list | jq '.data[0][] | select(.["app-name"].data == "niri" and .summary.data == "Screenshot captured") | .id.data' | sort
```

with `wlr-screencopy-unstable-v1`, this would be equivalent to the much shorter and easier  `grim $dir/screenshot.png` (which i also would imagine is likely faster than parsing json however many times, acessing the clipboard thrice, and posting a notification that is immediately and automatically dismissed)

**Comment by YaLTeR** [comment]
I agree, this use case makes much more sense to do through screencopy. (I would suggest a portal, but the screenshot portal is very limited at the moment and almost no tools actually use it from what I found.) I think adding screencopy would make sense, especially now that we have security-context.

> but with niri's current solution, you can still modify it after you release the mouse

If you're curious, the motivation here is twofold:
- frequently you do want to edit the selection when only at the opposite corner do you find out that you were actually a few pixels short initially;
- it makes preserving the selection between screenshots, which is quite useful, have consistent workflow (also need to press Enter to confirm).

> i don't want the same binds that i use to take screenshots for normal screenshotting purposes manually, to be optimized for programmatic use

I agree, adding stuff into binds that's only useful for programmatic use sounds like doing things the wrong way around.

> the niri msg commands don't seem to actually wait for anything

Yeah, that's intentional. They run the same code as the binds, and binds mustn't block the compositor for obvious reasons.

For screenshots in particular the reason is that image compression to PNG takes a few hundred ms, so it needs to run in a separate thread.

**Comment by sodiboo** [comment]
> I agree, this use case makes much more sense to do through screencopy. (I would suggest a portal, but the screenshot portal is very limited at the moment and almost no tools actually use it from what I found.)

When reading this issue, i saw you mention "screenshot portals" in your initial comment. This wasn't something i had heard of, but when searching for tools utilizing it (albeit not very thoroughly), i found nothing significant or useful. Mostly, almost all the results were about configuring the GNOME screenshot tool.

> I think adding screencopy would make sense, especially now that we have security-context.

I didn't really think of security issues regarding screencopy. Personally, i am of the belief that whatever you run on your computer locally is your own fault, so i don't "Believe In Security" in the context of Wayland. I can see how a portal might be beneficial, but ultimately even letting "any program" take screenshots isn't part of my threat model, given that those same programs can already, for example, run anything on my computer, read my entire home directory and nix config, and author git commits in my name. The display buffer is among the *least* sensitive places that my data is stored. I like the video capture portals not for the security, but for the convenience of having a single unified selection of windows that also handles them correctly, for all programs that might want to capture.

> If you're curious, the motivation here is twofold:
> 
> * frequently you do want to edit the selection when only at the opposite corner do you find out that you were actually a few pixels short initially;
>
> * it makes preserving the selection between screenshots, which is quite useful, have consistent workflow (also need to press Enter to confirm).

Oh yeah, absolutely, i totally get why someone might prefer this behaviour, and I'm in no way trying to say it's objectively bad, it's just not *what I intuitively expect* (read: "what I'm used to from Windows"). For reference, my "inuitive" way (read: "what I used to do on Windows") to solve these two problems is firstly based in some functionality of ShareX, which displays coordinates of the cursor, and a magnified circle with borders around the pixels near the cursor. This way, I can visually align the corner of the screenshot. To align the initial corner? Genuinely just take a wrong screenshot (or cancel it or something, ESC during the mouse selection click should cancel it in my "intuitive" screenshot ideal), then begin a new one at this precisely selected corner, and take a new screenshot with the start/end corners flipped, and then align the new "end" cursor in the incorrect corner.

When I feel the need to take two identically-positioned screenshots, it's generally already on a pixel border, and thus it's easy to realign with the same tedious process. This process was thought out without ever using a touchpad to do this, and my mouse is high DPI with the lowest sensitivity allowed in OS, as such I can make pixel perfect selections using it. What I might do on Linux to ease this process, using `grim` and `slurp` (or as i've recently taken to calling it...), could be to just run `slurp` once manually, save the result, and then run `grim` with the exact same geometry passed without bringing up any kind of selection again. With ShareX, in absence of clearly defined pixel borders, i may just remember or note down the exact pixel coordinates that i need to align my cursor at.

> They run the same code as the binds, and binds mustn't block the compositor for obvious reasons.
> 
> For screenshots in particular the reason is that image compression to PNG takes a few hundred ms, so it needs to run in a separate thread.

That makes sense as for how this happened. But shouldn't it be possible to return a handle to join this thread? Or in the case of IPC, i guess that would rather be a "completion" kinda message when the thread finishes. Then, `niri msg` could have some flag `--await` that would actually wait for completion of the task, and by default (including for binds) it would just ignore the action thread's completion state

**Comment by YaLTeR** [comment]
> letting "any program" take screenshots isn't part of my threat model, given that those same programs can already, for example, run anything on my computer, read my entire home directory and nix config, and author git commits in my name

Sure, programs you run on the host can do all those things, and thus security-context is not concerned with them. However, sandboxed or partially sandboxed programs cannot do any of that (i.e. Flatpaks that are made properly), and that's where security-context lets the compositor also filter out the sensitive protocols.

> I like the video capture portals not for the security, but for the convenience of having a single unified selection of windows that also handles them correctly, for all programs that might want to capture.

Right, and ideally the screenshot portal would also offer that kind of convenience for various use-cases, but unfortunately right now it can barely do anything, so nothing really uses it and it's not very developed as a consequence.

> But shouldn't it be possible to return a handle to join this thread? Or in the case of IPC, i guess that would rather be a "completion" kinda message when the thread finishes. Then, niri msg could have some flag --await that would actually wait for completion of the task, and by default (including for binds) it would just ignore the action thread's completion state

Yeah; however I would wait for more real use cases before adding something like this. Since you need to answer questions like, if you're waiting for a screenshot, are you also waiting for the animation to complete for focus-workspace-up? Which of those make sense? Honestly, adding separate specific `niri msg` subcommands for this stuff may be better.

Anyhow this is a bit off-topic for this issue.

**Comment by YaLTeR** [comment]
The PR above implements wlr-screencopy **v1**. This should be sufficient for any screenshot tool; grim works for example, and if other screenshot tools want v3 then they probably just need to bind v1 instead.

Screen recording tools will need v3, but it's more complex to implement correctly, so I've decided to postpone it. Besides, the screencast portal is a better interface anyway, since the compositor handles frame pacing.
