### ISSUE TITLE
Gtklock/hyprlock red screen issue

### ISSUE THREAD

**Issue by sioodmy** [YaLTeR/niri#341]
Every time I try to lock my session using gtklock or hyprlock the entire screen turns red. 

I know it's most likely my misunderstanding, but I haven't found any information about lockers in docs.
Also I Couldn't find anything useful in niri logs.
```
niri: locking session
backend::tty: pausing session
backend::tty: device is inactive
backend::tty: device is inactive
backend::tty: device is inactive
backend::tty: device is inactive
``` 

Just to clarify, I can confirm my current gtklock setup used to work on wayland perfectly fine. same with hyprlock. Maybe it's because of some unimplemented protocol?
### System Information

* niri version: 
niri unstable 2024-05-12 (commit 55e550262dcde29b0e0332e257008029b146a97f)

* Distro: 
NixOS (https://github.com/sioodmy/dotfiles)

thinkpad x1

**Comment by YaLTeR** [comment]
What seems to happen is that niri disconnects the client. Need to look into it; it may be that Smithay posts a protocol error when it shouldn't somewhere.

**Comment by YaLTeR** [comment]
Fixed with a Smithay update.
