### ISSUE TITLE
custom-shader does not follow window geometry

### ISSUE THREAD

**Issue by moilong** [YaLTeR/niri#351]
prefer-no-csd

layout {
    focus-ring {
        off
    }

    border {
        width 2
    }
}

window-rule {
    geometry-corner-radius 12
    clip-to-geometry true
}
with the above config, custom- shader for window-open and window- close does not obey geometry- corner- radious. Shadow appear like square as if there is no corner radious.

**Comment by YaLTeR** [comment]
Window open and close render the entire tile into a texture, then pass this texture to the shaders. So you don't want to add any extra shadow there. All rounded corner stuff is already "baked in". What are you trying to do?

**Comment by moilong** [comment]
Messed up animations section. Now recompiled to v0.1.6. Everything ok.
