### ISSUE TITLE
Some applications won't launch

### ISSUE THREAD

**Issue by amatsagu** [YaLTeR/niri#358]
### System Information

* niri version: niri 0.1.6 (v0.1.6-2-g56e02a3)

* Distro: Debian GNU/Linux 12 (bookworm) x86_64

* GPU: integrated graphics [Vega 7]

* CPU: Ryzen 5 5600G

### Info
Hey, I'm just trying out Niri (I really like scrolling concept). I've successfully completed and copied files to correct places following building guide. I've tried launching few apps that I use and some of them work and some don't:

Apps that work fine:
- Waybar
- Fuzzel
- Foot (tho it has weird bar at the top)
- Spotify (even weirder top bar)
- Google Chrome
- Visual Studio Code
- Bottles
- PulseAudio Volume Control
- HSR custom client
- Files & Disks (from Gnome)

Apps that fails to launch? (never spawn window)
- Oracle VM VirtualBox [xwayland on Sway]
- Termius [electron, native wayland with flags]
- Gimp [xwayland on Sway]
- Boxes [native wayland]
- MultiMC 5 [native wayland] (it's a custom, QT based launcher for easier modding minecraft, didn't try official MC client yet)

I normally use Sway for everyday work and all higher listed apps works just fine there. I assume they just miss something during initialization but idk, I'm not too knowledgeable with Wayland. I hope this report will help finding some bugs.

Edit: No clue if it's helpful but I ended session (Super + Shift + E) and niri produced it seems only normal logs, there were no warnings or errors.

**Comment by songww** [comment]
Gimp works with Xwayland/xwayland-satellite/gamescope on my machine, but not cage. 
Boxes works fine.

I don't have any other apps.

**Comment by lpnh** [comment]
There's a useful [section on the Wiki](https://github.com/YaLTeR/niri/wiki/Xwayland) discussing X11 applications. In addition, you can try the following flags to run Electron-based apps: `--ozone-platform-hint=auto` and `--enable-features=WaylandWindowDecorations`, or `--ozone-platform=wayland` if the previous two don't work.

**Comment by YaLTeR** [comment]
Hey, yeah, it probably mostly comes down to some apps requiring Xwayland. Some apps even don't really need Xwayland, but still call into it at the moment, so you may get away with spawning an Xwayland instance and giving the app both WAYLAND_DISPLAY and DISPLAY.

Also, GIMP beta is Wayland-native so it works fine, and Boxes works fine here too. The official MC client I run inside rootful Xwayland.

Closing because this isn't really a niri issue; feel free to keep discussing (or to ask on our Matrix).
