### ISSUE TITLE
layer-shell crash when no outputs are connected

### ISSUE THREAD

**Issue by hallettj** [YaLTeR/niri#359]
The 0.1.6 release is fantastic as always! I enjoyed adding a workspace indicator to my waybar config with the new message option.

I'm getting a crash sometimes when resuming from suspend. I think this was happening once in a while on 0.1.5 too. The error message is:

```
thread 'main' panicked at src/handlers/layer_shell.rs:31:14:
called `Option::unwrap()` on a `None` value
```

The full log output with stack backtrace is [here](https://gist.github.com/hallettj/62ef4eb92a5dd7ee8f35fd19788549ae)

### System Information

* niri version: niri stable 0.1.6

* Distro: NixOS 23.11 (I'm using sodiboo's [niri-flake](https://github.com/sodiboo/niri-flake))

* GPU: AMD RX 6700 XT

* CPU: AMD Ryzen 7 5800X

**Comment by YaLTeR** [comment]
Mhm, thanks for the report. Looks like it's hitting the undertested case of "no outputs connected". I will look into this.

**Comment by YaLTeR** [comment]
f4cdde1f4f89729f91336ea2f5ad7a1265e3bf70 should fix this I think
