### ISSUE TITLE
Option to always show border around the client

### ISSUE THREAD

**Issue by kchibisov** [YaLTeR/niri#37]

**Comment by kchibisov** [comment]
probably, but then it'll not work with multi-monitor hint.

**Comment by kchibisov** [comment]
I'd simply suggest `border: Option<RGB>`.

**Comment by YaLTeR** [comment]
> it'll not work with multi-monitor hint.

I mean, it's the same idea, so not really an issue.

**Comment by YaLTeR** [comment]
Mhm, won't be as simple as I initially thought, because you have to keep around a `SolidColorBuffer` for the border (creating a new one every frame causes continuous damage). Right now it's one per workspace, would need to become one per window, which would need a larger refactor.

**Comment by YaLTeR** [comment]
Implemented in c21805bf705bd36a6eb7f79039b759e9af79dfcb.
