### ISSUE TITLE
Support wlr-output-management-unstable-v1

### ISSUE THREAD

**Issue by YaLTeR** [YaLTeR/niri#370]
It should apply the output configuration transiently, exactly like `niri msg output`. I'm not sure how exactly testing a configuration should work, but I think cosmic-comp has that, so can reference that.

**Comment by subutux** [comment]
I would love this. I currently have a different monitor setup for work and home and previously solved this by using (Kanshi)[https://sr.ht/~emersion/kanshi/] to create 2 profiles.

**Comment by edrex** [comment]
I like to use use way-displays on other compositors (recommended @subutux), since it supports a) flexible matching for display config and b) resolution independent positioning (position laptop panel below or right of external display independently of external display resolution/scale), so this would be nice.

**Comment by YaLTeR** [comment]
wlr-output-management support has been merged, please give it a good test and report any issues you find.

**Comment by subutux** [comment]
The only thing I needed to edit to my previous kanshi config was:

* **no full display names**: The display names are the physical ports, not the display make and model (Sway does provide the displays with make and model)
  *  ex. `output "Iiyama North America PL3493WQ 1171400300105"` -> `output "DP-3"`
* **the position of the displays must take the scaling into account**: This is done automatically in Sway
  * ex. `position 3456,0`  -> `position 1728,0` when the first display has a scaling of `2`

No show stoppers, but means that I can't use the same config between a Sway and a Niri session.

Should I log new issues for this?

**Comment by YaLTeR** [comment]
No full names => we're waiting for libdisplay-info in Smithay, no issue needed. 

Position scaling => are you sure this is a thing? I'll double check but niri should accept logical pixel position as it should be.

**Comment by subutux** [comment]
Iv'e tried [wdisplays](https://github.com/artizirk/wdisplays) with the position at 1278:
![image](https://github.com/YaLTeR/niri/assets/872941/cf6fa7c9-b9e5-4939-8225-a2264ce0c014)
and 3456:
![image](https://github.com/YaLTeR/niri/assets/872941/98deaff8-8fd7-434b-855d-ac6f5088b5a7)
Resulting in an inaccessable eDP-1 screen.

**Comment by YaLTeR** [comment]
Well, yeah, that's correct behavior. It even matches what you see in wdisplays.
