### ISSUE TITLE
center-focused-column always with f-f-m causes runaway

### ISSUE THREAD

**Issue by gregzuro** [YaLTeR/niri#377]
With center-focused-always,   warp-mouse-to-focus, and  focus-follows-mouse all active, moving the mouse to the right or left of the screen will cause the strip to move all the way to the end or start  of the strip. 

Seems like updating the mouse position after each column shift would fix it?

### System Information

* niri version:  niri unstable 2024-05-21 (commit efb39e466b5248eb894745e899de33661493511d)

* Distro: nixos

* GPU: AMD

* CPU: Intel...

**Comment by YaLTeR** [comment]
Hmm, I see what's happening here. The mouse focus is (intentionally) not updated during animations, so when a window is in process of sliding under the cursor and you move it, it recognizes as moving the cursor over this new window. I'll try adding an extra focus update to the focus-follows-mouse logic.

**Comment by YaLTeR** [comment]
I pushed a commit that fixes this. Should be better now.
