### ISSUE TITLE
Error when using Nvidia 555 beta driver

### ISSUE THREAD

**Issue by armerpunkt** [YaLTeR/niri#386]
When trying to launch Niri after installing the 555 beta drivers, the screen remains black, and it produces the following error:

> WARN niri::backend::tty: error queueing frame: The underlying drm surface encountered an error: Page flip commit failed on device \`Some("/dev/dri/card1")\` (Operation not permitted (os error 1))

However, this is fixed in the latest commit of Smithay: https://github.com/Smithay/smithay/commit/fb44b240ea4a3aa39a6b92f5bede23301ab9a26e (I manually ran `cargo update smithay` and `cargo build --release` to test)

### System Information

* niri version: niri 0.1.6  and also the latest git

* Distro: Garuda

* GPU: Nvidia 3060ti

* CPU: AMD Ryzen 5600x

**Comment by YaLTeR** [comment]
Thanks for the report. Updated Smithay in 2ac8d840343dc964981507353c9128c68361cb6f, should work now.
