### ISSUE TITLE
Implement/support wallpaper 

### ISSUE THREAD

**Issue by wesbluemarine** [YaLTeR/niri#39]
Any chance? I've tried wbg but it doesn't work.
For me also a simple solid colour change could be enough.

**Comment by kchibisov** [comment]
And also just regular launch of `swaybg` should work...

**Comment by YaLTeR** [comment]
Yeah, swaybg works. A built-in background setting should also happen at some point, together with a built-in panel.

**Comment by wesbluemarine** [comment]
Thanks! Swaybg works as expected!.
