### ISSUE TITLE
wvkbd on screen keyboard closes when tapped

### ISSUE THREAD

**Issue by minego** [YaLTeR/niri#394]
The on screen keyboard wvkbd seems to launch properly but when you click on or tap on any key it closes immediately.

An issue was created on the wvkbd project's github page:
https://github.com/jjsullivan5196/wvkbd/issues/70

It was noted on that issue is that the compositor (in this case niri) did not accept the keymap.

### System Information

* niri version: niri unstable 2024-05-24 (commit 2ac8d840343dc964981507353c9128c68361cb6f)

* Distro: NixOS unstable (updated earlier today)

* GPU: AMD (SteamDeck) and Asahi (Macbook Pro)

* CPU: AMD (SteamDeck) and Apple M2

**Comment by YaLTeR** [comment]
I see a Smithay issue linked in there. I don't think this is a niri issue, rather a Smithay issue.

**Comment by minego** [comment]
> I see a Smithay issue linked in there. I don't think this is a niri issue, rather a Smithay issue.

Looking at the latest comments, and the Smithay bug report, I think you are correct. It wasn't clear initially where the fault was, but I think it is now safe to say that Niri isn't the cause and this can be closed. Thanks for looking.
