### ISSUE TITLE
focus-workspace only works on primary monitor

### ISSUE THREAD

**Issue by Nairou** [YaLTeR/niri#395]
When hitting a keybinding to switch focus to another workspace (i.e. `Mod+1 { focus-workspace "term"; }`), the workspace appears on the primary monitor, even if mouse/keyboard focus was on the secondary monitor.

### System Information

* niri version: niri 0.1.6 (unknown commit)

* Distro: NixOS

* GPU: AMD RX 6800 XT

* CPU: Intel i7-8700K

**Comment by YaLTeR** [comment]
Hm? Workspaces do not move between monitors when you focus them. That workspace is likely on the primary monitor, so that's where your mouse and keyboard went.

**Comment by Nairou** [comment]
> Workspaces do not move between monitors when you focus them.

Ah, okay. Coming from Sway, I wasn't expecting that. I tend to move workspaces between monitors a lot. :smile:

**Comment by YaLTeR** [comment]
Yeah, it works a bit differently in niri. You can move workspaces between monitors but you need to do it manually when you want it.

**Comment by Nairou** [comment]
What about when a workspace is manually moved to the second monitor?

1. Open a window in workspace 2
2. Switch to workspace 2 (on the primary monitor)
3. Move the workspace to the second monitor (the window is now visible there)
4. While on another workspace on the primary monitor, hit the keybinding to switch to workspace 2
5. The primary monitor switches to a blank workspace, rather than focusing the second monitor

**Comment by YaLTeR** [comment]
Focus by index will focus nth workspace on the current monitor. Focus by name will focus that named workspace.

**Comment by Nairou** [comment]
Thanks for the distinction. I should have clarified, I'm using a named workspace:

`Mod+2 { focus-workspace "notes"; }`

That keybinding only brings up the correct workspace (as in, the one with windows opened on it via window-rules) if it's already on the primary monitor.

**Comment by YaLTeR** [comment]
Hm, it should always focus that workspace on whatever monitor it is currently on, is that not what happens? You could check with `niri msg workspaces` just in case.

**Comment by Nairou** [comment]
Okay, I'm an idiot, disregard.

Thanks for the `niri msg workspaces` check, it showed me exactly what I did wrong. I thought I moved the workspace to the second monitor, but I only moved the column over. Once I moved the actual workspace, it worked as expected.

Sorry to waste your time, but also thanks for your help. :upside_down_face:

**Comment by YaLTeR** [comment]
Glad we figured it out!
