### ISSUE TITLE
chromium based apps not reading flags

### ISSUE THREAD

**Issue by dlasky** [YaLTeR/niri#4]
This is a weird one and not really expecting a solve, just wanted to bring it up...

For some reason brave, vscode, and a few other electron based apps are ignoring [app]-flags.conf and barfing on x-server not found even when ozone is set. (I also tried running them manually with the flags with similar result)

**Comment by YaLTeR** [comment]
Uhh, yeah, idk, I'm not sure I can help with this. I tried running
```
code --enable-features=WaylandWindowDecorations --ozone-platform-hint=auto
```
and it seemed to work for me?

**Comment by dlasky** [comment]
Interesting. do you have gnome installed + gnome-xdg portal? I suspect that has something to do with it cause of the ENV setup.

Feel free to close and i'll keep digging

**Comment by YaLTeR** [comment]
Yeah, I do have GNOME and xdg-desktop-portal-gnome. My plan is to try to keep some bare minimum of compatibility with that since that's my main DE and setup.

**Comment by YaLTeR** [comment]
I'll close since this doesn't seem to be niri-related at the moment, but feel free to keep posting here.

**Comment by raininja** [comment]
ya for me, in pure wayland, brave does not start, and I think it's because of gnome-keyring? IDK it works here in river (but I am running xwayland on that one).  I haven't done any digging, I just thought this might be related?

**Comment by ypurpl** [comment]
in case anyone's stuck here, https://wiki.archlinux.org/title/Wayland#Environment_variable fixes it. if you use uwsm, add 

`export ELECTRON_OZONE_PLATFORM_HINT=auto`

to `.config/uwsm/env`, or just use niri's environment config section
