### ISSUE TITLE
Discord wont launch

### ISSUE THREAD

**Issue by noomly** [YaLTeR/niri#405]
When opening Discord, the initial loading popup appears but when the apps open its window is just blank (with the default background color of Discord). It crashes, closes and reopens indefinitely; all while the loading popup is opened. I did configure it to run on Wayland natively, and I am able to run other Electron apps this way such as Spotify and Postman. I tried with Discord and Discord Canary.

I'm not sure how to get more logs from Niri.

<details>
<summary>Discord logs</summary>
<code>DiscordCanary 0.0.402
Starting app.
Starting updater.
2024-05-27T20:57:45.183Z [Modules] Modules initializing
2024-05-27T20:57:45.183Z [Modules] Distribution: remote
2024-05-27T20:57:45.184Z [Modules] Host updates: disabled
2024-05-27T20:57:45.184Z [Modules] Module updates: enabled
2024-05-27T20:57:45.185Z [Modules] Module install path: /home/noom/.config/discordcanary/0.0.402/modules
2024-05-27T20:57:45.185Z [Modules] Module installed file path: /home/noom/.config/discordcanary/0.0.402/modules/insta
lled.json
2024-05-27T20:57:45.185Z [Modules] Module download path: /home/noom/.config/discordcanary/0.0.402/modules/pending
splashScreen.initSplash(false)
CDM component API found
blackbox: 2024-05-27T20:57:45.813Z 0 

----------------------------------------------
CDM work timed out
blackbox: 2024-05-27T20:57:45.871Z 1 Discord starting: {"releaseChannel":"canary","version":"0.0.402"}, modulepath: /
home/noom/.config/discordcanary/0.0.402/modules
blackbox: 2024-05-27T20:57:45.934Z 2 ✅ webContents.created web1 "index.html"
blackbox: 2024-05-27T20:57:45.947Z 3 ✅ window.created win1 "discord"
splashScreen: SPLASH_SCREEN_READY
splashScreen.webContentsSend: SPLASH_SCREEN_QUOTE SPLASH_SCREEN_QUOTE [ 'Hold Tight — Loading Discord' ]
2024-05-27T20:57:46.225Z [Modules] No updates to install
splashScreen: no-pending-updates
2024-05-27T20:57:46.227Z [Modules] Host is up to date.
2024-05-27T20:57:46.228Z [Modules] Checking for module updates at https://discord.com/api/modules/canary/versions.json
splashScreen: checking-for-updates
splashScreen.updateSplashState checking-for-updates checking-for-updates {}
splashScreen.webContentsSend: SPLASH_UPDATE_STATE SPLASH_UPDATE_STATE [ { status: 'checking-for-updates' } ]
2024-05-27T20:57:46.447Z [Modules] No module updates available.
splashScreen: update-check-finished true 0 false
CDM completed with status (old updater): undefined
splashScreen.launchMainWindow: false
Optional module ./ElectronTestRpc was not included.
splashScreen.updateSplashState launching launching {}
splashScreen.webContentsSend: SPLASH_UPDATE_STATE SPLASH_UPDATE_STATE [ { status: 'launching' } ]
blackbox: 2024-05-27T20:57:46.912Z 4 ✅ webContents.created web2 ""
blackbox: 2024-05-27T20:57:46.928Z 5 ✅ window.created win2 "Discord"
blackbox: 2024-05-27T20:57:46.939Z 6 ✅ webContents.did-finish-load web1
[WebContents] crashed (reason: crashed, exitCode: 139)... reloading
Optional module ./ElectronTestRpc was not included.
blackbox: 2024-05-27T20:57:54.710Z 7 ❌ render-process-gone { reason: 'crashed', exitCode: 139 }
blackbox: 2024-05-27T20:57:54.779Z 8 window.closed win2</code>
</details>

### System Information

* niri version: niri 0.1.6 (unknown commit)

* Distro: Archlinux

* GPU: Integrated

* CPU: AMD Ryzen 7 PRO 3700U

**Comment by lpnh** [comment]
I don't know if this helps, but my approach is to launch [WebCord](https://github.com/SpacingBat3/WebCord) with  `--ozone-platform=wayland` .

**Comment by YaLTeR** [comment]
Yeah it's a discord issue, it still requires X11 for some reason even when running under Wayland.
