### ISSUE TITLE
Empty named workspaces are lost when monitor is disconnected

### ISSUE THREAD

**Issue by Nairou** [YaLTeR/niri#419]
I run niri on my desktop, with two monitors attached. Whenever I turn the monitors off for the night, wayland seems to see this as the monitors being disconnected. I had this issue with sway as well. It may be an AMD thing, I didn't notice this happening back with I used the motherboard's integrated Intel GPU.

However, when this happens, niri seems to drop any named workspaces that don't have windows in them. My impression was that named workspaces never get auto-deleted.

I currently get around this by forcing niri to reload its config, re-creating all workspaces.

### System Information

* niri version: niri 0.1.6 (unknown commit)

* Distro: NixOS

* GPU: AMD RX 6800 XT

* CPU: Intel i7 8700K

**Comment by YaLTeR** [comment]
Named workspaces should never get cleaned up. I'll take a look.

**Comment by YaLTeR** [comment]
Should be fixed in b5ad0e12fd46f7ab06f4bbc0e80bf3f2d4395cbf, not sure how we missed it.
