### ISSUE TITLE
remmina keyboard problems

### ISSUE THREAD

**Issue by bobblkabb** [YaLTeR/niri#437]
I don't know if this is a niri problem or a remmina problem. remmina works with other (hyprland) installations, so maybe it's rather a niri problem.
Keyboard input doesn't match! When I press 'e' I'm getting a 'ü' or 'o' for 'q', 'p' for 'w', '+' for 'r', 't' doesn't work at all.
...
somehow looks like it shifted:
'u', 'i', 'o', 'p' -> 'a', 's', 'd', 'f'

Any idea?

### System Information

* niri version: 0.1.6

* Distro: openSUSE Tumbleweed

* GPU: Intel Corporation HD Graphics 530 (rev 06)

* CPU: Intel Corporation Xeon E3-1200 v5/E3-1500 v5/6th Gen Core Processor Host Bridge/DRAM Registers (rev 07)

**Comment by YaLTeR** [comment]
Uhh huh? No clue honestly

**Comment by minego** [comment]
omg, I started seeing this recently too! I couldn't find anyone else reporting this anywhere. I assumed it was a bug in remmina, but I don't know.

**Comment by czarkoff** [comment]
FWIW in my experience,  when remote keyboard layout isn't US, RDP clients tend to map keys from the US layout,  regardless of local layout. Thus mapping is weird when local layout is also not US.

**Comment by YaLTeR** [comment]
> remmina works with other (hyprland) installations

Could it be that there it runs as an X11 application, so it's a Remmina Wayland bug? Mind testing it?

**Comment by herobrauni** [comment]
Same here, works with KDE wayland but sends strange input with niri.
Seems to me as if remmina runs wayland under kde:
![image](https://github.com/user-attachments/assets/71aa60cd-8cec-4d31-b473-d4c2716cd2be)

**Comment by YaLTeR** [comment]
Try running it with `env DISPLAY=` under KDE to be more sure it's not getting keymap from X11?

**Comment by herobrauni** [comment]
That indeed broke it on KDE as well.
Setting was `DISPLAY=:1` before if that helps. Setting that again makes the keyboard function normal.
Is that somehow applicable to niri?

**Comment by YaLTeR** [comment]
Yeah, then it's reading the keyboard layout from X11 for whatever reason. You can run it through one of the Xwayland options on niri.

**Comment by xdavidel** [comment]
I have the same problem as well even when using `xwayland-satellite`.
Running niri 25.05.1 (under nixos)
