### ISSUE TITLE
Transform rotation is opposite of Sway

### ISSUE THREAD

**Issue by tv42** [YaLTeR/niri#438]
I've been moving over from Sway, and noticed a funny difference that may hit others: niri's `output "..." { transform "90" }` is counter-clockwise, Sway's is clockwise: https://github.com/swaywm/sway/wiki#display-rotation

If this is something you don't hold a strong opinion on, it might be easier to go with what others are doing -- that part of my config was otherwise a copy-paste and mechanical transform, except for the laugh I got from having an upside-down portrait monitor.

### System Information

* niri version:  0.1.6

**Comment by YaLTeR** [comment]
I had considered this at the time of implementing the option: https://github.com/YaLTeR/niri/pull/137#issuecomment-1919726513 There's no "standard" among popular compositors, so I went with the less annoying way code-wise.
