### ISSUE TITLE
Whole screen flickering while switching windows 

### ISSUE THREAD

**Issue by mohammedbilalns** [YaLTeR/niri#441]
Sometimes, when switching between windows (using keybindings and touchpad gestures), the whole screen flickers for a few seconds. A green horizontal line appeared at the top of the screen before this started, and it still stays there.

### System Information
Lenovo Thinkbook G2 ITL

* niri version: niri 0.1.6 (unknown commit)

* Distro: Endeavour Os 

* GPU: Intel - Tigerlake-LP GT2

* CPU: 11th Gen i5-1135G7

**Comment by YaLTeR** [comment]
Huh? That sounds like a GPU or a screen issue

**Comment by mohammedbilalns** [comment]
> Huh? That sounds like a GPU or a screen issue
Yes it is , I just rebooted and it is still there in login manager .
