### ISSUE TITLE
xwayland fcitx5 problem

### ISSUE THREAD

**Issue by cexossqu** [YaLTeR/niri#445]
I have encountered two issues and am unsure if they are unsupported features or bugs. Both problems pertain to the fcitx5 input method in xwayland. Firstly, it appears that steam does not activate my fcitx5 under xwayland. Secondly, there are applications that activate fcitx5 but do not display a candidate box.

### System Information

* niri version: 0.1.6

* Distro: nixos

* GPU: AMD RX 6500xt

* CPU: intel 12100F

**Comment by YaLTeR** [comment]
I guess I'll delegate this question to @kchibisov, I don't have much experience with input methods.

How are you running Xwayland for Steam?

**Comment by cexossqu** [comment]
> I guess I'll delegate this question to @kchibisov, I don't have much experience with input methods.
> 
> How are you running Xwayland for Steam?

Using the first method in the wiki, run the xwayland command directly

**Comment by kchibisov** [comment]
I'm not sure it'll work unless fcitx5 knows before running about XWayland somehow, which won't happen, I guess. Though, maybe with dbus methods it'll work, I'm not sure what steam uses, never used IME in it and not sure it can work with XWayland at all.

As for windows who don't display the popup, they may set its position to some really big value just to never show it, but I never seen a Wayland app without the ime popup, but again, it's up to application to communicate that, if they don't then there won't be a popup. You can check that with `WAYLAND_DEBUG` for the client that lacks it.

**Comment by vollowx** [comment]
Are you running steam directly under rootful Xwayland or under a compositor like i3wm? In my case with i3wm, programs under Xorg can all get the candidates popup of IME.

**Comment by cexossqu** [comment]
> Are you running steam directly under rootful Xwayland or under a compositor like i3wm? In my case with i3wm, programs under Xorg can all get the candidates popup of IME.

I also use i3wm. I decided to forgo using fcitx5 under xwayland, as it was not particularly crucial to me.
Maybe we should use the Wayland app
Thanks everyone!!

**Comment by YaLTeR** [comment]
So I guess this should be closed since it's not necessarily a niri issue?
