### ISSUE TITLE
DISPLAY environment variable not set.

### ISSUE THREAD

**Issue by IamPyu** [YaLTeR/niri#452]
Various applications (Like teams-for-linux, minetest, etc.) will not open because DISPLAY is not set.

### System Information

* niri version: stable 0.1.6

* Distro: NixOS

* GPU: Intel Graphics Iris Xe

* CPU: Intel Core i7

**Comment by IamPyu** [comment]
Figures I don't have XWayland enabled.

**Comment by karesztrk** [comment]
Same here. Teams was not starting at all. I didnt know that it runs on X11

**Comment by Sempyos** [comment]
Microsoft teams for Linux has been disconnected in favor of Microsoft's PWA.

**Comment by LuckShiba** [comment]
if anyone is having this problem, you need to have `xwayland-satellite` installed (if you just installed, be sure to restart niri first).
