### ISSUE TITLE
Certain types of transparent windows show background as the active border color rather than the desktop

### ISSUE THREAD

**Issue by ThatOneCalculator** [YaLTeR/niri#459]
### The issue

Certain windows with transparency (like Foot) show fine:

![image](https://github.com/YaLTeR/niri/assets/44733677/fffabab1-57f0-4270-93da-8dce9cae920b)

While others like Nautilus (& seemingly all other GTK4 apps) and Zed show the color of the border:

![image](https://github.com/YaLTeR/niri/assets/44733677/eebb1971-fc6a-40ab-9075-c636e7a2059e)

![image](https://github.com/YaLTeR/niri/assets/44733677/1f2a06f4-50ed-42e2-a82d-2496de2f3298)

### System Information

* niri version: niri 0.1.6 (v0.1.6-56-g589e5a6)

* Distro: EndeavourOS x86_64

* GPU: AMD RX 6700XT

* CPU: AMD Ryzen 7 5800X

**Comment by YaLTeR** [comment]
This is because they don't signal server-side decoration support. You can override it with this window rule: https://github.com/YaLTeR/niri/wiki/Configuration:-Window-Rules#draw-border-with-background

**Comment by ThatOneCalculator** [comment]
That worked perfectly, thank you! Is there any reason that option isn't enabled by default?

**Comment by YaLTeR** [comment]
Windows can be arbitrary shape, for example with rounded corners. Some apps keep them during the tiled state. So niri needs the window to explicitly signal that it uses server-side decorations to omit the border background.
