### ISSUE TITLE
Flickering/screen corruption on a dual GPU laptop on Nvidia screen 

### ISSUE THREAD

**Issue by dragonnn** [YaLTeR/niri#469]
Hi! I am trying Niri on my ASUS Zephyrus G14 GA401IU with has two GPUs: 
04:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Renoir [Radeon Vega Series / Radeon Vega Mobile Series] (rev c6)
01:00.0 VGA compatible controller: NVIDIA Corporation TU116M [GeForce GTX 1660 Ti Mobile] (rev a1)
Where on of the laptop screen outputs is wired to the NVIDIA card (the USB-C port).
It works on Niri but I get heavy flickering/screen corruption if anything happens on that screen (it doesn't happen only in vscode but in anything else too).
[

https://github.com/YaLTeR/niri/assets/1771469/5efb94cc-c54e-46b2-9388-1a2d5d14ce90

](url)
on stable

https://github.com/YaLTeR/niri/assets/1771469/ac0c2410-2734-4f89-842e-5137abc30b01

on git version
that screen works fine on Hyprland without any flickering. Anything can be done about that?

### System Information

* niri version: 
* niri 0.1.6 (v0.1.6-57-gebaf1b0)
* and stable version 0.1.6 release from Arch repo

* Distro: Arch

* GPU: AMD Vega Mobile and GeForce GTX 1660 Ti Mobile

* CPU: AMD Ryzen 7 4800HS with Radeon Graphics

**Comment by YaLTeR** [comment]
Hey, I'm guessing that's just NVIDIA being NVIDIA. Let's wait for explicit sync in Smithay and niri and then see if it still happens.

**Comment by jeLee6gi** [comment]
I'm on a desktop with a 4070 and

**Comment by dragonnn** [comment]
> Hey, I'm guessing that's just NVIDIA being NVIDIA. Let's wait for explicit sync in Smithay and niri and then see if it still happens.

True, true but somehow Hyprland manages it so I hopped for maybe some workaround :D.
@jeLee6gi not yet, thanks I will try it. I see they is a debug section with options I can play around, didn't find it before.

**Comment by dragonnn** [comment]
Setting wait-for-frame-completion-before-queueing does look like it works now fine! So I can try move my system to niri. Thanks!

**Comment by YaLTeR** [comment]
Huh, okay, interesting.

**Comment by YaLTeR** [comment]
I'll mention this on the getting started wiki page.
