### ISSUE TITLE
Mod + Shift + / fails on fr keyboard

### ISSUE THREAD

**Issue by CaptainBloodz** [YaLTeR/niri#498]
### System Information

* niri version: niri 0.1.7 (unknown commit)

* Distro: Gentoo

* GPU: Intel Skylake

* CPU: Intel Skylake

Using 

input {
    keyboard {
        xkb {
            // You can set rules, model, layout, variant and options.
            // For more information, see xkeyboard-config(7).

            // For example:
            // layout "us,ru"
            layout "fr"
            // options "grp:win_space_toggle,compose:ralt,ctrl:nocaps"
        }
    }

Changing / to Question has the same issue, whether TTY or winit window.

**Comment by YaLTeR** [comment]
Fails how?

**Comment by CaptainBloodz** [comment]
It does trigger anything, whereas shortkeys menu shown at the beginning ot the session it expected to pop up again.

    // Mod-Shift-/, which is usually the same as Mod-?,
    // shows a list of important hotkeys.
    Mod+Shift+Slash { show-hotkey-overlay; }

**Comment by YaLTeR** [comment]
I guess it's some other key on the french layout, idk. Check with wev what it says when you press the key that you expect to be slash

**Comment by CaptainBloodz** [comment]
Mod+Shift+Colon { show-hotkey-overlay; }

Is the way with fr keyword. where / is shifted, colon the unshifted.

Thks

**Comment by CaptainBloodz** [comment]
Mod+Shift+Colon appears as Mod+Shift+colon where Colon is expected as in Slash
