### ISSUE TITLE
With `gaps 0` the focus ring is cut off

### ISSUE THREAD

**Issue by Schweber** [YaLTeR/niri#501]
When i set 
```
layout { 
    gaps 0
    focus-ring {
        width 1
        }
}
```
the focus ring is cut off at the screen edges. I find this counter intuitive and would like the focus ring to always be visible all around the window. I expect `gaps` to specify a  gap on top of the focus ring and not on top of the bare window without the focus ring.

### System Information

* niri version:  niri 0.1.7 (unknown commit)

* Distro: Nixos unstable

* GPU: AMD Ryzen 7 5800H

**Comment by YaLTeR** [comment]
I mean, the focus ring goes around the window. If the window is flush with the edges, it will be cut off. You could use a border if you'd like something that is "included" into the window. Or as you mention, just set gaps to 1 manually (or left/right/top/bottom strut).

**Comment by YaLTeR** [comment]
Do they have focus rings or is it a border?

**Comment by YaLTeR** [comment]
Maybe it should render on top of other windows? Not sure

**Comment by YaLTeR** [comment]
I just checked, the focus ring does already render on top of other windows, as it should. Which doesn't change the fact that it's cut off on the sides with no gaps (or struts), but yeah
