### ISSUE TITLE
Rounded Corners of layer shell components not showing after update

### ISSUE THREAD

**Issue by mohammedbilalns** [YaLTeR/niri#502]
An hour ago, I updated Niri from 0.1.6 to the version in chaotic-aur (0.1.7, v0.1.7-3-gc681198). Now, the layer shell components like Waybar and Wofi aren't showing their rounded corners, even though the screenshot shows them with rounded corners. 

![photo](https://github.com/YaLTeR/niri/assets/70318383/2cac0967-95ce-4e73-9e46-0cd8032c2d3a)
![screenshot](https://github.com/YaLTeR/niri/assets/70318383/efe42c2b-4675-4050-86b0-3cd62e4f534b)

Is this the version that supports fractional scaling?, I tried to set fractional scaling in the config, but it isn't working.

### System Information

* niri version: niri 0.1.7 (v0.1.7-3-gc681198)

* Distro:  EndeavourOS Linux x86_64

* GPU:Intel Tigerlake-LP GT2 (Iris Xe graphics )

* CPU: 11th gen Intel i5-1135G7

**Comment by YaLTeR** [comment]
> Waybar and Wofi

Could you check using the following bind? `Mod+Shift+Ctrl+O { debug-toggle-opaque-regions; }` If they show up as blue, then they are not setting their opaque region correctly, which is an application bug.

> Is this the version that supports fractional scaling?, I tried to set fractional scaling in the config, but it isn't working.

Yeah, should work.

**Comment by mohammedbilalns** [comment]
> Could you check using the following bind? `Mod+Shift+Ctrl+O { debug-toggle-opaque-regions; }` If they show up as blue, then they are not setting their opaque region correctly, which is an application bug.

![2024-07-02T22:17:32,608856676+05:30](https://github.com/YaLTeR/niri/assets/70318383/189b9691-afc7-4927-a658-ce5ca3187f4d)
![2024-07-02T22:17:41,678692589+05:30](https://github.com/YaLTeR/niri/assets/70318383/2f99ae41-64dc-4d17-806d-46c43cd3fba1)
![2024-07-02T22:17:48,887412695+05:30](https://github.com/YaLTeR/niri/assets/70318383/aaa1cf93-2930-4c23-9b0a-641befd0ea5e)


> > Is this the version that supports fractional scaling?, I tried to set fractional scaling in the config, but it isn't working.
> Yeah, should work.
I tried setting the scale to 1.2 and 1.5 in the config. Is there something else I should do?

**Comment by YaLTeR** [comment]
Yeah, you can see it's all blue, including the corners. It's a client bug, they're setting the opaque region incorrectly.

> I tried setting the scale to 1.2 and 1.5 in the config. Is there something else I should do?

No, just set that for the correct output (and make sure you uncomment the output node).

**Comment by mohammedbilalns** [comment]
Fractional scaling is working fine now. I forgot to uncomment the output node as you said.

**Comment by mohammedbilalns** [comment]
The screen becomes fully red for a fraction of a second when activating Swaylock. Is this related to the issue?

**Comment by YaLTeR** [comment]
That is not related, that is #119

**Comment by lpnh** [comment]
> The screen becomes fully red for a fraction of a second when activating Swaylock. Is this related to the issue?

I "solved" this red screen issue by calling niri `do-screen-transition` action before running `swaylock`, like this:

```nushell
#!/usr/bin/env nu

niri msg action do-screen-transition --delay-ms 300

swaylock -f
```

Using the script in niri `config.kdl` file:

```
Pause { spawn "~/.config/nushell/scripts/lock-screen.nu"; }
```

You can adjust the `--delay-ms` value to your preference. I use an image as the lock screen, and this adds a very nice smooth transition. I plan to keep using it even after the fix.

**Comment by YaLTeR** [comment]
Closing because this is a client bug.
