### ISSUE TITLE
Random stuttering in games/applications

### ISSUE THREAD

**Issue by IgnIVertiKalCaD** [YaLTeR/niri#510]
Niri config: https://hastebin.com/share/oxigefakep.csharp

### System Information
* niri version: niri 0.1.7 (unknown commit) | my build
* Distro: NixOS 24.11pre644361.1
* GPU: AMD ATI Radeon RX 6700XT | OC: LACT 
* CPU: AMD Ryzen 7 3800X
* Monitors: 4k LG | WQHD AOC 
 
Video of the problem: https://youtu.be/xBXdEbvG-VM

I don't know what causes me to have stuttering and other problems in apps/games. They happen at random times. The video doesn't show it as much. I have 2 or 3 frames per second on my video in general. 
Stuttering can start at any time for no reason at all. I had this problem on hyprland (still do), but only with games. On NIRI I have this problem everywhere.
#
Я не знаю из-за чего у меня происходят stuttering и прочие проблемы в приложениях/играх. Происходят они в случайное время. На видео это не так видно. У меня на видео вообще кадра 2 или 3 в секунду. 
В любое время могут начаться stuttering без какой-либо причины. Такая проблема была на hyprland (она и осталась), но только с играми. На NIRI же у меня проблема везде.

**Comment by YaLTeR** [comment]
Хм, странно. Не знаю, как тут лучше диагностировать. В этом процессоре же нет iGPU, то есть только одна ГПУ в системе?

> У меня на видео вообще кадра 2 или 3 в секунду.

Это тоже довольно странно, это не из-за видеоэнкодера случаем? В превью OBS нормально выглядит?

**Comment by IgnIVertiKalCaD** [comment]
> Хм, странно. Не знаю, как тут лучше диагностировать. В этом процессоре же нет iGPU, то есть только одна ГПУ в системе?
> 
> > У меня на видео вообще кадра 2 или 3 в секунду.
> 
> Это тоже довольно странно, это не из-за видеоэнкодера случаем? В превью OBS нормально выглядит?

В превью картинка 60/60, вообще соска. Encoder - H264/gpu/vaapi
В моей проце нет igpu. В системе только dgpu. 
Проблемы такой нет в hyprland, поэтому не факт, что проблема в mesa, либо в чём-то ином.

**Comment by IgnIVertiKalCaD** [comment]
I was able to capture in normal frame quality. The problem of the fact that the recording was not 60, but about 0 frames - streaming. I was streaming while recording. It's either a niri problem, obs problem, or I don't know what.

Anyway, I was able to capture the frame sag. On normal page flipping, I'm getting frame sagging as if the compositor is failing. On hyprland for half a year of work on it I have not observed such a thing

Translated with DeepL.com (free version)
#
https://youtu.be/tAtLwz8HaJw

**Comment by YaLTeR** [comment]
Так, ну такое сложно дебажить, конечно, но можно попробовать вот что.

1. Построй у себя `https://github.com/wolfpld/tracy/tree/v0.10` (именно тег v0.10).
1. Скомпилируй niri через `cargo build --release --features=profile-with-tracy`. Это будет билд с профайлингом, им нельзя пользоваться просто так (т.к. он собирает профайлинг инфу в оперативку).
1. Запусти этот билд на другом TTY, подключи к нему Tracy `./capture-release -o output.tracy -f`, пока он собирает данные попробуй репродьюснуть проблему. Как только репродьюснешь, сразу в Tracy нажми Ctrl-C, чтобы легко было потом найти, в какой момент собственно была проблема.
1. Пришли как-нибудь полученный файл, и я посмотрю, есть ли там что-то интересное.

**Comment by YaLTeR** [comment]
Ещё для интереса: если в фоне включить что-то, что использует немного GPU, просто чтобы его держать в разогретом состоянии, проблема пропадает?

**Comment by IgnIVertiKalCaD** [comment]
> Ещё для интереса: если в фоне включить что-то, что использует немного GPU, просто чтобы его держать в разогретом состоянии, проблема пропадает?

No, I don't. I stream during the whole work process. But even without streaming, the footage drops like on good, old X

**Comment by IgnIVertiKalCaD** [comment]
> Так, ну такое сложно дебажить, конечно, но можно попробовать вот что.
> 
>     1. Построй у себя `https://github.com/wolfpld/tracy/tree/v0.10` (именно тег v0.10).
> 
>     2. Скомпилируй niri через `cargo build --release --features=profile-with-tracy`. Это будет билд с профайлингом, им нельзя пользоваться просто так (т.к. он собирает профайлинг инфу в оперативку).
> 
>     3. Запусти этот билд на другом TTY, подключи к нему Tracy `./capture-release -o output.tracy -f`, пока он собирает данные попробуй репродьюснуть проблему. Как только репродьюснешь, сразу в Tracy нажми Ctrl-C, чтобы легко было потом найти, в какой момент собственно была проблема.
> 
>     4. Пришли как-нибудь полученный файл, и я посмотрю, есть ли там что-то интересное.

I couldn't nail the tracy, as I didn't understand how to build it at all. I don't understand C++ projects.
#
Я не смог забилдить tracy, так как я вообще не понял, как её билдить. Я C++ проекты не понимаю.

**Comment by YaLTeR** [comment]
Там есть manual.pdf, в нём есть инструкции.

**Comment by IgnIVertiKalCaD** [comment]
https://snipboard.io/7BjNM1.jpg

Вот такие у меня проблемы на niri.
На гноме, можно мне на слово поверить, stutterings намного меньше. Я бы даже сказал, что их вообще нет. А на niri и hyprland это уже не смешно. Я проведу тесты, чтобы было понятно, что проблема именно в композиторе.
#
That's the kind of problems I'm having on niri.
On gnome, you can take my word for it, stutterings are much smaller. I'd even say there are none at all. And on niri and hyprland it's not funny anymore. I'll run some tests to make it clear that it's the compositor that's the problem.

**Comment by IgnIVertiKalCaD** [comment]
Tracy - https://drive.google.com/file/d/17i7QDtkhqOJ7_zLEvbYMFIbW9fWTEjr-/view?usp=sharing
![image](https://github.com/YaLTeR/niri/assets/54883747/4875966b-be10-45fc-ab02-6ff89e917537)

Нужна инфа о том, что было запущено в этот момент? У меня происходят дропы кадров до 10 и так постоянно. Вверх вниз, вверх вниз, вверх вниз.
#
Need info on what was running at that point? I'm getting frame drops of up to 10 frames and such all the time. Up down, up down, up down, up down.

**Comment by YaLTeR** [comment]
Я на этой записи вижу только один интервал длиной 2 с, когда были какие-то фрейм дропы (на мониторе DP-1, который постоянно перерисовывается):

![image](https://github.com/YaLTeR/niri/assets/1794388/f660867c-bc44-4372-bfaa-5ea265e8df09)

Но ни здесь, ни в другой части записи, никаких лагов композитора я не наблюдаю. То есть кажется, что лагает не композитор, а приложения.

Второй монитор DP-2 перерисовывается достаточно нечасто и непостоянно, но опять же, на стороне композитора лагов не вижу.

Можешь проверить, если ты во время фрейм дропов запустишь какую-то анимацию композитора (например, переключение воркспейса или Mod+MMB перетаскивание), то она будет лагать или нет?

**Comment by IgnIVertiKalCaD** [comment]
Как раз лагов анимаций я вообще не наблюдал. Лагают приложения при скролле. Ощущается это как дропы кадров, что очень мешает и портит рабочий процесс. DP-1 4k монитор, DP-2 WQHD монитор. 

Я могу заснять, как это выглядит со стороны - на камеру смартфона.

Что я могу ещё предоставить для анализа ситуации? 
#
I have not observed any animation lags at all. Applications lag when scrolling. It feels like frame drops, which is very annoying and spoils the workflow. DP-1 4k monitor, DP-2 WQHD monitor. 

I can take a picture of how it looks from the side - on my smartphone camera.

What else can I provide to analyze the situation?

**Comment by YaLTeR** [comment]
Ну даже не знаю, что сказать, или как тут ещё можно диагностировать. Мб баг Мезы какой-нибудь, или какая-то неудачная приоритизация работы ГПУ?

**Comment by IgnIVertiKalCaD** [comment]
> Ну даже не знаю, что сказать, или как тут ещё можно диагностировать. Мб баг Мезы какой-нибудь, или какая-то неудачная приоритизация работы ГПУ?

На какой mesa у Вас использует niri? Я его сбилжу и протестирую. В этот раз с полным мониторингом всей системы и тд. 
#
What mesa are you using niri on? I'll knock it down and test it. This time with full system monitoring and so on.

**Comment by YaLTeR** [comment]
Ту, что установлена в системе, там ничего особенного нет. Я сам сижу на Fedora Silverblue, тут сейчас 24.1.2.

**Comment by IgnIVertiKalCaD** [comment]
У меня стоит Mesa 24.1.1

**Comment by IgnIVertiKalCaD** [comment]
Проблема с играми была в прослойке Xwayland. Я попробовал Xwayland-sateline и вот они 60 стабильных, плавным, приятных и вкусных кадров.

Проблема со статтерами в firefox - проблема была в настройке webGPU. Я сбросил настройки фурятины и просадки пропали.
#
The problem with the games was the Xwayland layer. I tried Xwayland-sateline and there they are 60 stable, smooth, nice and tasty frames.

The problem with statlines in firefox - the problem was in the webGPU setting. I reset the firefox settings and the sags disappeared.

**Comment by YaLTeR** [comment]
Понятно, хорошо, что разобрались.

**Comment by IgnIVertiKalCaD** [comment]
> Понятно, хорошо, что разобрались.

Тебе спасибо, что говнокод не пишешь. Твой DE не идеально, но оно стребится до того идеала, который бы я хотел видеть в "своих" продуктах. Я буду рад помочь в тестировкой и прочей лабудой, если это не код. Я rust понимаю на уровне ребёнка из 5г класса. 
Если не хватает рук на что-либо, я буду рад помочь. Спасибо за труд.
