### ISSUE TITLE
extra bottom spacing on foot when not using prefer-no-csd and disabling foot csd

### ISSUE THREAD

**Issue by nekopsykose** [YaLTeR/niri#519]
picture: ![](https://img.ayaya.dev/ebtmm9ltqmyu)

note the extra space at the bottom

since prefer-no-csd is not set (intentionally; i want most csds), foot normally draws its own csd (which looks terrible). disabling it with

```ini
[csd]
preferred = none
```

in foot.ini then ends up with that extra bottom spacing, which is the same size as the actual csd would be.

i'm not sure if this is a bug in niri or in foot, but thought i'd start here

there could be an extra workaround of allowing setting prefer-no-csd in window rules, but i think that isn't supported

### System Information

* niri version: niri 0.1.7 (v0.1.7-3-gc681198-modified)

* Distro: Chimera Linux

* GPU: RX 6600

* CPU: r7 5800x

**Comment by YaLTeR** [comment]
It's because in this mode foot will restrict its size to whole terminal cell size. With prefer-no-csd it doesn't do it, maybe because of the tiled state. There's currently no way to control this in niri, but maybe there's a foot setting for it. Either way, it's not a niri or a foot bug, just how it works.

**Comment by nekopsykose** [comment]
that makes sense, thanks!

**Comment by dnkl** [comment]
> maybe because of the tiled state.

Sounds right. CSDs or SSDs doesn't affect whether foot resizes by cells or not, only the window state does. Only floating windows (i.e. not tiled, not maximized and not fullscreen) does.

It (size window in cell multiples) can be disabled for floating windows as well, by setting `resize-by-cells=no` in `foot.ini`.

**Comment by nekopsykose** [comment]
> It (size window in cell multiples) can be disabled for floating windows as well, by setting resize-by-cells=no in foot.ini.  

i didn't think of that.. thanks! it works perfectly with that set :)

**Comment by YaLTeR** [comment]
Thanks! I think I'll end up adding some way to change whether the tiled state is used or not used (currently it's tied to prefer-no-csd). But nice to see there's a foot option to control this.
