### ISSUE TITLE
seemingly unknown/incorrect monitor display names

### ISSUE THREAD

**Issue by nekopsykose** [YaLTeR/niri#523]
in `niri msg outputs`, it seems my monitor gets detected as unknown:

```
$ niri msg outputs
Output "DP-1" (Unknown - Unknown - DP-1)
  Current mode: 2560x1440 @ 169.831 Hz
```

wlroots-based compositors seem to handle this correctly:

```
...
    "make": "GIGA-BYTE TECHNOLOGY CO., LTD.",
    "model": "M27Q",
    "serial": "21240B002501",
...
```

kde (which also uses libdisplay-info) also does. not sure what gnome does, but it's also correct (checked in `wayland-info` which reflects the same info):

```
interface: 'wl_output',                                  version:  4, name:  4
        name: DP-1
        description: GIGA-BYTE TECHNOLOGY CO., LTD. 32"
        x: 0, y: 0, scale: 1,
        physical_width: 700 mm, physical_height: 390 mm,
        make: 'GBT', model: 'M27Q',
```

i assume this is more of a smithay issue than a niri one, but thought i'd start here. i guess there's just an incomplete EDID parsing implementation?

### System Information

* niri version: niri 0.1.7 (v0.1.7-12-g6147a31)

* Distro: Chimera Linux

* GPU: RX 6600

* CPU: r7 5800x

**Comment by YaLTeR** [comment]
Yeah, waiting for someone to finish libdisplay-info integration in Smithay: https://github.com/Smithay/libdisplay-info-rs/pull/5
