### ISSUE TITLE
gnome-maps doesn't launch via provided desktop file

### ISSUE THREAD

**Issue by nekopsykose** [YaLTeR/niri#525]
(also in flatpak)

gnome-maps has a .desktop file that looks something like

```
Exec=gapplication launch org.gnome.Maps %U
```

this (afaik) launches the dbus service:

```
[D-BUS Service]
Name=org.gnome.Maps
Exec=/usr/share/gnome-maps/org.gnome.Maps --gapplication-service
```

a trace of execution looks like:

```
$ extrace
331473 fuzzel --log-no-syslog
  331475 /usr/bin/flatpak run '--branch=stable' '--arch=x86_64' '--command=gapplication' --file-forwarding org.gnome.Maps launch org.gnome.Maps @@u @@
331483 bwrap --args 38 -- xdg-dbus-proxy '--args=40'
  331484 xdg-dbus-proxy '--args=40'
331475 bwrap --args 38 -- gapplication launch org.gnome.Maps
    331488 gapplication launch org.gnome.Maps
          331494 /usr/bin/flatpak run '--branch=stable' '--arch=x86_64' '--command=/app/share/gnome-maps/org.gnome.Maps' org.gnome.Maps --gapplication-service
      331499 bwrap --args 38 -- xdg-dbus-proxy '--args=40'
        331500 xdg-dbus-proxy '--args=40'
          331494 bwrap --args 38 -- /app/share/gnome-maps/org.gnome.Maps --gapplication-service
              331504 /usr/bin/gjs /app/share/gnome-maps/org.gnome.Maps --gapplication-service
```

note the gapplication-service arg. launching it without this arg works.

however, it also works with this arg in other compositors- on niri it never shows up and has to be ran manually:

```
flatpak run org.gnome.Maps # works, invokes the executable directly
```

maybe this is a quirk of not using a systemd distro (i didn't check a systemd one), but it does work in gnome/kde/sway instead, so not sure why

### System Information

* niri version: niri 0.1.7 (v0.1.7-12-g6147a31)

* Distro: Chimera Linux

* GPU: RX 6600

* CPU: r7 5800X

**Comment by YaLTeR** [comment]
Just tried, worked fine for me from fuzzel. So likely on your side.

**Comment by nekopsykose** [comment]
yeah, i'm stupid. that's what happens when you test a bunch of wayland sessions in parallel for $reasons and end up breaking the user dbus session and not notice it...
