### ISSUE TITLE
High memory and CPU usage

### ISSUE THREAD

**Issue by hashankur** [YaLTeR/niri#533]
Runs normally for a few hours but memory and CPU increases slowly. Cursor movement, selection, drag-drop and animations lags.

[Perf record flamegraph](https://github.com/YaLTeR/niri/assets/46897914/79fd17e4-74f3-4246-9c1f-e280a66868ea)

~Suspected wine, but happens without running it~

https://github.com/YaLTeR/niri/assets/46897914/400b4c12-571d-47f5-8b74-ee1fcdfbda26

### System Information

* niri version: niri stable 0.1.7

* Distro: NixOS 24.11

* GPU: Radeon RX Vega 6 integrated graphics

* CPU: AMD Ryzen 3 5300U

**Comment by YaLTeR** [comment]
Huh. That flame graph is also broken, how did you record it?

**Comment by hashankur** [comment]
```
perf record -F 999 --call-graph=fp -p $(pidof niri)
perf script | inferno-collapse-perf | inferno-flamegraph > flamegraph.svg
```

**Comment by YaLTeR** [comment]
Did you build niri with frame pointers? You need Rust 1.79.0 and this in `.cargo/config.toml`:
```
[build]
rustflags = ["-C", "force-frame-pointers=yes"]
```

**Comment by hashankur** [comment]
No, I'll do that.

**Comment by hashankur** [comment]
[flamegraph | debuginfo + force-frame-pointers](https://github.com/YaLTeR/niri/assets/46897914/ae447ef7-b730-4990-b80b-d3491a4c854d)

**Comment by hashankur** [comment]
That seemed to work. Recorded for ~1 min.

[flamegraph_dwarf](https://github.com/YaLTeR/niri/assets/46897914/eaef0835-008c-4b4c-a1fd-5dc0294d1784) (moving around, text selection)
[flamegraph_dwarf_idle](https://github.com/YaLTeR/niri/assets/46897914/b9738717-fdaa-4c03-9b7b-eff53e2f44d3)

**Comment by YaLTeR** [comment]
Are you running any clipboard managers or something? It appears that something is constantly requesting the clipboard contents.

**Comment by hashankur** [comment]
Yes. [clipse](https://github.com/savedra1/clipse).

There's a listener command for it on startup. I'll try running niri without it.

**Comment by hashankur** [comment]
I can confirm its the clipboard manager.

Can I know if this is a niri bug or something related to clipse?

**Comment by YaLTeR** [comment]
I guess I'll need to check myself

**Comment by YaLTeR** [comment]
Did you have this lag on any other compositors?

**Comment by hashankur** [comment]
Hmm, Hyprland did have a somewhat similar lag, but it was rare.

I'll try a different clipboard manager and see if this happens.

**Comment by hashankur** [comment]
Seems to be a clipse problem. Cliphist works fine.

**Comment by oatmealine** [comment]
Can repro with clipse, switched to cliphist as suggested and it did not go away. Seems to be specifically related to copying, pasting and selecting text (writing/reading from the clipboard buffers). Weirdly, I can't replicate this on my laptop which _should_ be running the exact same software
