### ISSUE TITLE
failed to update: niri/cagro.lock need to be update, but --lock flag prevent this

### ISSUE THREAD

**Issue by alphanhp** [YaLTeR/niri#541]
Updating git repository `https://github.com/Smithay/smithay.git`
error: the lock file /home/nhp/.cache/paru/clone/niri-git/src/niri/Cargo.lock needs to be updated but --locked was passed to prevent this
If you want to try to generate the lock file without accessing the network, remove the --locked flag and use --offline instead.
==> ERROR: A failure occurred in prepare().
    Aborting...
error: failed to build 'niri-git-0.1.6.r0.d96a66d-1': 
error: packages failed to build: niri-git-0.1.6.r0.d96a66d-1

### System Information
arch linux-zen 6.9.8

* niri version: niri-git-0.1.6.r0.d96a66d-1

* Distro: 
arch

* GPU: 
nvidia 1060

* CPU:

**Comment by YaLTeR** [comment]
Try again now?

**Comment by alphanhp** [comment]
It works successful !
