### ISSUE TITLE
xdg-desktop-portal-wlr won't launch, causing screensharing to fail

### ISSUE THREAD

**Issue by theoparis** [YaLTeR/niri#544]
```
[theo@gigamachine ~]$ /usr/libexec/xdg-desktop-portal-wlr -r
wl_registry#2: error 0: invalid version for global zwlr_screencopy_manager_v1 (27): have 1, wanted 2
```

### System Information

* niri version: niri 0.1.7 (v0.1.7-41-ga5a3493)

* Distro: Arch Linux

* GPU: AMD 6600 XT

* CPU: AMD Ryzen 5600x

**Comment by YaLTeR** [comment]
You need xdg-desktop-portal-gnome for screencasting, not -wlr.

**Comment by sakithb** [comment]
for anyone else stumbling upon this issue and doesn't want to install xdg-desktop-portal-gnome (which brings in nautilus/gnome-desktop packages on arch) just for screencasting. i replaced "gnome" with "wlr" in /usr/share/xdg-desktop-portal/niri-portals.conf.

**Comment by revanj** [comment]
> for anyone else stumbling upon this issue and doesn't want to install xdg-desktop-portal-gnome (which brings in nautilus/gnome-desktop packages on arch) just for screencasting. copy /usr/share/xdg-desktop-portal/niri-portals.conf to $XDG_CONFIG_HOME/xdg-desktop-portal/portals.conf and replace "gnome" with "wlr"

this works very well. thank you!!

**Comment by KiaraGrouwstra** [comment]
> for anyone else stumbling upon this issue and doesn't want to install xdg-desktop-portal-gnome (which brings in nautilus/gnome-desktop packages on arch) just for screencasting. copy /usr/share/xdg-desktop-portal/niri-portals.conf to $XDG_CONFIG_HOME/xdg-desktop-portal/portals.conf and replace "gnome" with "wlr"

it would be nice to get the portal support somewhat rounded out, whereas [it seems](https://wiki.archlinux.org/title/XDG_Desktop_Portal) this change would mean losing portals:

- Background
- Clipboard
- Input capture
- Screenshot
- Wallpaper

i don't feel like i can quite gauge the impact of that, but i wonder if there might be other light-weight portals to help out on some of these.
for screenshots, for one, niri's [own screenshot functionality](https://yalter.github.io/niri/Configuration%3A-Key-Bindings.html#screenshot-screenshot-screen-screenshot-window) comes to mind, begging the question if that could be exposed through some `xdg-desktop-portal-niri` perhaps.
