### ISSUE TITLE
ulauncher doesn't float on top , as wofi

### ISSUE THREAD

**Issue by r4hulrosh4n** [YaLTeR/niri#553]
how can i make ulauncher float on top 
![image](https://github.com/user-attachments/assets/b79d910d-ec20-46a7-8985-e98d909abbb4)

**Comment by YaLTeR** [comment]
I'm guessing that they are creating a regular window rather than using layer-shell. They should really use layer-shell for this, but otherwise this should behave as expected once #122 is implemented.

**Comment by friday** [comment]
Ulauncher v6 (huge rewrite, still in beta but approaching stable release soon) uses Layer Shell. From my limited testing it works great in Niri.
