### ISSUE TITLE
Add "mesa-libEGL" as HARD dependency on Fedora Copr

### ISSUE THREAD

**Issue by thepragmaticmero** [YaLTeR/niri#554]
### System Information

* niri version: 0.1.7

* Distro: Fedora Everything (Minimal install)

* GPU: Intel UHD something something

* CPU: Intel 11400

IDK where to commit/ask changes to the [Fedora copr repo](https://copr.fedorainfracloud.org/coprs/yalter/niri/) so I'm doing it here.

Some crazy guy like me likes to replicate Arch Linux installs on Fedora (the whole OS only takes up 1.1GiB), when using `sudo dnf install niri --setopt=install_weak_dependencies=False` and later then execute `niri-session` it crashes automatically, I learnt to debug that using `journalctl -eb /usr/bin/niri` and the package `mesa-libEGL` is missing, after installing it works fine and nice. I guess the package `mesa-libEGL` isn't added as hard dependency on [Fedora copr](https://copr.fedorainfracloud.org/).

Also I'd like to know where I could commit or ask for changes to copr repos on fedora?, thks YalteR. I'm eating yogurt and oatmeal rn.

**Comment by YaLTeR** [comment]
I have mesa-dri-drivers there, that's not enough I guess?
