### ISSUE TITLE
Let windows spawned with compositor binds steal focus

### ISSUE THREAD

**Issue by r4hulrosh4n** [YaLTeR/niri#558]
When I am in full screen and try to open a new window, it doesn't focus on the newly created window.

**Comment by YaLTeR** [comment]
This is the result of a focus stealing prevention policy. However, ideally it shouldn't apply to windows spawned with compositor binds. Need to figure out how to do that, probably using xdg-activation.

**Comment by r4hulrosh4n** [comment]
okay !

**Comment by salman-farooq-sh** [comment]
Can the new IPC in the 0.1.9 version help with this at least as a workaround until something proper is done?

**Comment by YaLTeR** [comment]
Maybe, depends on what you want

**Comment by tyressk** [comment]
Does this issue also apply to when there is a `window-rule` -> `open-on-workspace` config for that window? Currently it doesn't do that and it would be nice if it automatically jumped to that workspace

**Comment by YaLTeR** [comment]
I think it should, yeah. Will need to see once it's implemented, what feels good.

**Comment by YaLTeR** [comment]
With #779 merged, this now works as long as the window correctly activates itself with the provided xdg-activation token. Even works when launching through fuzzel.
