### ISSUE TITLE
file picker not opening

### ISSUE THREAD

**Issue by JimitSoni18** [YaLTeR/niri#560]
### System Information

* niri version: niri 0.1.7 (v0.1.7-53-gd777810)

* Distro: void linux

* GPU: integrated intel

* CPU: intel i5-4200M

i have installed xdg-desktop-portal xdg-desktop-portal-gtk xdg-desktop-portal-gnome and copied resources/niri-portals.conf to /usr/share/xdg-desktop-portals, started niri using niri --session, and then when i try to open a file picker from lapce editor, or my own application that uses the rfd crate, the file picker does not open.
i do not have systemd, void uses runit.
i compiled niri from source

**Comment by YaLTeR** [comment]
Did you start a d-bus session?

**Comment by JimitSoni18** [comment]
@YaLTeR , i don't know what that means, i did add the dbus service:

```
~
❯ sudo sv status dbus
Password:
run: dbus: (pid 818) 1492s; run: log: (pid 817) 1492s
```

**Comment by YaLTeR** [comment]
You might want to ask other void linux users, I'm not familiar with how it works. But you need to run niri inside a working d-bus session for portals to work. Maybe you need `dinit`? (and build niri with the `dinit` feature)

**Comment by JimitSoni18** [comment]
yes i did build it with dinit, xdp-gnome-screencast,dbus features. i will ask in the void matrix discussion channel. thank you for your quick response btw

**Comment by JimitSoni18** [comment]
hello, as you said, i needed to run it under dbus session. i got it working now, thanks!

btw this compositor is awesome, i want to learn about wayland but i cannot find a starting point, as the wayland docs require a fair bit of knowledge about x, 2d rendering, and linux in general, and smithy has almost no docs, so i wanted to ask what according to you would be a good starting point

**Comment by YaLTeR** [comment]
Good you got it working!

Do you want to learn about Wayland compositors specifically? I guess drop into the Smithay room on Matrix and ask around. Also take a look at smallvil code (in the Smithay repo). Not sure there's a good resource readily available and it's quite complex a topic indeed.
