### ISSUE TITLE
Helldivers 2 - black window

### ISSUE THREAD

**Issue by shumvgolove** [YaLTeR/niri#561]
Original issue: https://github.com/Supreeeme/xwayland-satellite/issues/44

Running Helldivers 2 with `Xwayland`, `gamescope` or `xwayland-satellite` produces a black window.

The issue is not happening in `Sway` session, where switching the game display setting to Borderless window actually allows `Niri` to render the game normally. Switching the game display mode back to Fullscreen in `Niri` session, weirdly enough,  works fine until you lose focus on the game (e.g. spawn browser/terminal).

### System Information

* niri version: 0.1.7

* Distro: Chimera Linux

* GPU: AMD Radeon RX 7800 XT 

* CPU: AMD Ryzen 7 7800X3D

**Comment by YaLTeR** [comment]
What happens if you run it in a rootful Xwayland in sway?

**Comment by shumvgolove** [comment]
Both `Niri` and `Sway` run the game fine in rootful mode:

**Comment by shumvgolove** [comment]
I should mention that, as far as I understand, the game will render black until you click (focus) the game window, so it will capture your input (this happens in `Sway`). In `Niri` with `xwayland-satellite` it seems like the game never captures that input, so it renders black (I hear the video intro, but no matter what I press, I can't skip it).

**Comment by YaLTeR** [comment]
So, I don't quite understand what does and doesn't work. You mentioned at first that "Running Helldivers 2 with `Xwayland`, ... produces a black window." but then you said that Xwayland (rootful) runs it fine in niri?

**Comment by shumvgolove** [comment]
- Spawn `Xwayland` without flags.
- Start Steam and Helldivers 2.

Result: black screen.

- Spawn `Xwayland` without flags.
- Run `i3`.
- Start Steam and Helldivers 2.

Result: game renders fine.

**Comment by YaLTeR** [comment]
Does black screen in rootful Xwayland without i3 reproduce if you do the same steps in sway?

**Comment by shumvgolove** [comment]
Yeah, I can reproduce it on Sway, sorry.

Anyhow, I double checked `gamescope` and `xwayland-satellite`/`xwayland rootless` behaviour:

## Gamescope

`Sway`

* Run `gamescope -- steam`
* Run Helldivers 2

Result: renders.

`Niri`

* Run `gamescope -- steam`
* Run Helldivers 2

Result: black window.

## xwayland (rootless/-satellite)

`Sway`

* Start Steam and Helldivers 2 (duh)

Result: renders.

`Niri`

* Run `xwayland-satellite`
* Start Steam and Helldivers 2 

Result: black window.

**Comment by YaLTeR** [comment]
Gamescope on sway probably works because it runs as an X11 client there. So yeah, seems like not a niri issue

**Comment by shumvgolove** [comment]
Thanks, sorry for the noise!
