### ISSUE TITLE
OBS Screen Capture Option not avalible

### ISSUE THREAD

**Issue by Ouxyre** [YaLTeR/niri#564]
Cannot find the screen capture option on OBS

### **System Information:**

* niri version: niri 0.1.7 (unknown commit)

* Distro: Arch Linux

* GPU: Intel HD Graphics 515 

* CPU: Intel Core m3-6Y30 

I am simply unable to screen caputre in OBS
![image](https://github.com/user-attachments/assets/b2b112f9-d3aa-46c3-b271-6b12caac51fc)

Running obs via terminal yields:
`info: [pipewire] No capture sources available`

I've already installed pipewire-pulse and xdg-desktop-portal-wlr but still unable to capture my screen

**Comment by YaLTeR** [comment]
You need xdg-desktop-portal-gnome to screencast from niri.

**Comment by Ouxyre** [comment]
Thank you, was this specified somewhere in the wiki? I don't know how I didn't just try that.

**Comment by YaLTeR** [comment]
Yeah, in the readme and here https://github.com/YaLTeR/niri/wiki/Important-Software#portals

**Comment by bthnakkurt** [comment]
hi i installed it but still there isnt that option

**Comment by YaLTeR** [comment]
Make sure you run pipewire before niri and have working portals and OBS with pipewire capture (OBS from Flathub has it).

**Comment by bthnakkurt** [comment]
i have gnome wlr gtk and normal portals installed
i also run pipewire with spawn-at-startup
interesting.
could it be because my distro doesnt have systemd

**Comment by YaLTeR** [comment]
> i also run pipewire with spawn-at-startup

That is too late, you need to run before. And remember to run `niri-session` if dinit or `niri --session` if no dinit or systemd

**Comment by bthnakkurt** [comment]
yes i run like that but no luck
