### ISSUE TITLE
block-out-from support for layer-shell surfaces

### ISSUE THREAD

**Issue by LunarEclipse363** [YaLTeR/niri#566]
I'm not very familiar with how this works on wayland, but I've been told that 
> mako is a wlr-layer-shell application which doesn't use xdg-toplevel surfaces. 
> xdg-toplevel surfaces (colloquially known as "a window") can have an app-id. Other types of Wayland surfaces do not have an app-id.

So if I understand correctly, it's currently impossible to exclude wlr-layer-shell applications from screen recording because they don't have windows with an app-id, so you can't apply window rules to them.

Maybe this could be solved by adding layer rules like how you can already add window rules in the config?

**Comment by YaLTeR** [comment]
Yeah, it is currently impossible. Maybe layer-rule would be needed, or maybe even client-rule if it's possible to reliably get the binary name of the client (might be).

**Comment by elkowar** [comment]
@YaLTeR we do have the namespace of the layershell surface, which in many cases could be enough. My current usecase would be to just block out notifications from screensharing. Mako's surfaces get the namespace `notifications`, so matching on that would be more than sufficient.

**Comment by YaLTeR** [comment]
I see, good point.

**Comment by YaLTeR** [comment]
Implemented in 1a0612cbfd0abee0796efa86470226686ae78f21.
