### ISSUE TITLE
unable to use screencast when running niri for first time

### ISSUE THREAD

**Issue by JimitSoni18** [YaLTeR/niri#571]
### System Information
void linux on thinkpad, glibc

* niri version: 0.1.7

* Distro: void linux, glibc

* GPU: intel integrated 

* CPU: i5 4200M

i have observed that when i run niri in a dbus session, using `dbus-run-session niri --session`, then start a browser and try screensharing, in google meet or discord or anywhere else, the gtk window picker does not open. here is an image after i left the google meeting saying it could not share screen:
![Screenshot from 2024-08-03 12-51-56](https://github.com/user-attachments/assets/d8dce7da-7c80-4a7c-9c91-e3e36e141380)

however, if i exit niri (pressing super+shift+e) then run command `niri` (not running in a session, and not using flag --session), then exit that again (pressing super+shift+e), and run niri in a dbus session again, using `dbus-run-session niri --session`, the screen casting starts working, and the gtk window picker appears this time. see the picture attached:
![Screenshot from 2024-08-03 12-55-12](https://github.com/user-attachments/assets/bdcdd8ba-c080-4325-b516-c7630471c634)

here are some spawn commands i run when i run niri, if it helps:
spawn-at-startup "pipewire"
spawn-at-startup "dunst"
spawn-at-startup "swww-daemon"
spawn-at-startup "swww img wallpapers.webp"
spawn-at-startup "eww" "open" "bar"

i thought that maybe niri requires pipewire running on startup to cast screen, so i tried pipewire before starting niri, but it did not work.

**Comment by YaLTeR** [comment]
You currently need to run pipewire before niri, spawn-at-startup is too late for that.

> i tried pipewire before starting niri, but it did not work

That's weird, it should work I think.

**Comment by JimitSoni18** [comment]
yeah i'll try again and see if it works

**Comment by JimitSoni18** [comment]
now i am able to use screencast, previously i was spawning pipewire directly in the shell using `nohup pipewire > /dev/null &`, now i an launching in a fish script, and it does seem to work.

i still think it is weird that it does not work when pipewire is spawned from the shell
