### ISSUE TITLE
Touchscreen input gets applied to wrong output/monitor

### ISSUE THREAD

**Issue by feathecutie** [YaLTeR/niri#574]
I have a laptop with a touchscreen display and use an external monitor as a secondary output.
When I use the touch screen on my laptop while there is no external monitor plugged in, everything works as expected, but as soon as I connect my second monitor, all touchscreen input gets applied to its output, no matter which output is currently focused.

This is the output of `niri msg outputs`:

```
Output "HDMI-A-1" (28_1_2 - HP E242 - HDMI-A-1)
  Current mode: 1920x1200 @ 59.950 Hz (preferred)
  Variable refresh rate: not supported
  Physical size: 520x320 mm
  Logical position: 0, 0
  Logical size: 1920x1200
  Scale: 1
  Transform: normal
  Available modes:
    1920x1200@59.950 (current, preferred)
    1920x1080@60.000
    1920x1080@60.000
    1920x1080@59.940
    1920x1080@50.000
    1920x1080@50.000
    1600x1200@60.000
    1680x1050@59.883
    1600x900@60.000
    1280x1024@60.020
    1440x900@59.901
    1280x800@59.910
    1280x720@60.000
    1280x720@60.000
    1280x720@59.940
    1280x720@50.000
    1280x720@50.000
    1024x768@60.004
    800x600@60.317
    720x576@50.000
    720x576@50.000
    720x480@60.000
    720x480@60.000
    720x480@59.940
    720x480@59.940
    720x480@59.940
    640x480@60.000
    640x480@59.940

Output "eDP-1" (11_24_6 - 22169 - eDP-1)
  Current mode: 1920x1080 @ 60.038 Hz (preferred)
  Variable refresh rate: not supported
  Physical size: 340x190 mm
  Logical position: 0, 1200
  Logical size: 1920x1080
  Scale: 1
  Transform: normal
  Available modes:
    1920x1080@60.038 (current, preferred)
    1920x1080@40.027
    1680x1050@60.038
    1280x1024@60.038
    1440x900@60.038
    1280x800@60.038
    1280x720@60.038
    1024x768@60.038
    800x600@60.038
    640x480@60.038
```

Note that this still happens after I changed my configuration to move the laptop screen (`eDP-1`) to logical position 0,0 and the second monitor below to 0,1080, though I haven't tested yet if this persists after restarting Niri.

EDIT: Even after restarting niri and setting the laptop screen to logical position 0,0 beforehand, the issue persists and all touch input is directed to the output of the external monitor.

### System Information

* niri version: niri unstable 2024-08-01 (commit 908c8eb42af7a24b3fe7961b9d52c104910edcf7)

* Distro: NixOS unstable/24.11

* GPU: Integrated graphics of CPU

* CPU: AMD Ryzen 7 5700U with Radeon Graphics

**Comment by YaLTeR** [comment]
There's currently no automatic mapping for touchscreens. I'm not sure whether it's possible (haven't looked much into it). So you have to set it manually:
```
input {
    touch {
        map-to-output "eDP-1"
    }
}
```

**Comment by feathecutie** [comment]
Good to know, thanks, I missed that in the docs. Automatic mapping for touchscreens would definitely be nice to have (especially if one ends up having multiple touchscreens in a setup), but this is a good workaround for now

**Comment by feathecutie** [comment]
I can't test it myself right now because I'm struggling to get a custom Niri to build and run with my development setup, but there is a [`output_name` method on Smithay input devices](https://smithay.github.io/smithay/input/struct.Device.html#method.output_name), which from my understanding does exactly what is needed here (indicate which output this input device belongs to, if any).
I'll try to test it out and potentially submit a patch for this sometime this week if I manage to get stuff to work, but I wanted to mention it here regardless in case you or anyone else wants to take a look at it.

**Comment by YaLTeR** [comment]
Thanks! I'll take a look

**Comment by YaLTeR** [comment]
Though, feel free to do it if I don't get to it first
