### ISSUE TITLE
Keybind repeat doesn't work for XF86Audio(Raise|Lower)Volume

### ISSUE THREAD

**Issue by ThatOneCalculator** [YaLTeR/niri#578]
### The problem

In my config, I have

```
	XF86AudioRaiseVolume  allow-when-locked=true { spawn "swayosd-client" "--output-volume=raise"; }
	XF86AudioLowerVolume  allow-when-locked=true { spawn "swayosd-client" "--output-volume=lower"; }
    XF86AudioMute         allow-when-locked=true { spawn "swayosd-client" "--output-volume=mute-toggle"; }
    XF86AudioMicMute      allow-when-locked=true { spawn "swayosd-client" "--input-volume=mute-toggle"; }
    XF86MonBrightnessUp   allow-when-locked=true { spawn "swayosd-client" "--brightness=raise"; }
    XF86MonBrightnessDown allow-when-locked=true { spawn "swayosd-client" "--brightness=lower"; }
 ```

The brightness raise/lower works as expected when holding the keys down, but I have to tap to repeat for the audio keys.

### System Information

* niri version: niri 0.1.7 (unknown commit)
** Built from `niri-git` (AUR) this morning

* Distro: Arch Linux

* GPU: Radeon 890M

* CPU: Ryzen 9 AI HX370

**Comment by ThatOneCalculator** [comment]
https://github.com/user-attachments/assets/18cc516b-2301-4dab-81b7-dbd8ae2638e8

**Comment by YaLTeR** [comment]
Idk, what if you bind the brightness command to the volume keys? Maybe it's a swayosd issue and you need a cooldown?

**Comment by ThatOneCalculator** [comment]
It's definitely a swayosd issue, since I can scroll on my waybar to do the same thing with bringing the audio up and down, and binding the brightness keys to the volume control commands works perfectly.

**Comment by ThatOneCalculator** [comment]
*not a. Whoops.

**Comment by YaLTeR** [comment]
> binding the brightness keys to the volume control commands works perfectly

That's very odd, are you sure nothing wrong is going with your volume keys then? Try `sudo libinput debug-events` and compare what happens when you hold those compared to brightness keys.

**Comment by ThatOneCalculator** [comment]
Yep, it's a problem with the keys. libinput shows the volume up/down keys as being held down, while the brightness keys rapidly repeat.

![image](https://github.com/user-attachments/assets/18eb93c6-c902-4988-b898-83f0037401a0)

**Comment by ThatOneCalculator** [comment]
Wow, I might be very stupid. I have `niri-git` on my desktop but `niri` on my laptop. :facepalm:

**Comment by YaLTeR** [comment]
That repeating is not niri's doing; so it just happened to work. The git niri should work for volume, too, using the niri repeat.

**Comment by ThatOneCalculator** [comment]
Yep. I thought I was running the latest git but I was running the latest release.

**Comment by ThatOneCalculator** [comment]
After a reboot, can confirm that it's working as expected on the latest git version. Sorry about that.
