### ISSUE TITLE
fcitx5 is not available on chromium wayland

### ISSUE THREAD

**Issue by BRS5672023** [YaLTeR/niri#583]
### System Information

* niri version: niri 0.1.7 (0.1.7-1-modified)

* Distro: Arch Linux

* GPU: AMD Radeon 780M

* CPU: AMD Ryzen 7 8845H

Fcitx5 is not available on chromium with the following flags
```
--use-gl=angle
--use-angle=vulkan
--enable-zero-copy
--ignore-gpu-blocklist
--enable-accelerated-video-decode
--enable-chrome-browser-cloud-management
--enable-features=RawDraw,CanvasOopRasterization,Vulkan,VulkanFromANGLE,DefaultANGLEVulkan,VaapiIgnoreDriverChecks,VaapiVideoEncoder,ScrollableTabStrip,OverlayScrollbar
#--disable-features=WaylandFractionalScaleV1
--video-capture-use-gpu-memory-buffer
--force-color-profile=display-p3-d65
--ozone-platform-hint=auto
#--enable-wayland-ime
--gtk-version=4
```
It seems that text_input_v1 is not supported so `--enable-wayland-ime` won't work here while `--gtk-version=4` does not work either. Even though I have installed gtk4.. I also checked that `--gtk-version=4` won't help on electron apps (with ozone wayland)..

That being said, it works flawlessly on firefox and kitty.

**Comment by YaLTeR** [comment]
According to this, Chromium recently added text input v3 support, so I guess it'll start working eventually: https://github.com/Smithay/smithay/issues/1447

**Comment by BRS5672023** [comment]
> According to this, Chromium recently added text input v3 support, so I guess it'll start working eventually: [Smithay/smithay#1447](https://github.com/Smithay/smithay/issues/1447)

Ok, I'm missing some information just reading the arch wiki page.. Should I keep this issue open then?

**Comment by YaLTeR** [comment]
No; either way it would be on Smithay side. But I think you just need to wait till some further Chromium release.

**Comment by BRS5672023** [comment]
I confirmed that fcitx5 works on chrome dev 129.0.6643.2, while the effective flags are `--enable-wayland-ime --wayland-text-input-version=3` rather than `--gtk-version=4`.

**Comment by YaLTeR** [comment]
Nice!
