### ISSUE TITLE
Niri --session on new tty, service breaks

### ISSUE THREAD

**Issue by fengints** [YaLTeR/niri#591]
### System Information

* niri version: 0.1.7-1

* Distro: Manjaro

* GPU: Integrated

* CPU:intel westmere

niri --session doesn't have services also services breaks on initial tty after restarting them
services location: .config/.../niri.service.wants

I don't have my own usecases right now, just found this bug.

Steps to reproduce

1. Login through dm manager
2. Open new niri --session in tty1 (it has also no services running)
3.  `systemctl --user restart x.service`

additional: services won't appear or able to restart on initial tty even if you kill tty1,
`systemctl --user daemon-reload` doesn't make it either

**Comment by YaLTeR** [comment]
You need the `niri-session` script to start the niri.service, just running `niri --session` does not start any systemd services.

**Comment by YaLTeR** [comment]
Feel free to reopen if I misunderstood something.

**Comment by fengints** [comment]
too much boilerplate, can i reload services started with `spawn-at-startup` ?

**Comment by YaLTeR** [comment]
If you start them with `systemd --user start`, sure

**Comment by fengints** [comment]
i don't want all this files and systemd stuff, just with 1 line of code `spawn-at-startup`

**Comment by fengints** [comment]
how do i restart the services i started with that way

**Comment by YaLTeR** [comment]
Just pkill and start again? All spawn-at-startup does is run the command at the earliest possible time

**Comment by fengints** [comment]
i thought there is some way in .config to start a service with `spawn-at-startup` and getting it into variable or smth. to use it later.

**Comment by fengints** [comment]
If there is no such option where can i have pid of my "app" i started with spawn-at-startup

**Comment by YaLTeR** [comment]
pidof name?
