### ISSUE TITLE
Walker doesn't get autofocused on load.

### ISSUE THREAD

**Issue by 0x006E** [YaLTeR/niri#596]
I'm not sure if this is a niri problem or not, hence I am cross posting the issue I've posted on the walker repository. When using walker (a runner) on niri, the keyboard does not focus on the output, even clicking on the popup does not focus it. Only If I click on the search input, it focuses. 

Related issue: https://github.com/abenz1267/walker/issues/107

### System Information

* niri version: niri unstable 2024-08-01 (commit 908c8eb42af7a24b3fe7961b9d52c104910edcf7)

* Distro: NixOS unstable

* GPU: Intel Alderlake Integrated Graphics and Nvidia 2050

* CPU:Intel i5-1240P

**Comment by YaLTeR** [comment]
I guess we figured it out in the linked issue
