### ISSUE TITLE
 Workspace, opening app at startup doesn't work

### ISSUE THREAD

**Issue by fengints** [YaLTeR/niri#598]
### System Information
Workspace, opening app at startup doesn't work

* niri version: 0.1.7-1

* Distro: Manjaro

* GPU: Integrated

* CPU:intel westmere

Docs here
https://github.com/YaLTeR/niri/wiki/Configuration:-Named-Workspaces

I have default column size 0.3 in layout.
Nemo and others are not opening on n workspace, 
if you open it at startup time manually it opens with 0.7 proportion but app itself doesn't open at startup, then after some time(actions? opening firefox in my case) it ignores the rule and if you open it manually again in the same workspace it opens with 0.3 proportion

```
//Top of the config file
workspace "n"
window-rule {
    match at-startup=true app-id="nemo"
    open-on-workspace "n"
    default-column-width { proportion 0.7; }
}
```

**Comment by YaLTeR** [comment]
`at-startup=true` does not make it so the app runs at startup. What it does, is it restricts the window rule to apply only during the first minute after niri startup.

What you're looking for is `spawn-at-startup`.

**Comment by fengints** [comment]
remove this line from the docs then
https://github.com/YaLTeR/niri/wiki/Configuration:-Named-Workspaces

![image](https://github.com/user-attachments/assets/297b2819-8345-4cdc-b008-d0998c28c9b1)

**Comment by fengints** [comment]
It should be different. 
//If you open Fractal it is going to open at the "chat" workspace.

adding some spawns are not excess there in the docs to make it more clear 
spawn "Fractal" after that lines

**Comment by YaLTeR** [comment]
I reworded it to:
```
// Open Fractal on the "chat" workspace, if it runs at niri startup.
```
