### ISSUE TITLE
Support HiDPI configuration

### ISSUE THREAD

**Issue by kchibisov** [YaLTeR/niri#6]
I'm pretty sure smithay just requires you to pass a scale around.

**Comment by YaLTeR** [comment]
Yeah, shouldn't be too difficult. I just hardcoded scale 1 everywhere so far since I had other things to worry about.

I guess this is blocked more on output configuration in general.

**Comment by YaLTeR** [comment]
Implemented integer scaling in https://github.com/YaLTeR/niri/commit/109668fa30bf65e56a2723ff29bcadc3e9a6e4ca. Some minor things are still TODO, i.e. I don't send output enter/leave to the pointer surface yet so it keeps using scale 1, also I don't use the new preferred_buffer_scale yet. But by and large it seems to work, even with screen recording.
