### ISSUE TITLE
Chromium ignores resize column animation

### ISSUE THREAD

**Issue by abdeoliveira** [YaLTeR/niri#600]
Pressing the default `mod+R` switches between presets column widths with a nice animation in all windows but Chromium. I bet it is a Chromium bug based on historical events.

### System Information

* niri 0.1.7 (unknown commit)

* Distro: Arch

* GPU: Intel WhiskeyLake-U GT2 [UHD Graphics 620] 

* CPU: Intel i7-8665U (8) @ 4.800GHz

**Comment by YaLTeR** [comment]
For me it works, actually. With running Chromium on Wayland.

I know it doesn't work for X11 clients running through xwayland-satellite though.
