### ISSUE TITLE
Black screen....

### ISSUE THREAD

**Issue by jokyv** [YaLTeR/niri#606]
Hello there!

When i run niri from Ly display manager i get black screen without able to run anything.
However i am able to log out when i hit MOD+SHIFT+E and ENTER (back to the display manager)

Other like GNOME runs without any problem on my machine.
When i run niri inside gnome like hit `niri` in the terminal niri runs without any problem.
However when i exit i see the following which i am not sure if it is any issue:

2024-08-17T13:47:18.633366Z  WARN niri::backend::winit: error binding renderer wl_display: None of the following EGL extensions is supported by the underlying EGL implementation, at least one is required: ["EGL_WL_bind_wayland_display"]

I also have tried the following inside my config file which also did not help:

`debug {
    render-drm-device "/dev/dri/renderD128"
}`

I had run niri in this machine in the past without any issue.
Recently i had to format the disk and install everything from the beginning but it seems niri does not want me anymore :(
Any ideas please?

### System Information

* niri version:  0.1.8-1
* Distro: Linux 6.10.5-arch1-1
* GPU: Nvidia RTX 2060 with Driver version 555.58.02
* CPU: AMD Ryzen™ 7 3700X

**Comment by YaLTeR** [comment]
Hello, do you have recent enough nvidia drivers and the modeset kernel flags and whatnot? https://github.com/YaLTeR/niri/wiki/Getting-Started#nvidia

Also which nvidia gpu is that?

**Comment by jokyv** [comment]
Hey thanks for the quick reply - actually that worked!

First of all Nvidia specs and driver version updated (original post)

I do feel a bit strange though as i do not remember implementing such changes in the first time i installed niri.
Nevertheless i am putting the steps i took here for future reference by anyone who has similar problem on Arch:

- Go to:
`sudo nano /etc/default/grub`
- Change line like below:
`GRUB_CMDLINE_LINUX_DEFAULT=quiet vdev.log_priority=3 nvidia-drm.modeset=1`
- Then run:
`sudo update-grub`
- Reboot

**Comment by YaLTeR** [comment]
Great, thanks for the steps!

**Comment by Ultra980** [comment]
I have the same issue on NixOS with the latest nvidia drivers and modesetting enabled. But I also have an intel iGPU

**Comment by Ultra980** [comment]
these are the logs:

```
[2m2024-10-02T16:52:58.342489Z[0m [32m INFO[0m [2mniri[0m[2m:[0m starting version stable 0.1.8
[2m2024-10-02T16:52:58.343742Z[0m [34mDEBUG[0m [2mniri_config[0m[2m:[0m loaded config from "/home/ultra/.config/niri/config.kdl"
[2m2024-10-02T16:52:58.805432Z[0m [32m INFO[0m [2mniri::backend::tty[0m[2m:[0m using as the render node: "/dev/dri/renderD128"
[2m2024-10-02T16:52:58.841554Z[0m [34mDEBUG[0m [2mniri::backend::tty[0m[2m:[0m device added: 57856 "/dev/dri/card0"
[2m2024-10-02T16:52:58.893556Z[0m [34mDEBUG[0m [2mniri::backend::tty[0m[2m:[0m device changed: 57856
[2m2024-10-02T16:52:58.894464Z[0m [34mDEBUG[0m [2mniri::backend::tty[0m[2m:[0m device added: 57857 "/dev/dri/card1"
did not find extension DRI_Mesa version 2
did not find extension DRI_IMAGE_DRIVER version 2
failed to bind extensions
did not find extension DRI_Mesa version 2
did not find extension DRI_IMAGE_DRIVER version 2
failed to bind extensions
did not find extension DRI_Mesa version 2
failed to bind extensions
[2m2024-10-02T16:52:59.637939Z[0m [33m WARN[0m [2mniri::backend::tty[0m[2m:[0m error adding device: No such file or directory (os error 2)
[2m2024-10-02T16:52:59.637975Z[0m [32m INFO[0m [2mniri[0m[2m:[0m listening on Wayland socket: wayland-1
[2m2024-10-02T16:52:59.637979Z[0m [32m INFO[0m [2mniri[0m[2m:[0m IPC listening on: /run/user/1000/niri.wayland-1.5266.sock
[2m2024-10-02T16:53:04.634749Z[0m [32m INFO[0m [2mniri::input[0m[2m:[0m quitting after confirming exit dialog
[2m2024-10-02T16:53:04.643254Z[0m [34mDEBUG[0m [2mniri::utils::watcher[0m[2m:[0m exiting watcher thread for /home/ultra/.config/niri/config.kdl


```

**Comment by YaLTeR** [comment]
This looks like the common NixOS Mesa version mismatch issue.

**Comment by Ultra980** [comment]
Should I make an issue on the flake's repo?
