### ISSUE TITLE
focus related or something i don't know what title shoud i use

### ISSUE THREAD

**Issue by r4hulrosh4n** [YaLTeR/niri#608]
When I use messaging apps like WhatsApp or Telegram and switch to a different workspace, I don’t get notifications for new messages in the previous workspace. This makes it look like I’m ignoring messages, even though I’m just busy in other workspaces and missing the notifications. I’m not sure if this is a bug or if there’s a way to fix it. Please help me.

**Comment by YaLTeR** [comment]
That kinda sounds like the app is mistaking the window activated state for the window keyboard focus, probably an application bug.

**Comment by YaLTeR** [comment]
Looks like it's a Chromium issue. It keeps the blinking cursor when it's activated but has no keyboard focus.
