### ISSUE TITLE
Zrythm app window does not properly get sized.

### ISSUE THREAD

**Issue by rempas** [YaLTeR/niri#609]
I did install [niri](https://aur.archlinux.org/packages/zrythm-git) and when I launch it and open a project, the window is sized in the top corner of the screen. Trying to fullscreen it, shows the animation, fullscreens it and then IMMEDIATELY, goes back to its previous size.

![Screenshot from 2024-08-18 18-39-08](https://github.com/user-attachments/assets/13279e86-d8be-4237-9039-e24aa4c3d05a)

### System Information

* niri version: niri 0.1.7 (v0.1.7-46-ge98d1ec)

* Distro: Artix Linux (dinit)

* GPU: AMD RX 560

* CPU: AMD Ryzen 5 2400G

**Comment by YaLTeR** [comment]
This is most likely a zrhythm bug. Maybe it tries to restore the window size or something.

**Comment by rempas** [comment]
> This is most likely a zrhythm bug. Maybe it tries to restore the window size or something.

Maybe. It should be noted that under [labwc](https://labwc.github.io/), it works without problems. Should I open an issue in Zrythm's repo?

**Comment by YaLTeR** [comment]
I guess. Check if any other GTK 4 apps have a similar issue?

**Comment by rempas** [comment]
> I guess. Check if any other GTK 4 apps have a similar issue?

I checked on (I think nautilus) and, it works as expected. I'll check more and I'll update.

**Comment by rempas** [comment]
easyeffects also works without problems. Do you know any other GTK4 apps? Epiphany won't run as I'm on Artix and it doesn't have Xwayland and Epiphany doesn't work on Wayland natively...

**Comment by YaLTeR** [comment]
Most things from here: https://circle.gnome.org/

**Comment by rempas** [comment]
Yep! I tried a few, and they seem to be working without problems. So, I suppose a GTK4 bug that has to do with a Wayland protocol that has a bug (or hasn't been implemented at all) on Niri and, only Zrythm seems to be using so far?

I don't know if all that sounds dumb, I'm just making assumptions in hopes to help 😅

**Comment by YaLTeR** [comment]
My guess is that there's some weird logic in zrhythm itself

**Comment by rempas** [comment]
Ok, I'll open a bug report there, and we'll see how that goes.
