### ISSUE TITLE
niri not compiling on musl, void linux

### ISSUE THREAD

**Issue by trolljoe** [YaLTeR/niri#614]
### System Information

* niri version: latest from github

* Distro: Void Linux musl

* GPU: AMD Mancer RX 550

* CPU: Intel I5 2450M

tried compiling niri on musl, but once it tries to compile niri(bin), i just get these notes:

```  = note: /usr/bin/ld: cannot find -lpangocairo-1.0: No such file or directory
          /usr/bin/ld: cannot find -lpango-1.0: No such file or directory
          /usr/bin/ld: cannot find -lharfbuzz: No such file or directory
          /usr/bin/ld: cannot find -lcairo: No such file or directory
          /usr/bin/ld: cannot find -lpango-1.0: No such file or directory
          /usr/bin/ld: cannot find -lharfbuzz: No such file or directory
          /usr/bin/ld: cannot find -lcairo-gobject: No such file or directory
          /usr/bin/ld: cannot find -lcairo: No such file or directory
          /usr/bin/ld: cannot find -lgbm: No such file or directory
          /usr/bin/ld: cannot find -lxkbcommon: No such file or directory
          /usr/bin/ld: cannot find -lseat: No such file or directory
          /usr/bin/ld: cannot find -linput: No such file or directory
          /usr/bin/ld: cannot find -lpixman-1: No such file or directory
          /usr/bin/ld: cannot find -lgbm: No such file or directory
          collect2: error: ld returned 1 exit status
```
i have all those dependecies installed, including their devel version. i'm not sure if this is an issue with musl. my build command was `RUST_BACKTRACE=full cargo build --no-default-features --features "dbus" --release --verbose`

**Comment by YaLTeR** [comment]
That's weird, looks pretty much as if you didn't have the devel versions installed.

**Comment by trolljoe** [comment]
yeah, double checked and they're all installed. i will try compiling after running `sudo ldconfig` to see if that changes anything.

**Comment by trolljoe** [comment]
> yeah, double checked and they're all installed. i will try compiling after running `sudo ldconfig` to see if that changes anything.

that did not seem to fix it. checked again and all packages are indeed installed. 
i ran `pkg-config --list-all` and this is my output:
[lol.txt](https://github.com/user-attachments/files/16686194/lol.txt)

for some reason (?) some libs actually do show up in pkg-config, but some don't. but all of the libs are failing, so i assume it isn't recognizing any

**Comment by YaLTeR** [comment]
Very strange

**Comment by trolljoe** [comment]
yeah, seems like it's a musl issue. i'm not sure if i can run niri off of distrobox

**Comment by YaLTeR** [comment]
Alright. Though, people did successfully build niri for void before. Not sure what they did exactly.

**Comment by trolljoe** [comment]
> Alright. Though, people did successfully build niri for void before. Not sure what they did exactly.

void has both musl and glibc, that's probably how

**Comment by trolljoe** [comment]
another update, i got it to build on musl using:

`RUSTFLAGS="-Ctarget-feature=-crt-static" RUST_BACKTRACE=full cargo build --no-default-features --features "dbus" --release --verbose`
