### ISSUE TITLE
Focus ring is _clamped_ to top/bottom when switching workspaces

### ISSUE THREAD

**Issue by kchibisov** [YaLTeR/niri#62]
During animation you can see the focus ring being clamped to monitor edge until you finish the switch, I'd expect it to be offscreen or not being showed at all given that we have 2 rings basically at the same time.

**Comment by YaLTeR** [comment]
The focus ring is kind of per-workspace, so it does make sense I think. Right now it corresponds exactly to the window active state, which is also maintained for windows on unfocused workspaces to avoid windows visually focusing/unfocusing on workspace switches.

**Comment by kchibisov** [comment]
The problem is not that it's visible, but that the bound is clamped and moves with window. So you just need to properly not render it.

**Comment by YaLTeR** [comment]
Hm, wait, what do you mean?

**Comment by kchibisov** [comment]
Hm, I think it actually planes are bugging? Because I don't see this in the recording or without a plane. I just see a border element when switching which I shouldn't see.

**Comment by kchibisov** [comment]
Or maybe my monitor, since it's clearly not there on a recording...

**Comment by YaLTeR** [comment]
Might be a damage tracking bug in Smithay. I certainly saw several of what looked like damage tracking bugs.

**Comment by YaLTeR** [comment]
Recordings and screenshots do not use damage or planes fwiw.

**Comment by kchibisov** [comment]
Hm, no, it's a monitor issue it has a frame where border is doubled so it looks like it's clamped.
