### ISSUE TITLE
binds are not processed for `wlr-virtual-keyboard` events

### ISSUE THREAD

**Issue by sodiboo** [YaLTeR/niri#631]
Whilst trying to use a software called lan-mouse, [I had to implement some protocols for it to work properly](https://github.com/YaLTeR/niri/pull/630). One protocol i *didn't* implement was `wlr-virtual-keyboard`. This one seems to be mostly implemented in Smithay, and niri's implementation basically boils down to delegating to Smithay. nonetheless, I haven't investigated the code for this and am not 100% confident that this is surely a Smithay bug. I've only tested it in niri.

You can reproduce the issue like so:

- Run my branch with the protocols needed by lan-mouse, on two computers
- Open lan-mouse on both, and connect them to one another.
- Move the mouse between them. Observe that keyboard focus moves with the mouse.
- Prepare both keyboards.
- Open `wev` on Computer A (which one is A or B is arbitrary)
- Press e.g. `Super+Up` on Computer A keyboard
- Notice that `wev` receives just a `Super` keypress. The `Up` is eaten by niri.
- Press the same sequence on Computer B keyboard (bridged by lan-mouse to Computer A using `wlr-keyboard-shortcuts-inhibit` on B and `wlr-virtual-keyboard` on A)
- Notice that `wev` receives `Super+Up`
- Try the same with e.g. `Super+T` and notice that in one case a terminal opens, and the other wev just receives the keypress.
- Move focus to Computer B
- Repeat the experiment
- Observe that the results are the same but flipped based on which keyboard was used. What matters is not the actual keyboard, but whether it's a "real" keyboard on this computer or one emulated with `wlr-virtual-keyboard`

### System Information

* niri version: #630

* Distro: NixOS 24.11 Vicuña

* GPU: AMD RX 7800 XT

* CPU: AMD Ryzen 5 7600XT

**Comment by YaLTeR** [comment]
Someone actually opened an issue for this before: https://github.com/YaLTeR/niri/issues/403

I haven't looked into it yet, not sure whether it is possible to catch those events from Smithay to handle them manually. Or maybe Smithay should send them through the compositor input handling? If so then virtual events should be somehow differentiated I guess so the compositor can ignore specific shortcuts from them?

**Comment by sodiboo** [comment]
Oh, i see! This is a duplicate issue then.
