### ISSUE TITLE
Incorrect positioning "Tab Hover Card Images" in Google Chrome browser

### ISSUE THREAD

**Issue by alexdev16** [YaLTeR/niri#639]
### System Information

* niri version: 0.1.8 (9063a5d)

* Distro: Fedora Linux 40 (Workstation Edition)

* GPU: Intel Corporation Alder Lake-P GT2 [Iris Xe Graphics]

* CPU: 12th Gen Intel(R) Core(TM) i7-12700H

 In Google Chrome browser when hovering over a tab, the tab card is not displayed under the tab:
https://github.com/user-attachments/assets/a833ca1a-c982-4dbc-b78c-1bf04118d789

**Comment by alexdev16** [comment]
After updating Google Chrome to version 130, the tab cards fell into place and are now displayed under the tabs.

**Comment by YaLTeR** [comment]
Nice, guess they fixed it.
