### ISSUE TITLE
fullscreen freezing xwayland window

### ISSUE THREAD

**Issue by zero64801** [YaLTeR/niri#643]
I tested only with steam but maybe happens with other apps aswell, when fullscreen steam games ( maybe happen with other apps aswell, didn't test ) the screen will freeze/lag without any sign of coming back I can switch to another tty even though it takes a while to do so. I looked through other closed issues which mentioned something equal/similliar /issues/559 which was marked as solved, the thing that fixed it for me now was disabling direct scanout like mentioned before. ( I'm running in a nvidia gpu/proprietary driver 550.78 )

### System Information

* niri version: 0.1.6

* Distro: NixOS 24.05

* GPU: RTX 3060 TI

* CPU: AMD Ryzen 7 5700x

**Comment by YaLTeR** [comment]
That sounds similar to that issue yeah. 

Could you provide niri output with smithay debug, and also maybe a drm debug log, as described in that issue?

**Comment by zero64801** [comment]
> That sounds similar to that issue yeah.
> 
> Could you provide niri output with smithay debug, and also maybe a drm debug log, as described in that issue?

Sorry, I was running niri 0.1.6 , updated to 0.1.8 and everything is fixed/working without disabling direct-scanout.

**Comment by YaLTeR** [comment]
Alright, that probably was that issue then.
