### ISSUE TITLE
Niri does not work on FreeBSD 14.1

### ISSUE THREAD

**Issue by rempas** [YaLTeR/niri#649]
Niri does not work on FreeBSD 14.1. I launch it, the sceen stays black for some seconds. Then, the monitor brings a "no signal" message and then, the PC reboots on its owm.

### System Information

* niri version: niri 0.1.8 (unknown commit)

* Distro: FreeBSD 14.1-Release p3

* GPU:  AMD RX 560

* CPU: Ryzen 5 2400G

**Comment by YaLTeR** [comment]
Please post the niri output.

**Comment by rempas** [comment]
> Please post the niri output.

No output. The screen goes black and I can't see anything. I'm try to redirect the output to a file and tell you if it's successful written.

But, I'll do it in a while because I'm busy now.

**Comment by micielski** [comment]
Does it only happen with Niri or something like Sway works fine?
Try uninstalling `drm-515-kmod` and instead install `drm-510-kmod`.
I had a similar problem on FreeBSD with RX 570 and it wasn't specific to Niri only

**Comment by rempas** [comment]
> Does it only happen with Niri or something like Sway works fine? Try uninstalling `drm-515-kmod` and instead install `drm-510-kmod`. I had a similar problem on FreeBSD with RX 570 and it wasn't specific to Niri only

XFCE and Niri don't work. Mate and Labwc work

Let me try what you said.

**Comment by rempas** [comment]
> Please post the niri output.

Here's the output:

![IMG_20240904_213515](https://github.com/user-attachments/assets/4885d584-315e-41cf-ac5a-d922327b8b08)

Btw, one time, it randomly worked! Then when I rebooted, it didn't worked again 😔

**Comment by YaLTeR** [comment]
That output looks like everything is working from niri side.

**Comment by rempas** [comment]
@YaLTeR Yeah, you're right! Everything works from Niri's side! It was like @micielski said in the end. Installing the other kmod package makes everything work! I will probably open an issue in the FreeBSD team as the DRM for 5.10 is super old....

Thanks a lot everyone!
