### ISSUE TITLE
Mouse input on games running on Xwayland is not working correctly. 

### ISSUE THREAD

**Issue by k1logr4m** [YaLTeR/niri#654]
I've managed to launch games under Xwayland by following the rootless instructions on the wiki. However, I'm having issues with input. It seems like there's input on some parts of the window, but none on other parts. Here's what happens when I launch Minetest (FOSS Minecraft clone):

https://github.com/user-attachments/assets/b80931ea-eeae-4544-9908-34d3742cf592

On other games like OXTO, I can't move the in-game cursor around the whole window. Instead, the cursor collides with an invisible border:

https://github.com/user-attachments/assets/27887137-734d-4db3-8456-3bbda1e46d41

Same thing happens when I fullscreen with mod+shift+f. Also, I can't follow rootful instructions for Xwayland. This is the terminal output when I do step 1:
```
_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
(EE) 
Fatal server error:
(EE) Cannot establish any listening sockets - Make sure an X server isn't already running(EE)
```
Therefore, I can't spawn a black window.

### System Information

* niri version: niri 0.1.8 (unknown commit)

* Distro: EndeavourOS
* Kernel version: 6.10.8-arch1-1

* GPU: Nvidia RTX 3060Ti
* GPU Driver: nvidia-open-dkms 560.35.03-3

* CPU: AMD Ryzen 5 3600

**Comment by YaLTeR** [comment]
> It seems like there's input on some parts of the window, but none on other parts.

Could you check `niri msg outputs` if any of your outputs have negative logical position? 

> I can't follow rootful instructions for Xwayland

You need to either kill the rootless Xwayland, or tell the rootful one to use a different x11 display. It complains that the display is already in use

**Comment by k1logr4m** [comment]
> Could you check niri msg outputs if any of your outputs have negative logical position?
```
Output "DP-2" (12_24_6 - VG278 - DP-2)
  Current mode: 1920x1080 @ 144.001 Hz
  Variable refresh rate: supported, disabled
  Physical size: 600x340 mm
  Logical position: 1280, 0
  Logical size: 1920x1080
  Scale: 1
  Transform: normal
  Available modes:
    1920x1080@60.000 (preferred)
    1920x1080@144.001 (current)
    1920x1080@119.982
    1920x1080@99.930
    1920x1080@84.905
    1920x1080@59.939
    1920x1080@50.000
    1680x1050@59.954
    1280x1024@75.025
    1280x1024@60.020
    1440x900@59.887
    1280x960@60.000
    1280x800@59.810
    1152x864@75.000
    1280x720@60.000
    1280x720@59.943
    1280x720@50.000
    1024x768@75.029
    1024x768@70.069
    1024x768@60.004
    800x600@75.000
    800x600@72.188
    800x600@60.317
    800x600@56.250
    720x576@50.000
    720x480@59.940
    640x480@75.000
    640x480@59.940
    640x480@59.929
```

> You need to either kill the rootless Xwayland, or tell the rootful one to use a different x11 display. It complains that the display is already in use

I'll try that, thank you.

**Comment by k1logr4m** [comment]
I made sure xwayland-satellite wasn't running but I still can't do rootful. Also did `export DISPLAY=:0`, `export DISPLAY=:1`, `export DISPLAY=:2` before running Xwayland. Unless, that's not how I change displays?

**Comment by YaLTeR** [comment]
It isn't (that's the client side); it's something like `Xwayland :1`

**Comment by k1logr4m** [comment]
> It isn't (that's the client side); it's something like Xwayland :1


You're right! I successfully launched OXTO game rootful and there's no input issues. Looks a bit stretched but I think it's due to the bare bones i3 config. Although I'd like to eventually do rootless xwayland, but I understand that there's no actual support for it.

**Comment by YaLTeR** [comment]
I think the input issues are not on niri side, but on the rootless Xwayland that you're using side.

**Comment by k1logr4m** [comment]
You're probably right. It looks like this might be an issue with xwayland-satellite and has nothing to do with Niri. I'll close this issue then, since input works fine everywhere except inside xwayland-satellite's own compositor. Many thanks for helping me out with getting rootful method working btw.
