### ISSUE TITLE
xwayland-satellite doesn't appear to work with niri

### ISSUE THREAD

**Issue by jjramsey** [YaLTeR/niri#659]
I tried following the directions here: https://github.com/YaLTeR/niri/wiki/Xwayland

I have the following section in "$HOME/.config/nir/config.kdl":

```
environment {
    DISPLAY ":0"
    QT_QPA_PLATFORMTHEME "qt6ct"
}
```

Niri is launched with that config. I then launch a terminal (qterminal, to be precise).

I run "xwayland-satellite &" in that terminal and get the following output:

```
 2024-09-08T16:49:55.144Z INFO  xwayland_process > _XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
 2024-09-08T16:49:55.144Z INFO  xwayland_process > _XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
 2024-09-08T16:49:55.223Z INFO  xwayland_satellite > Connected to Xwayland on :1
 2024-09-08T16:49:55.227Z INFO  xwayland_process   > The XKEYBOARD keymap compiler (xkbcomp) reports:
 2024-09-08T16:49:55.228Z INFO  xwayland_process   > > Warning:          Unsupported maximum keycode 708, clipping.
 2024-09-08T16:49:55.228Z INFO  xwayland_process   > >                   X11 cannot support keycodes above 255.
 2024-09-08T16:49:55.228Z INFO  xwayland_process   > > Warning:          Could not resolve keysym XF86KbdInputAssistPrevgrou
 2024-09-08T16:49:55.228Z INFO  xwayland_process   > > Warning:          Could not resolve keysym XF86KbdInputAssistNextgrou
 2024-09-08T16:49:55.228Z INFO  xwayland_process   > Errors from xkbcomp are not fatal to the X server
```

The `SocketCreateListener() failed` message is suspicious. That said, I then run xterm from the same terminal (as a test) and get the following results:

```
Authorization required, but no authorization protocol specified

xterm: Xt error: Can't open display: :0
```

There's probably some kind of permissions issue, but I don't really know where to start.

Interestingly enough, `xwayland-run -- xterm` does work, though it gets me the following warning messages:

```
_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Unsupported maximum keycode 708, clipping.
>                   X11 cannot support keycodes above 255.
> Warning:          Could not resolve keysym XF86KbdInputAssistPrevgrou
> Warning:          Could not resolve keysym XF86KbdInputAssistNextgrou
Errors from xkbcomp are not fatal to the X server
xterm: cannot load font "-misc-fixed-medium-r-semicondensed--13-120-75-75-c-60-iso10646-1"
```

In any event, it looks like the documentation for using xwayland-satellite with niri is incomplete.

### System Information

* niri version: niri 0.1.8 (unknown commit)

* Distro: Arch Linux

* GPU: AMD Radeon RX 7800 XT

* CPU: Intel Core i5-12400

**Comment by YaLTeR** [comment]
What if you don't have the environment DISPLAY?

**Comment by FreeFull** [comment]
The xwayland-satellite output says it's running on :1, but you have DISPLAY set to :0 in your niri config. You can pass in a specific display number to xwayland-satellite to make sure it matches up with your niri config

**Comment by jjramsey** [comment]
If `DISPLAY` isn't set, then `xwayland-satellite` still sets it to "`:1`". However, running `env DISPLAY=:1 xterm` does work, as does having both `spawn-at-startup "xwayland-satellite" in the config and `DISPLAY` set to `:1` in the `environment` section of the config works.

Looks like what needs to be fixed is the documentation in https://github.com/YaLTeR/niri/wiki/Xwayland, rather than niri itself.

**Comment by cyuria** [comment]
While I agree the niri docs *could* maybe be more fleshed out, I think just a link to the xwayland satellite docs would be enough. Xwayland satellite isn't part of niri, so I see no reason why niri should document it.

The current documentation mentions almost everything you might want to know with regards to running xwayland satellite. The only thing that isn't mentioned is putting it into `spawn-at-startup`, which people seem to have figured out themselves pretty easily.

**Comment by jjramsey** [comment]
> While I agree the niri docs _could_ maybe be more fleshed out, I think just a link to the xwayland satellite docs would be enough.

Unfortunately, the documentation for xwayland-satellite is somewhat sparse, especially when it comes to setting the `DISPLAY` variable. The usage section of its README says, "Run xwayland-satellite. You can specify an X display to use (i.e. `:12`)," but it doesn't say *how* to specify it. The only way to figure that out right now is to run `xwayland-satellite -help` and decipher the usage message.

Furthermore, and something more connected to Niri, the documentation seems to imply that xwayland-satellite defaults to using "`:0`" for the value of the `DISPLAY` variable, since there's no indication of how xwayland-satellite is informed of its value. The docs just say to run xwayland-satellite, and always use "`:0`" as the example `DISPLAY` value.

What I would recommend is that the Niri documentation say something like this:

> run xwayland-satellite with a command line such as the following
> ```
> xwayland-satellite :12
> ```
> where "`:12`" is your choice for the value of the `DISPLAY` variable (and could be something other than "`:12`" if desired). Now you can start X11 applications on the X11 DISPLAY that it provides:
> ```
> env DISPLAY=:12 flatpak run com.valvesoftware.Steam
> ```

That would be good enough without getting into the weeds of the xwayland-satellite user interface.

**Comment by YaLTeR** [comment]
Maybe you have some other `xwayland-run` in spawn-at-startup that takes up the :0 display?

**Comment by YaLTeR** [comment]
Clarified it on the wiki: https://github.com/YaLTeR/niri/commit/087a50a19c87175bc6c2a3b7ddc886f98f26f7c4

**Comment by jjramsey** [comment]
> Maybe you have some other `xwayland-run` in spawn-at-startup that takes up the :0 display?

For the record, no, but apparently, the SDDM that runs on my system uses X11, and that probably takes the :0 display.

**Comment by YaLTeR** [comment]
Right, that would explain it. I use GDM which runs on Wayland, and even when it doesn't, it runs as a separate user, so the socket doesn't conflict (IIUC).
