### ISSUE TITLE
Publish on crates.io to allow "cargo install niri"

### ISSUE THREAD

**Issue by hardBSDk** [YaLTeR/niri#68]

**Comment by YaLTeR** [comment]
While this is a valid thing you can do, it's not really how you want to install a Wayland compositor. You need not just the binary, but the session and desktop files installed in the correct system folders, so niri shows up in your login manager. `cargo install` cannot do that.

**Comment by YaLTeR** [comment]
It would, yeah. Honestly I'm thinking more about versioning. Since there's no release and updating a crate every commit sounds tedious and like a bad idea.

Although now that a considerable amount of stuff is implemented maybe I should tag an alpha version and put that up as a crate or something.

**Comment by YaLTeR** [comment]
Hm, it seems that things published on crates.io cannot use git dependencies, so this will have to wait until the next Smithay release.

**Comment by friedow** [comment]
Hey, I'm maintaining [centerpiece](https://github.com/friedow/centerpiece). Centerpiece is a pluggable desktop launcher and I would love to build a plugin for niri which shows open windows and lets you switch to them. Therefore, I'd like to use the niri-ipc crate to talk to niri. It would be really nice to get this published to crates.io so I we can depend on it :).

**Comment by YaLTeR** [comment]
I guess I could publish niri-ipc, it doesn't depend on Smithay. Maybe with next niri release.

**Comment by friedow** [comment]
That would be awesome! I'll prepare everything on centerpiece side until then :).

**Comment by YaLTeR** [comment]
niri-ipc is now on crates.io: https://crates.io/crates/niri-ipc

I'll close this issue since it's not actionable unless Smithay makes a stable release.
