### ISSUE TITLE
Niri goes to black screen after exit and relog

### ISSUE THREAD

**Issue by jamesonBradfield** [YaLTeR/niri#689]
After Exiting niri with quit action, will be taken back to lightdm. and relogging gives me a black screen that looks like a terminal but I can't input anything, have to reboot to relog.

### System Information

* niri version: niri 0.1.9 (unknown commit)

* Distro: Arch Linux

* GPU: AMD 6700 xt

* CPU: AMD Ryzen 5 5600G

**Comment by KoshulaDora** [comment]
#684 And this seems to be linked, we are both using ryzen cpu and amd gpu as well.

**Comment by YaLTeR** [comment]
Please paste the niri output when an unsuccessful login occurs: `journalctl --user-unit=niri -b`

**Comment by jamesonBradfield** [comment]
I figured out, it had something to do with lightdm. I've switched to Ly and everything seems to work fine. I no longer have lightdm on my system. I can reinstall it and we can track this bug down.

**Comment by YaLTeR** [comment]
Well I'll close this I guess, if someone has more info feel free to post
