### ISSUE TITLE
cannot set envirinment variables

### ISSUE THREAD

**Issue by zimbipw** [YaLTeR/niri#692]
I want the following env variables in my config file:
environment {
     CLUTTER_BACKEND {wayland}
     GDK_BACKEND {wayland,x11}                                                                                                                                                           
     QT_STYLE_OVERRIDE {adwaita}
     QT_AUTO_SCREEN_SCALE_FACTOR {1}
     QT_QPA_PLATFORM {wayland}
     QT_SCALE_FACTOR {1}
     QT_WAYLAND_DISABLE_WINDOWDECORATION {1}
     QT_WAYLAND_DECORATION {adwaita}
 }  

However I get error message like this:
snippet line 9:     CLUTTER_BACKEND {wayland}
    label at line 9, column 29: unexpected token

### System Information

* niri version: niri -V
niri 0.1.9 (unknown commit)

* Distro: Arch

* GPU: AMD Renoir

* CPU: AMD Ryzen 7 4800H with Radeon Graphics

**Comment by YaLTeR** [comment]
You don't need the inner {}. It should be quotes instead.
```
environment {
    CLUTTER_BACKEND "wayland"
}
```
