### ISSUE TITLE
Strange behavior about screan casting and xwayland file picker

### ISSUE THREAD

**Issue by cbjx** [YaLTeR/niri#693]
I'm using sddm as display manager, xwayland-satellite with b962a0fd commit for xwayland apps, and when i log into niri, xwayland apps (I tested with vesktop) can't open file picker.
But somehow I can fix this by log off, log in to any other wm/de (I tried with Hyprland and Leftwm), log off again and log in to niri. Now vesktop can open file picker, but I can't do screen casting. (obs pipewire capture option is gone and screen share on vesktop does nothing)

The only log i saw is "Sep 29 00:12:06 cbjx-pc xdg-desktop-por[192324]: Delegated FileChooser call failed: The name is not activatable" from xdg-desktop-portal-gnome, when xwayland apps fail to open file picker.

### System Information

* niri version: niri 0.1.9 (unknown commit)

* Distro: Arch Linux

* GPU: GTX 1660 super

* CPU: intel i5-10400f

**Comment by YaLTeR** [comment]
GNOME 47 now uses nautilus as file chooser. You need to install nautilus to get it working.
