### ISSUE TITLE
Terminal image previews via sixel are borked

### ISSUE THREAD

**Issue by masroof-maindak** [YaLTeR/niri#699]
All programs that use terminal image previews - [lf](https://github.com/gokcehan/lf) and [spotify_player](https://github.com/aome510/spotify-player) in my case - are almost unusable. The images randomly start flickering, or don't update, or update into existence for one nanosecond before reverting to the last shown image. I should mention: the same behaviour is NOT present in River, but IS present in cosmic.

https://github.com/user-attachments/assets/68a05446-84a8-4f4b-8e1b-669d6179988d

### System Information

* niri version: 0.1.9

* Distro: Arch Linux

* GPU: Intel integrated graphics

* CPU: Intel i5-4278U

**Comment by YaLTeR** [comment]
Hey, 

> IS present in cosmic

In this case you should report this issue to Smithay. It's either a terminal bug or a Smithay bug.

**Comment by masroof-maindak** [comment]
> Hey,
> 
> > IS present in cosmic
> 
> In this case you should report this issue to Smithay. It's either a terminal bug or a Smithay bug.

I'm unaware of any other Wayland terminals that implement sixel and there's a much higher chance it's a Smithay bug since it's not present in River, but I'll see if I can confirm my theory first.

I'll report wherever's suitable, thanks for the input.
