### ISSUE TITLE
File picker won't show up on selected applications: a dbus issue?

### ISSUE THREAD

**Issue by abdeoliveira** [YaLTeR/niri#702]
Filepicker won't work in some apps unless the application is started with dbus-launch. Examples are Chromium and webplotdigitizer.

After login-logout in Hyprland and then login on niri, the problem disappears. On the other hand, I can't screen share anymore. 

### System Information

* niri version: niri 0.1.9 (unknown commit)
* Distro: Arch
* GPU: Intel WhiskeyLake-U GT2
* CPU: Intel i7-8665U

**Comment by YaLTeR** [comment]
Uhh huh? I thought that systemd should already start a d-bus session because it uses d-bus extensively.

**Comment by jjramsey** [comment]
> Filepicker for example won't work on niri unless the application is started with dbus-launch.

Could you describe the steps that you used that fail to launch "Filepicker" (whatever that is) on Niri but work on Hyprland?

I use both SDDM and Arch, so I might be able to at least reproduce your problem. (FWIW, I do use Workrave via an [Sfwbar applet](https://github.com/rcaelers/workrave/tree/main/contrib/waybar-yambar-poss-other-applets/), and that relies on D-Bus to work.)

**Comment by abdeoliveira** [comment]
Thank you for your time on this. After opened this issue I see the problem is a bit more... involving. 

You can reproduce the problem like this:

1. After reboot, login into niri through SDDM (or just run niri-session from tty).
2. Open gmail in Chromium (I realized Firefox is not affected)
3. Start to compose an email and click in the attach button. It should open a Filepicker, but it doesn't.

Other program affected  is the not-so-popular [webplotdigitizer](https://aur.archlinux.org/packages/webplotdigitizer-bin). In case you decide to test it:

1. run xwayland-satellite
2. open webplotdigitizer and go to File > Load Image(s) > Choose File(s). Again, Filepicker should appear but it refuses to show up.

Still is niri, if you `dbus-launch chromium` or `dbus-launch webplotdigitizer` the Filepicker bug is gone.

On Hyprland, none of the aforementioned Filepicker problems happen. 

Finnaly, and interestingly, after login-and-logout Hyprland if you comeback to niri, the Filepicker bug is gone. Everything works as expected without the need of `dbus-launch`.

**Comment by abdeoliveira** [comment]
> I can't reproduce your problem. 

What did you try exactly?

>What's your output from running `pacman -Q | grep xdg-desktop-portal`?

xdg-desktop-portal 1.18.4-1
xdg-desktop-portal-gnome 47.1-1
xdg-desktop-portal-gtk 1.15.1-2

**Comment by jjramsey** [comment]
> What did you try exactly?

I tried opening webplotdigitizer from a terminal and doing "File > Load Image(s) > Choose File(s)". My file picker dialog shows up.

**Comment by abdeoliveira** [comment]
It seems it is a specific problem with my niri install. I gave up on debugging this and just applied a dirty workaround, launching webplotdigitizer trough dbus-launch. Also, switched from Chrome to Firefox.

**Comment by LCarmi** [comment]
I can confirm the issue happening on my side as well.
Accessing to https://ps.uci.edu/~franklin/doc/file_upload.html and trying to upload a file fails in Google Chrome because no dialog is open. No issue on Firefox.
It similarly happens with VScode, where no dialog is open (for example the `Open file...` one)

In both cases, launching with `dbus-launch` restores the expected behavior.

System Information:
Distro: Arch
Niri Version: niri 0.1.9-1
Running `pacman -Q | grep xdg-desktop-portal` gives the same results as @abdeoliveira

**Comment by abdeoliveira** [comment]
I'm reopening this issue since this is definitely not an isolated problem on my side as per @LCarmi feedback. I would like to also add my filepicker dialog opens in Thunar (not sure if this is important). 

Note this bug also happens in a live session on Fedora with niri fresh installed from COPR, as I stated before. 

Finally, I suspect `webplotdigitizer` runs inside a chrome-sandbox (which may narrows the issue as niri-crrome interaction). I would like to know if VScode is also containerized. 

![screenshot-2024 10 03_07 35 32](https://github.com/user-attachments/assets/906099ec-0a7e-435b-bc04-01bc2965c3a6)

**Comment by LCarmi** [comment]
I have done some extra experiments. The same issues happen in sway and GNOME. In GNOME, launching through the dbus does not open chrome but works with vscode even if the opened dialog is frozen.  In sway, there dbus-launch fixes the dialog popup.

Maybe some common wayland library is broken in Arch repos?

**Comment by abdeoliveira** [comment]
I don't think this is an Arch repo problem thing, since this issue is reproducible in Fedora.

**Comment by MauroGuida** [comment]
I've also encountered an issue with the file picker not opening any window when trying to save (or pick) something in both Firefox and Chrome.

I start Niri with `niri-session` from [greetd](https://git.sr.ht/~kennylevinsen/greetd).

I've resolved the issue with the following workaround:

`~/.config/xdg-desktop-portal/niri-portals.conf`
```
[preferred]
default=gnome;gtk;

org.freedesktop.impl.portal.FileChooser=gtk; # <---- THIS fixes the file picker issue

org.freedesktop.impl.portal.Screenshot=wlr; # <---- THIS fixes an issue that I have with eyedropper on Niri

org.freedesktop.impl.portal.ScreenCast=gnome;
org.freedesktop.impl.portal.Background=gnome; # <---- THIS fixes SyncThingy background permission issue

org.freedesktop.impl.portal.Secret=gnome-keyring;
```

What this does is instruct `xdg-desktop-portal` to use the GTK file chooser implementation instead of the GNOME implementation on Niri. For some reason, the GNOME implementation fails to start on my system. You can find the error message by running: `systemctl --user status xdg-desktop-portal.service`

**Comment by FreeFull** [comment]
The GNOME implementation requires that you have Nautilus installed, perhaps that's why?

**Comment by MauroGuida** [comment]
> The GNOME implementation requires that you have Nautilus installed, perhaps that's why?

Yes, that was the issue. With `nautilus` installed, the GNOME file picker works. On Arch, `nautilus` [is not marked](https://archlinux.org/packages/extra/x86_64/xdg-desktop-portal-gnome/) as an optional dependency for `xdg-desktop-portal-gnome`, although `evince` is marked for print previews, but `nautilus` isn't listed for the file picker...

**Comment by abdeoliveira** [comment]
@MauroGuida I can confirm that installing nautilus solves the issue. Unfortunately the workaround  `~/.config/xdg-desktop-portal/niri-portals.conf` didn't work for me.

**Comment by MauroGuida** [comment]
> @MauroGuida and @FreeFull I can confirm that installing nautilus solves the issue. Unfortunately the workaround `~/.config/xdg-desktop-portal/niri-portals.conf` didn't work for me.

In order for `xdg-desktop-portal` to apply the changes in `~/.config/xdg-desktop-portal/niri-portals.conf`, you either need to reboot or, preferably, restart `xdg-desktop-portal` by running:
`systemctl --user restart xdg-desktop-portal.service`
Anyway, the problem was with `nautilus`, so it’s resolved thanks to @FreeFull. I believe it's best not to modify the preferred portals, unless absolutely necessary, to avoid introducing other unwanted issues that could be difficult to track down in the future.

**Comment by abdeoliveira** [comment]
This worked for me (after reboot):

```
oliveira@arch:~$ cat ~/.config/xdg-desktop-portal/niri-portals.conf 
[preferred]
org.freedesktop.impl.portal.FileChooser=kde
 ```

**Comment by abdeoliveira** [comment]
> > @MauroGuida and @FreeFull I can confirm that installing nautilus solves the issue. Unfortunately the workaround `~/.config/xdg-desktop-portal/niri-portals.conf` didn't work for me.
> 
> In order for `xdg-desktop-portal` to apply the changes in `~/.config/xdg-desktop-portal/niri-portals.conf`, you either need to reboot or, preferably, restart `xdg-desktop-portal` by running: `systemctl --user restart xdg-desktop-portal.service` Anyway, the problem was with `nautilus`, so it’s resolved thanks to @FreeFull. I believe it's best not to modify the preferred portals, unless absolutely necessary, to avoid introducing other unwanted issues that could be difficult to track down in the future.

Yes, yes, yes, you are right: `org.freedesktop.impl.portal.FileChooser=gtk` solves the issue after restarting `xdg-desktop-portal`.

**Comment by YaLTeR** [comment]
When doing changes to niri-portals.conf, remember to leave ScreenCast (and optionally Screenshot, and in the future also some others will be needed like RemoteDesktop) to gnome:
```
org.freedesktop.impl.portal.ScreenCast=gnome;
org.freedesktop.impl.portal.Screenshot=gnome;
org.freedesktop.impl.portal.RemoteDesktop=gnome;
```
Since niri only works with xdp-gnome for these.

**Comment by abdeoliveira** [comment]
I would like to add that implementing the `org.freedesktop.impl.portal.FileChooser=gtk` workaround breaks screen sharing on both both Firefox and Chromium (tested on Google Meet).

**Comment by MauroGuida** [comment]
> I would like to add that implementing the `org.freedesktop.impl.portal.FileChooser=gtk` workaround breaks screen sharing on both both Firefox and Chromium (tested on Google Meet).

Have you removed `default=gnome;gtk;` from `niri-portals.conf`? If so, please try adding it back, or at least include the following in `niri-portals.conf`:
```
org.freedesktop.impl.portal.ScreenCast=gnome;
org.freedesktop.impl.portal.Screenshot=gnome;
```

**Comment by abdeoliveira** [comment]
@MauroGuida, right. My bad. You and YaLTer stated it and I completely missed those variables. Thanks.
