### ISSUE TITLE
Swayidle doesn't work when started with spawn-on-startup

### ISSUE THREAD

**Issue by stepanzak** [YaLTeR/niri#707]
Hi, I have a weird issue with swayidle. I have this line at my niri.kdl:
`spawn-at-startup "swayidle" "-w" "before-sleep" "'swaylock -f'"`
I can see the process in Btop:
![Swayidle in Btop](https://github.com/user-attachments/assets/336f865f-4a23-4370-9b8e-8d06ea4ba23e)
The problem is that it does nothing. When I close the laptop lid or put the system to sleep with `systemctl suspend`, it doesn't invoke swaylock.
When I run `pkill swayidle` however, and then run the same swayidle comand from a terminal:
`swayidle -w before-sleep 'swaylock -f'`
It works!
It invokes swaylock before sleep using any method mentioned above.

PS: I remember some time ago having the same problem with some program enabling numlock. It would work from a terminal, but not from niri config. I can't recall it's name sadly...

### System Information

* niri version: niri 0.1.9 (unknown commit)

* Distro: EndeavourOS

* GPU: Internal + Some old Nvidia Quadro something, can search for it but I don't think it's related

* CPU: intel CORE i7 vPro

**Comment by YaLTeR** [comment]
Hey, you don't need the extra single quotes around the command since niri already passes it as a single argument. Try: 

```
spawn-at-startup "swayidle" "-w" "before-sleep" "swaylock -f"
```

**Comment by stepanzak** [comment]
That was it, thanks a lot!
