### ISSUE TITLE
XWayland coredumps on FreeBSD 14.1-RELEASE

### ISSUE THREAD

**Issue by tulilirockz** [YaLTeR/niri#722]
For some reason Xwayland just coredumps on a failed assertion when running niri on FreeBSD 14.1 with drm-515-kmod, absolutely no idea what causes it tho. Doesnt seem to happen on Sway

```
❯ Xwayland
Assertion failed: (dev->size == sizeof(dev_t)), function xwl_dmabuf_feedback_main_device, file ../hw/xwayland/xwayland-dmabuf.c, line 475.
(EE) 
Fatal server error:
(EE) Caught signal 6 (Abort trap). Server aborting
(EE)
``` 

### System Information

* niri version: 0.1.9 (unknown commit) 
    - Im using the LATEST port branch, and as of the time of writing, theyre fetching these dependency versions: https://cgit.freebsd.org/ports/tree/x11-wm/niri/distinfo 

* Distro: FreeBSD 14.1-RELEASE-p5 with PkgBase 

* APU: AMD Ryzen 3 2200g with Vega 8 integrated graphics
- More system information at: https://bsd-hardware.info/?probe=cb476ab6ab

**Comment by YaLTeR** [comment]
Uhhhhhh? No idea honestly

**Comment by jbeich** [comment]
Works fine on -CURRENT with drm-515-kmod but I'm using 5.15-lts-focal branch per [bug 274770](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=274770).

**Comment by jbeich** [comment]
Nevermind. After switching to vanilla drm-515-kmod I still can't reproduce on my Intel iGPU. 5.15-lts-focal does have some DMABUF regression fixes but on Intel it mainly helps to avoid green tint with Vulkan Video and VA-API.

Trying other drm-kmod versions like drm-61-kmod is still a good idea, especially on AMD GPUs.

**Comment by tulilirockz** [comment]
After testing out a ton of stuff, apparently nesting niri on.. niri... makes it work! - its just the tty backend that doesnt like Xwayland for some reason

**Comment by YaLTeR** [comment]
Does this still happen?

**Comment by YaLTeR** [comment]
Feel free to reopen with more info if you think this is a niri issue.

**Comment by tulilirockz** [comment]
Hello! Sorry for not answering earlier, I completely forgot about it. This is most likely an upstream issue. I tried manually updating `smithay` and tons of dependencies but even then it didnt fix the issue. Nowadays I dont use FreeBSD anymore so I cant really do anything about this issue anymore

**Comment by esad** [comment]
I am just testing FreeBSD 14.2 and this is still happening with Xwayland as well as e.g. cage when invoked from niri

**Comment by JetpackJackson** [comment]
I'm also having this issue on FreeBSD 14.3. Is there any workaround I can do?
