### ISSUE TITLE
integer scaling causes blurring

### ISSUE THREAD

**Issue by alicealysia** [YaLTeR/niri#746]
Currently using 2 monitors, the second has a scaling setting of 2.0 and the display appears blurry as though it's rendering at half resolution and being upscaled.

**Comment by YaLTeR** [comment]
Could you attach a screenshot?

**Comment by alicealysia** [comment]
Got home from work, decided to do some extra troubleshooting to make sure this isn't being caused by something else.
Turns out I was right to do that.
Here's nemo with scaling enabled rendering to my xwayland-satellite display:
![image](https://github.com/user-attachments/assets/4a01509e-d4e0-4af0-b5ce-351bbb613ade)

and here it is rendering to... not... that
![image](https://github.com/user-attachments/assets/ea43497f-e7f9-4af5-b13f-e0dc88c741a1)

This looks an awful lot like setting the scale using xrandr doesn't it?

For anyone else who runs into this problem, this thread is the issue in xwayland-satellite
https://github.com/Supreeeme/xwayland-satellite/issues/11

sorry for wasting your time YaLTeR!
