### ISSUE TITLE
Alpine Linux fails to initialize TTY backend.

### ISSUE THREAD

**Issue by Blendi-Goose** [YaLTeR/niri#766]
On Alpine Linux, niri fails to initialize the TTY backend, giving a "Function not implemented (os error 38)" error.
Here's the full output from niri:
```
2024-10-29T10:33:50.345589Z  INFO niri: starting version 0.1.9 (unknown commit)
2024-10-29T10:33:50.361589Z DEBUG niri_config: loaded config from "/home/blendi/.config/niri/config.kdl"
thread 'main' panicked at src/main.rs:183:6:
called `Result::unwrap()` on an `Err` value: error initializing the TTY backend

Caused by:
    0: Error creating a session. This might mean that you're trying to run niri on a TTY that is already busy, for example if you're running this inside tmux that had been originally started on a different TTY
    1: Failed to open session: Function not implemented (os error 38)
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### System Information

* niri version: niri 0.1.9 (unknown commit)

* Distro: Alpine Linux edge

* GPU: AMD Radeon RX 7900 XTX

* CPU: AMD Ryzen 9 7950X

**Comment by YaLTeR** [comment]
Seems your TTY is busy for some reason. Do you use any display manager, or how do you run niri?

**Comment by Blendi-Goose** [comment]
> Do you use any display manager, or how do you run niri?

I tried using SDDM to run niri, but that just gives a black screen and kicks me back to SDDM. This output is from running it in a seperate TTY, which had nothing else going on (as far as I know).

**Comment by YaLTeR** [comment]
Well, I'm not sure unfortunately

**Comment by Blendi-Goose** [comment]
I've done a debug build from source, so I could enable RUST_TRACEBACK=full, in case it happens to be useful.

Here's the output: [new-niri-output.txt](https://github.com/user-attachments/files/17557790/new-niri-output.txt)

**Comment by YaLTeR** [comment]
Unfortunately it is not useful. It says everything in the error right there (I typed that error message). I don't know what causes it in your case. Pretty sure people got niri working on Alpine in the past

**Comment by Blendi-Goose** [comment]
Update: It can actually run through SDDM if I modify the niri.desktop file in /usr/share/wayland-sessions.
Apparently, the default niri.desktop just runs niri-session (which won't work on OpenRC, and isn't even installed by the alpine package)

**Comment by YaLTeR** [comment]
I see. That is an Alpine packaging issue then.
