### ISSUE TITLE
Pointer Left / Right click are confused

### ISSUE THREAD

**Issue by geryzhydrox** [YaLTeR/niri#767]
### System Information

* niri version: 

* Distro: 

* GPU: 

* CPU:

**Comment by geryzhydrox** [comment]
I don't really have any libinput settings in sway at all, but the `input` section in niri's `config.kdl` does include trackpoint, tablet, and touch which i don't have in `sway`'s config... In any case, the issue somehow fixed itself without me really doing anything. So much for NixOS's promise of purity...

**Comment by YaLTeR** [comment]
Huh. Well, alright then. Maybe some hardware bug?
