### ISSUE TITLE
KDE Connect presentation remote pointer is broken

### ISSUE THREAD

**Issue by LunarEclipse363** [YaLTeR/niri#770]
So basically, the expected behavior is that you get an overlay over your screen that has the funny shiny circle you control by moving your phone around while holding a button.

On niri this instead creates a new black fullscreen window, by tweaking window rules I only got it to be transparent and sit besides other windows.

https://github.com/user-attachments/assets/763226d5-add7-48b8-a13a-3ec6bb70a769

I'm guessing this is a clash of "kdeconnect assumes it can overlay a normal window above everything else" versus niri's "windows can never overlap eachother" paradigm.

### System Information

* niri version: `niri 0.1.9 (unknown commit)`

* Distro: Arch Linux

* GPU: (integrated)

* CPU: AMD Ryzen 7 4800H

**Comment by YaLTeR** [comment]
Well, KDE connect cannot assume this on Wayland, not only on niri but on other compositors too. In fact, on Wayland the compositor is expected to render a fullscreen window on black background with no other windows visible. And a maximized window cannot render above the GNOME Shell top bar for example, or above top-layer layer-shell panels on other compositors.

Instead, KDE connect could use a fullscreen layer-shell surface on the overlay layer which would do very close to what it wants.

**Comment by Malix-Labs** [comment]
Is it related to that issue: https://bugs.kde.org/show_bug.cgi?id=452669 ?

**Comment by pgattic** [comment]
For anyone coming across this, here is something that mostly fixes it for me:

```kdl
window-rule {
  match app-id=r"org.kde.kdeconnect.daemon" // ID of presentation pointer overlay
  open-floating true
  open-fullscreen false
  default-floating-position x=0 y=0 relative-to="top-left"

  // Adjust these to your monitor's resolution
  min-width 1920
  min-height 1080

  // Optionally customize opacity of pointer
  // opacity 1.0

  tiled-state true

  focus-ring {
    off
  }
  border {
    off
  }
  shadow {
    off
  }
  draw-border-with-background false
}
```

Shoutout to this [Reddit post](https://www.reddit.com/r/hyprland/comments/1d0f2ou/to_the_one_person_using_kde_connect_presentation/), from which I derived the niri equivalent.

The only issues are that this still doesn't display over a fullscreen application (basically its main purpose, unfortunately). If the KDE Connect devs can make the pointer overlay ask the compositor to display it on the overlay layer, that should fix the issue.

**Comment by BahAilime** [comment]
I added 

```kdl
background-effect {
    blur false
}
```

so it does not blur the entire screen

**Comment by mohamed-AARAB** [comment]
This issue helped me and this is more general fix; the width and height are not hardcoded:
```kdl
window-rule {
  match app-id=r"org.kde.kdeconnect.daemon" // ID of presentation pointer overlay
  open-floating true
  open-fullscreen false
  default-floating-position x=0 y=0 relative-to="top-left"

  // Optionally customize opacity of pointer
  // opacity 1.0

  // Scale dynamically to 100% of the monitor's dimensions
  default-column-width { proportion 1.0; }
  default-window-height { proportion 1.0; }

  tiled-state true

  focus-ring {
    off
  }
  border {
    off
  }
  shadow {
    off
  }
  draw-border-with-background false
  background-effect {
    blur false
  }
}
```
