### ISSUE TITLE
memory leaking

### ISSUE THREAD

**Issue by xcccdjsn** [YaLTeR/niri#772]
I have used swaylock, hyprlock and gtklock, but all of them will increment memory amount every time after using it.

### System Information

* niri version: niri 0.1.9 (unknown commit)

* Distro: Arch Linux x86_64

* GPU: Intel UHD Graphics G4 @ 1.25 GHz [Integrated]

* CPU: 11th Gen Intel(R) Core(TM) i3-1115G4 (4) @ 4.10 GHz

**Comment by YaLTeR** [comment]
Could it be some mesa GPU objects that will get garbage collected later?

I guess we need to check with the Tracy memory profiler or something to see if there are any leaks on the Rust side.

**Comment by YaLTeR** [comment]
I added Tracy profiling. I can see the Rust memory increase every time I run swaylock. It's a bit hard to tell what gets leaked. Seems like some surface data might have a ref cycle?

**Comment by YaLTeR** [comment]
Found it: https://github.com/YaLTeR/niri/issues/772

**Comment by xcccdjsn** [comment]
I have not test other window manager.

I found other application also can cause memory leaking, especially kitty. Spawn multiple kitty in short time, and then close them quickly. I did it many times resulting in lot of memory leaking.

This is my result screenshots.
I also got memory usage from btop which derived same result.

![IMG20241102193500](https://github.com/user-attachments/assets/aacc9730-f2fd-4d96-a2f9-7f9239284132)
![IMG20241102193516](https://github.com/user-attachments/assets/f78f4474-81a6-482b-80cc-eec2e6f85133)
![IMG20241102193539](https://github.com/user-attachments/assets/79203cb7-062d-4c0e-9d05-9a5b226c065b)

**Comment by GallowsDove** [comment]
This is exactly what I've been rambling about in matrix room a few weeks ago. Recommend looking at my smithay issue and other linked issues (especially the nvidia one)

https://github.com/Smithay/smithay/issues/1562

**Comment by YaLTeR** [comment]
Screen locker leak should be fixed with 600cffb009cde7ed3e04b9f53365ad56cf2d6d6b

**Comment by YaLTeR** [comment]
@xcccdjsn could you please test cosmic-comp for your kitty issue? I believe it's not niri specific and there's already a Smithay issue open.
