### ISSUE TITLE
Feature: Add Nix Flake Support

### ISSUE THREAD

**Issue by billksun** [YaLTeR/niri#78]
Adding Nix Flake support can help interested contributors more easily get into hacking the code base by providing a reproducible build and development environment.

This also opens the door to creating Nix packages, and modules for NixOS and Home-Manager.

Here is the PR associated with this task: #77.

**Comment by kchibisov** [comment]
See https://github.com/YaLTeR/niri/issues/5

**Comment by billksun** [comment]
Hmm, so this flake doesn't add Nix package manager support. Not in the sense like adding AUR or ebuild support gives you packages for Arch and Gentoo Linux. This flake doesn't produce any installable packages.

As stated it just adds support for reproducible builds and a reproducible development environment, so developers don't have to hunt for system dependencies before getting started.

In essence, this flake just adds Nix developer tooling support. In its current state, this flake allows you to run:

```
nix build
./result/bin/niri
```

And Niri will be built and executed. There's no need to manually install the correct system packages beforehand. You don't even have to have `cargo` installed. There's also no need to use `steam-run` on NixOS like in the mentioned issue. System76's flake uses `libglvnd` as a runtime dependency to help dispatch OpenGL calls, making Niri aware of Nix's copy of `libEGL`, thus this flake is more self-contained.

While developers can maintain their own forks of Niri with their own Nix flake config, that sort of defeats the purpose of using Nix, a big part of which is to save developers from recreating their own dev environments from scratch. This reduces the burden of maintainers having to handle issues like #67 and #70, and is the main draw for me as a developer to use Nix. Just need to figure out the dependencies once, and all developers _can_ benefit from it.

I think a big selling point for me when a project supports Nix flakes, is that I can quickly build and run a project without making system changes to my OS they may be tricky to revert. So personally, I am much more likely to be engaged in project that has Nix support. Niri, however, is a big exception! I am so excited about Niri and its implementation of the scrollable tiling manager concept, that was willing to go through the dependency hunting myself and get it working.

What I am offering here, is to codify that process so other interested parties can have an easier time than me when trying out Niri. And hopefully, seeing by Niri in action themselves will bring about more engagement with the project.

However, I do understand that developer tooling can be a highly personal choice, and I do respect the maintainers' preference on how they want a project managed.

So if this is not wanted, just let me know, I'll close up the ticket and PR. No hard feelings :grin:.

**Comment by YaLTeR** [comment]
Hey, so @sodiboo made a flake here: https://github.com/sodiboo/niri-flake

I think it's better this way if it lives in a repo controlled by someone actually using nix. I linked that from the README.

**Comment by YaLTeR** [comment]
Development Nix flake was also added to the niri repository in #77.
