### ISSUE TITLE
Pressing Mod key moves focus to left column

### ISSUE THREAD

**Issue by k1logr4m** [YaLTeR/niri#790]
I was playing Titanfall 2 and then prompt saying "Press space to continue" appeared. It didn't respond the first time I pressed it, so I repeatedly kept pressing space and enter waiting for it to respond and then I was taken away from the game to the very first column. Then I tried to go back to the game window by pressing "mod+L" but it seems like just by pressing the mod key, focus moves backwards. It has the same effect as pressing "mod+h", which moves focus to left column in my config.

What I've tried to fix the problem:
1. Exit Niri and relaunch from display manager.
2. Reboot PC.
3. Reconnect keyboard.
4. Swap to a different keyboard.
5. Use default config.kdl from github.
6. Try a different USB port.
7. Reinstall Niri (Ran yay -S niri).

In addition, I switched to Hyprland and River to check if I have a similar issue when I press the mod key, but nothing weird happens. On both of those compositors mod+h is bound to resizing the window.

### System Information

* niri version: 
0.1.9

* Distro: 
EndeavourOS

* GPU: 
Nvidia RTX 3060Ti

* CPU:
AMD Ryzen 5 3600

**Comment by k1logr4m** [comment]
I found out what the problem was. My mouse's scroll wheel was busted and was giving input repeatedly. There was no issue with Niri.

**Comment by YaLTeR** [comment]
Heh, alright
