### ISSUE TITLE
Gentoo dependency: virtual/rust is masked(legacy Rust ebuild are no longer maintained)

### ISSUE THREAD

**Issue by EssenSea** [YaLTeR/niri#792]
One of the following masked packages is required to complete your request:
- virtual/rust-1.82.0::gentoo (masked by: package.mask)
/usr/portage/profiles/package.mask:
# Matt Jolly <kangie@gentoo.org> (2024-11-09)
# The legacy Rust ebuilds are no longer maintained and have been
# replaced by the new slotted Rust. Removal in 30 days.

- virtual/rust-1.81.0-r1::gentoo (masked by: package.mask)
- virtual/rust-1.80.1::gentoo (masked by: package.mask)
- virtual/rust-1.79.0::gentoo (masked by: package.mask)
- virtual/rust-1.77.1::gentoo (masked by: package.mask)

(dependency required by "gui-wm/niri-0.1.9::guru" [ebuild])

### System Information

* niri version: 0.1.9

* Distro: gentoo

* GPU: nvidia-1060

* CPU:intel-8750H

**Comment by YaLTeR** [comment]
Why is this a niri issue? I don't maintain any of those packages.

**Comment by EssenSea** [comment]
> Why is this a niri issue? I don't maintain any of those packages.

Sorry for bad format and ambiguous information in above. Open Issue here is due to niri's ebuild( gentoo's package manager system, determined how to compile niri's src. And as you know , gentoo need to nearly compile any thing in local mechine) file, just like SPEC in fedora's rpm system. Here are from niri-0.1.9.ebuild.

(dependency required by "gui-wm/niri-0.1.9::guru" [ebuild])

BDEPEND="
	>=virtual/rust-1.77.0
	screencast? ( $(llvm_gen_dep 'sys-devel/clang:${LLVM_SLOT}') )
"
I'm not sure could we reduce this line and niri could be compile and work normal. Or how to modify this line.

**Comment by YaLTeR** [comment]
I don't maintain the niri ebuild. It is not stored in this repository. I can't help you with that unfortunately.

**Comment by EssenSea** [comment]
> I don't maintain the niri ebuild. It is not stored in this repository. I can't help you with that unfortunately.

Thx for reply,  Just migrated to Gentoo about a week , and not familar with compiling process ... :(.  I NEED NIRI !!! :(...

**Comment by YaLTeR** [comment]
Maybe @kchibisov could help, idk

**Comment by kchibisov** [comment]
You should bring it to your package manager and not here.

@EssenSea just drop the `virtual/rust` line and set the `RUST_MIN_VERSION="1.77.0"` if you're updating the ebuild.

But in any way, you can always _unmask_ packages while they are being _updated_.

**Comment by EssenSea** [comment]
Thx for help!  @kchibisov @YaLTeR. 

virtual/rust will be removal nealy soon( metioned in emerge -avuDU @world process) . And all version of dev-lang/rust and dev-lang/rust-bin are masked, I'm not sure whether these will be removed in nearly future. It seems like that some kind of crazy things are happening. I'm thinking should I migrate again(fk!). :(

**Comment by kchibisov** [comment]
You clearly don't understand what basically everything means. Gentoo just slotted the rust, means that you can have multiple installed side by side, so `virtual/rust` is no longer needed, since `virtual` packages are packages where you can specify what package you use for rust, but it's no longer needed, since you have slots.

niri's ebuild just wasn't updated, since it's in guru, so guru maintainers should update it themselves.

**Comment by EssenSea** [comment]
> You clearly don't understand what basically everything means. 

To be honestly, that's right. I was shocked by all version of dev-lang/rust are masked by offical.  And I know nothing about what does this mean......

Thx for disabuse.  Truly a newbie in computer science, and it will be sustaining for a long term since my major was some traditional engineering.

**Comment by kchibisov** [comment]
![image](https://github.com/user-attachments/assets/a4995427-acf2-4540-bc55-66eaf188f37a)

masked versions use old ones, which will be soon removed `-r100` are new versions of them which are stable as you can see.

Just wait a bit and niri in guru will get updated to a new rust eclass, which merged like yesterday, probably it'll take a few days though. Just bad timing and a fact that niri is not in a main repository, so it was not automatically updated like all other rust packages in gentoo.

**Comment by EssenSea** [comment]
> masked versions use old ones, which will be soon removed `-r100` are new versions of them which are stable as you can see.

I was misunderstanding these, thanks
