### ISSUE TITLE
Scrolling not working with 0.10 

### ISSUE THREAD

**Issue by Kassiee** [YaLTeR/niri#801]
I installed Niri from arch linux extra-testing repository and for some reason, without any errors, scrolling on any regular program doesn't work anymore, yet scrolling works when used for niri's binds.

Again, no errors shown, and I've got no idea how to troubleshoot this

**Comment by YaLTeR** [comment]
Yeah, this is the regression mentioned in the release notes. I'll tag a hotfix release soon that fixes it.

**Comment by YaLTeR** [comment]
https://github.com/YaLTeR/niri/releases/tag/v0.1.10.1
