### ISSUE TITLE
Cursor animation stops when not moving cursor

### ISSUE THREAD

**Issue by phuhl** [YaLTeR/niri#804]
Extremely minor bug, but thought, I'd report it anyways. When the cursor is moving and there is an animated cursor (e.g. loading indicator), than everything is well, but when the cursor is not moved, the animation does not progress. It seems that animation frames are only requested on cursor repaint 

### System Information

* niri version: niri 0.1.9 (v0.1.9-62-g0866990)

* Distro: xps13plus 6.11.6-arch1-1 

* GPU: Intel Corporation Alder Lake-P GT2 [Iris Xe Graphics]

* CPU: 12th Gen Intel(R) Core(TM) i7-1260P

**Comment by YaLTeR** [comment]
What application is that?

**Comment by phuhl** [comment]
In my case, if I remember correctly, GTK-based Emacs

**Comment by YaLTeR** [comment]
As far as I know, GTK 3 and 4 draws the cursor client-side. When I run the cursors demo from `gtk3-demo`, the spinning cursor updates correctly. So I'm not sure there's a niri issue here?
