### ISSUE TITLE
Cursor theme changes everywhere except the background and the terminal

### ISSUE THREAD

**Issue by Ouxyre** [YaLTeR/niri#806]
### System Information

* niri version: niri 0.1.10-1 (unknown commit), also on niri 0.1.9

* Distro: Arch Linux

* GPU: Intel HD Graphics 

* CPU: Intel m3-6Y30 (4) 

Exactly like the title says, the cursor theme stays as breeze when moved on the terminal or background. It looks like it has to do with niri as even when I take a screenshot, the cursor also changes to breeze instead of the one I downloaded (Graphite light)

I set the cursor theme to be graphite in the niri config, as well as index.theme in the /usr/share/icons directory

What must I do to fix this?

**Comment by YaLTeR** [comment]
In the background, the terminal and the screenshot UI the cursor is drawn by niri. Elsewhere it's drawn by the apps themselves. Niri sets `$XCURSOR_THEME`, then it's up to the apps to follow this.

**Comment by YaLTeR** [comment]
I guess in this case, niri fails to load the cursor but the apps follow it fine?

**Comment by Ouxyre** [comment]
Yes, exactly.

**Comment by YaLTeR** [comment]
Well, niri passes the theme name that you set in the config straight to [the xcursor crate](https://lib.rs/crates/xcursor). So if it's not a misspelling of some sort, then that would be an xcursor crate issue.

**Comment by Ouxyre** [comment]
Sorry for wasting your time, I got it to work. Seems like the folder name of the cursors is used rather than the actual cursor name.

**Comment by YaLTeR** [comment]
Good to know
