### ISSUE TITLE
Window becomes out of the screen when window-resizing actions are applied

### ISSUE THREAD

**Issue by Paul-Eau** [YaLTeR/niri#822]
When using the set-column-width or set-window-height actions with `+` or `-` modifiers with only one active window, executing these actions can resize the window to the point where it extends beyond the screen, making part of the content invisible.

### System Information

* niri version: niri 0.1.10-1
* Distro: Arch Linux
* GPU: iGPU intel HD620
* CPU: Intel i5-7300u

**Comment by YaLTeR** [comment]
Hello, this is intended. It is the only way to capture screenshots bigger than the screen at the moment, before floating windows are implemented.
