### ISSUE TITLE
Can't perform privileged UI actions

### ISSUE THREAD

**Issue by BlackCherryCat** [YaLTeR/niri#824]
Can't perform privileged UI actions like mount a drive with nautilus, I have gnome polkit installed

![Screenshot from 2024-11-23 01-05-21](https://github.com/user-attachments/assets/d91886e9-65e9-45df-881f-6cf1107862cd)

### System Information

* niri version: niri 0.1.10-1

* Distro: Arch Linux

* GPU: RTX 4060 Ti 16GB

* CPU: AMD Ryzen 5 7600

**Comment by YaLTeR** [comment]
This isn't really related to niri. You need to make sure you have a working polkit agent installed *and* enabled in systemd.

**Comment by BlackCherryCat** [comment]
okay, I managed to do that, but it's normal that the auth windows doesnt apply correctly the gtk theming?
![Screenshot from 2024-11-23 17-39-24](https://github.com/user-attachments/assets/4c564898-bfb5-482a-bee2-a4185ac7741c)

**Comment by YaLTeR** [comment]
I don't know unfortunately.
