### ISSUE TITLE
Window doesn't get focused if the pointer lands on it after switching workspaces with `focus-follows-mouse` enabled

### ISSUE THREAD

**Issue by Endg4meZer0** [YaLTeR/niri#829]
The title mostly depicts it all: window does not get focused if the pointer lands on it after switching workspaces in any way with `focus-follows-mouse` enabled in the configuration.

https://github.com/user-attachments/assets/b13a7c26-b7a3-4481-ba6a-c6f75c7bebde

### System Information

* niri version: 0.1.10 (v0.1.10-15-g7de752e)

* Distro: Arch (kernel: 6.11.9-zen1-1-zen)

* GPU: AMD RX 570

* CPU: AMD Ryzen 5 2600

**Comment by Endg4meZer0** [comment]
Hold up, I've just noticed a commit that works on that issue? I'm gonna update and see if it's still there

**Comment by YaLTeR** [comment]
See the discussion here: https://github.com/YaLTeR/niri/discussions/717#discussioncomment-10857616

**Comment by Endg4meZer0** [comment]
Oh, I see. A solid argument, although I really like the idea of triggering `focus-follows-mouse` for wheel and touch bindings and wish that it would one day come true. Thank you!
