### ISSUE TITLE
Dragging Firefox tab to second monitor pops out tab to same monitor

### ISSUE THREAD

**Issue by ThatOneCalculator** [YaLTeR/niri#857]
### System Information

* niri version: niri 0.1.10 (v0.1.10-13-g1a0612c)
* Mozilla Firefox 133.0
* Distro: Arch Linux x86_64
* GPU: AMD Radeon 890M
* CPU: AMD Ryzen 9 AI 370

### The issue

As you can see in this video, attempting to drag the tab to the same monitor works, but attempting to drag it to the second monitor pops it out on the same monitor, and I need to Super + click-and-drag to get it onto the second monitor.

[2024-12-10 11-19-58.webm](https://github.com/user-attachments/assets/c0ead22f-deb6-4d98-9d40-186cbcdcc563)

**Comment by YaLTeR** [comment]
Hi, it'll be fixed in the next release (commit https://github.com/YaLTeR/niri/commit/c239937fac836f308311eff5f5d5fc5262c6eb55 fixed it).
