### ISSUE TITLE
Keyboard inputs not being read for `rofi-wayland`

### ISSUE THREAD

**Issue by cgeoga** [YaLTeR/niri#864]
Hello,

Please excuse me if I have missed this issue in a previous discussion, and thank you in advance for your time and for the wonderful window manager.  

While using `rofi-wayland` on vanilla Arch linux, keyboard inputs aren't registered. Launching the program in a terminal and then mashing keys that should be input to rofi shows the (terminal) output
```
libnkutils-bondings-critical **: [time]: nk_bindings_seat_handle_key: assertion 'self->keymap != NULL' failed
```
Looking at `rofi-wayland`, it hasn't been updated for a long time in the official repos. Moreover, when I launch the same program in sway, my keyboard inputs do get read and everything works as expected. So I am wondering if there is any chance the issue could be with niri (?). 

In case it is relevant, here is the exact program that I run:
```
#!/bin/bash

dir="$(fd ${1:-.} -i --type d '/home' | rofi -threads 0 -theme Monokai -dmenu -sort -sorting-method fzf -i -p "find")"
foot bash -c "cd '$dir' && bash"
```

Thanks again for everything!

### System Information

* niri version: niri 0.1.10-1

* Distro: Arch

* GPU:  NA

* CPU: Intel i7-1260p

**Comment by YaLTeR** [comment]
Hey, this has been fixed a while ago on an unreleased version of rofi-wayland. https://github.com/davatorium/rofi/discussions/2008
