### ISSUE TITLE
Stylus input becomes uncentered with second monitor attached

### ISSUE THREAD

**Issue by ThatOneCalculator** [YaLTeR/niri#867]
[VID_20241213_205427766.webm](https://github.com/user-attachments/assets/ffc4fb16-23f1-4a62-8b22-998545e60c11)

### System Information

* niri version: niri 0.1.10 (v0.1.10-55-g82e3024) (built from latest git today)
* Distro: Arch Linux x86_64
* GPU: AMD Radeon 890M
* CPU: AMD Ryzen 9 AI 370
* Truncated output of `niri msg outputs` with both monitors attached:

```
Output "GIGA-BYTE TECHNOLOGY CO., LTD. M34WQ 0x000000C9" (DP-2)
  Current mode: 3440x1440 @ 144.001 Hz (preferred)
  Variable refresh rate: supported, disabled
  Physical size: 800x340 mm
  Logical position: 2058, 0
  Logical size: 3440x1440
  Scale: 1
  Transform: normal
  Available modes:
    3440x1440@144.001 (current, preferred)
    3440x1440@59.973 (preferred)
    #...

Output "Samsung Display Corp. ATNA60CL10-0  Unknown" (eDP-1)
  Current mode: 2880x1800 @ 120.000 Hz (preferred)
  Variable refresh rate: supported, disabled
  Physical size: 340x220 mm
  Logical position: 0, 0
  Logical size: 2057x1285
  Scale: 1.4
  Transform: normal
  Available modes:
    2880x1800@120.000 (current, preferred)
    2880x1800@60.001 (preferred)
    #...
```

**Comment by YaLTeR** [comment]
Hey, you need to manually map tablet to the right output: https://github.com/YaLTeR/niri/wiki/Configuration:-Input#pointing-devices

I'm not sure if there's a way to make it map automatically to the correct output.

**Comment by ThatOneCalculator** [comment]
Ah, my bad for not RTFM :sweat_smile: 
As outlined in the wiki, this solved it perfectly for me :)

```
input {
    tablet {
        map-to-output "eDP-1"
    }

    touch {
        map-to-output "eDP-1"
    }
}
```
