### ISSUE TITLE
MPV is visually dropping frames

### ISSUE THREAD

**Issue by aslpavel** [YaLTeR/niri#870]
[MPV](https://mpv.io/) is visually dropping frame (it is not really dropping them on the player side) this is not happening for the same file if I ran it in sway for example. I'm not really sure how to debug it, if you need more information please let me know

### System Information

* niri version: `niri 0.1.10-1 (unknown commit)`

* Distro: `Arch Linux`

* GPU: `AMD 780M` as part of `AMD Ryzen 7 7840U` 

* CPU: `AMD Ryzen 7 7840U`

**Comment by YaLTeR** [comment]
Well I'm not sure what I can do with this little info. I use mpv myself, works fine here.

**Comment by aslpavel** [comment]
I have recorded tracy profile, never used this tool before so I have no idea where to look 
[niri.zip](https://github.com/user-attachments/files/18137572/niri.zip)

**Comment by aslpavel** [comment]
I have just enabled `variable-refresh-rate` and I do not know if it fixed things or just hid the problem. But visually it looks much smoother, I have created another tracy profiler for comparison 
[niri-1.zip](https://github.com/user-attachments/files/18137684/niri-1.zip)

**Comment by YaLTeR** [comment]
Thanks for the Tracy recordings.

> I have recorded tracy profile, never used this tool before so I have no idea where to look

There's barely any niri work visible here. I suspect the problem is in how mpv schedules frames on your setup.

> I have just enabled variable-refresh-rate and I do not know if it fixed things or just hid the problem.

This also hints at that.

Maybe you have a weird mpv display-resample setting? I suggest turning it off, especially when watching with VRR.

> BTW tracy GUI crashes on niri but runs on sway:

For me it sometimes crashes like that on niri, but most of the time it runs fine. I suspect there's a race condition in Tracy itself and mesa.

**Comment by YaLTeR** [comment]
Any update on this? Did you have a chance to check the mpv display-resample setting?

**Comment by aslpavel** [comment]
I have just tried it, and actually with default `video-sync` which is equal to `audio` it lags with `variable-refresh-rate` off. If I set it to `display-resample` it seems like it fixes the problem or makes it better and harder to notice. But I think the best result is achieved with `variable-refresh-rate` on.

**Comment by YaLTeR** [comment]
Ah, right, I meant video-sync=audio. For me it works fine like that, not sure why it breaks for you. display-resample is best for no VRR, and for VRR you should use audio.

Btw you can enable on-demand VRR so it only turns on when mpv is visible.

**Comment by aslpavel** [comment]
I see, thank you I guess we can close the issue for now. I'm happy to use it with VRR. Though I'm curios why it happens in the first place, maybe some kind of weird interaction with pipewire, and then MPV tries to resample to compensate for it.
