### ISSUE TITLE
Add inotify support

### ISSUE THREAD

**Issue by quadbyte** [YaLTeR/niri#880]
Unity (3D game engine) rely on file change detection so that when you edit a source code file, the unity editor detect the changes and re-import the modified source file.

It is not working in Niri where the changes are not detected. This is a major show stopper for me as I have to manually trigger the re-import after every save.

Thank you!

### System Information

* niri version:  niri 0.1.10-1 (unknown commit)

* Distro: Arch Linux x86_64

* GPU: AMD Radeon RX 7800 XT

* CPU: AMD Ryzen 9 9950X

**Comment by YaLTeR** [comment]
Huh? Niri doesn't have anything to do with inotify

**Comment by quadbyte** [comment]
Sorry for the noise, this is actually a bug in Unity latest editor version.
