### ISSUE TITLE
Can't start Niri from bash_profile

### ISSUE THREAD

**Issue by eric-marin** [YaLTeR/niri#882]
I want to start Niri as soon i login from TTY. This is my `bash_profile`:
```
if [ -z "$DISPLAY" ] && [ "$XDG_VTNR" = 1 ]; then
  exec niri-session
fi
[[ -f ~/.bashrc ]] && . ~/.bashrc
```
Nothing is shown for a few minutes then i have to login again.
If I remove `exec niri-session` from the `bash_profile` and execute `niri-session` manually then Niri starts normally.
If I remove only `exec` I have to wait a few minutes then Niri starts.

### System Information

* niri version: niri 0.1.10-1 (unknown commit)

* Distro: Arch Linux

* GPU: Iris Xe Graphics

* CPU: i5-1240P

**Comment by YaLTeR** [comment]
The output and the journal (`journalctl --user-unit=niri -b`) right after this unsuccessful launch might tell something useful to diagnose.

But in general I'm not sure how good of an idea it is to do this, especially before sourcing the rest of .bashrc.

**Comment by eric-marin** [comment]
@BRS5672023 this solved my issue thank you!
