### ISSUE TITLE
Feature: option for [focus|move]-window-[up|down] to fallback to {focus|move-window-to]-workspace-[up|down]

### ISSUE THREAD

**Issue by rabidpug** [YaLTeR/niri#89]
Hi,

I migrated to Niri recently and I've been really enjoying the experience. For such a young project I've found it incredibly stable and really had no issues that weren't due to other programs.

I do have a couple of proposals that I think would improve the flexibility of some of the commands and reduce the number of keybinds required to navigate.

The proposal for this issue - I'd like to be able to have the option for the `focus-window` and `move-window` commands to fall back to the `focus-workspace` and `move-window-to-workspace` commands respectively when the former command doesn't do anything.
IE if I have 2 windows in the same column and I'm focused on the top window, with `Mod+Down` set to `focus-window-down` I'd like to have it go:
`Mod+Down` - focus the bottom window
`Mod+Down` - no more windows down to focus, so focus next workspace
etc
This way the vast majority of my navigation can be done with Mod+UDLR alone.

Thanks!

**Comment by YaLTeR** [comment]
Hello,

> I migrated to Niri recently and I've been really enjoying the experience. For such a young project I've found it incredibly stable and really had no issues that weren't due to other programs.

Thanks! That's great to hear :)

> I'd like to be able to have the option for the focus-window and move-window commands to fall back to the focus-workspace and move-window-to-workspace commands respectively when the former command doesn't do anything.

That's an interesting idea, I haven't thought of that before. Shouldn't be too difficult to implement either, I think.

**Comment by YaLTeR** [comment]
Added in https://github.com/YaLTeR/niri/pull/93.
