### ISSUE TITLE
Nix build is currently broken but CI ignores exit code

### ISSUE THREAD

**Issue by maxhbr** [YaLTeR/niri#894]
Hey,

the Nix build is currently failing with `exit 1` (see https://github.com/YaLTeR/niri/actions/runs/12471061748/job/34807344718#step:5:916) but the CI is configured to ignore the exit code:

https://github.com/YaLTeR/niri/blob/955039b5ea07c3fb2ff3278c0543004d86b7dcc7/.github/workflows/ci.yml#L192

Currently my OS, that is using the flake as a dependency to build Niri, is failing to build (will probably pin to an old hash).

The failing Tests are:
```
failures:
    tests::window_opening::dont_ack_initial_configure
    tests::window_opening::simple
    tests::window_opening::simple_no_workspaces
    tests::window_opening::target_output_and_workspaces

test result: FAILED. 68 passed; 4 failed; 0 ignored; 0 measured; 0 filtered out; finished in 4.81s
```
and they were introduced via https://github.com/YaLTeR/niri/commit/771ea1e81557ffe7af9cbdbec161601575b64d81

**Comment by YaLTeR** [comment]
@sodiboo hi could you take a look please?

CI ignoring nix build failure is intentional. I don't use or know nix so I don't want my CI to fail by something that I cannot fix myself. Ideally it would still show up as a red X without failing the whole workflow run, but I couldn't find a way to do it in GitHub Actions.

**Comment by sodiboo** [comment]
uhh these are the headless tests falling, right? I think it's just this: 

https://github.com/sodiboo/niri-flake/commit/350e6b68c70f5002a75e10521f5e66ace4b5eed1

**Comment by maxhbr** [comment]
@sodiboo : that works, I copied your changes and created a PR from that: https://github.com/YaLTeR/niri/pull/896

If you want to stay the author, just create your own and it is fine to drop my PR.
