### ISSUE TITLE
Border appears thin on some apps.

### ISSUE THREAD

**Issue by the-fuckin-nobody** [YaLTeR/niri#895]
### System Information

* niri version: `niri 0.1.10 (v0.1.10-68-g955039b)`

* Distro: `Gentoo linux`

* GPU: `Intel Corporation Alder Lake-P GT1 [UHD Graphics]`

* CPU: `Intel Core i5 12450H`

I'm still trying to figure things out on gentoo and I was just getting my hands on `niri` and boy is it awesome !!.

One thing kept bugging me is that, the border appears thinner on some apps, like 1 px thinner than on the terminal I/m using(foot). 

Here's two screenshots , one showing the borders on the terminal window (normal behavior) and other showing the border around the `zen-browser` window:

<b>Border appears as expected on `foot` (2px wide):</b>
![image](https://github.com/user-attachments/assets/c7f30b38-537d-4458-859b-b55c351ac355)

<b>Border appears 1px thinner on `zen-browser` (1px wide):</b>
![image](https://github.com/user-attachments/assets/94ba62ca-b977-4cd0-957d-11688abec11e)

This issue also exists on other gtk apps too. I have not tested it on any qt apps, cuz I've none.

This is the relevant part from  my config:

```kdl
    focus-ring {
        width 1
        active-gradient from="#82aaff" to="#fca7ea" angle=45 relative-to="workspace-view" in="oklch decreasing hue"
    }

    border {
        width 1
        active-gradient from="#82aaff" to="#fca7ea" angle=45 relative-to="workspace-view" in="oklch decreasing hue"
        inactive-gradient from="#82aaff" to="#fca7ea" angle=45 relative-to="workspace-view" in="oklab"

    }
```

Thanks for this amazing project.

**Comment by YaLTeR** [comment]
Hey, it's because those apps draw their own 1 px client-side border outside the window geometry. For Zen browser and Firefox (GTK 3) there's probably some GTK 3 CSS you can use to remove it.

**Comment by YaLTeR** [comment]
Forgot to mention: [clip-to-geometry](https://github.com/YaLTeR/niri/wiki/Configuration:-Window-Rules#clip-to-geometry) should get rid of it.

**Comment by the-fuckin-nobody** [comment]
> Forgot to mention: [clip-to-geometry](https://github.com/YaLTeR/niri/wiki/Configuration:-Window-Rules#clip-to-geometry) should get rid of it.

Worked like a charm! Thanks alot.
