### ISSUE TITLE
Will there be a release when it's ready?

### ISSUE THREAD

**Issue by mzur** [YaLTeR/niri#9]
Hi, I saw your project on HackerNews and it looks very interesting! The concept might fit perfectly to my workflow. Currently I'm using 2D workspaces in GNOME with my own extension and I'd be more than happy if I no longer have to maintain the extension but rather have the "2D" concept baked in to the compositor. I just wanted to ask if you plan to publish a release once you think this project is in beta stage or ready to use? That way I can just subscribe to the release feed and don't have to check out the project every now and then 😉

**Comment by mzur** [comment]
Thanks, that's all I wanted to know! I'll subscribe to the releases and give it a try from time to time.

**Comment by YaLTeR** [comment]
Well, guess what, I did tag an (alpha) release: https://github.com/YaLTeR/niri/releases/tag/v0.1.0-alpha.1 And it's got the aforementioned screen locking (via swaylock) too :smile:

**Comment by mzur** [comment]
Awesome, thanks!
