### ISSUE TITLE
[floating] interactive resizing mpv: position wiggles and jumps, stalls.

### ISSUE THREAD

**Issue by ToxicMushroom** [YaLTeR/niri#908]
These might be purely mpv bugs but I thought it'd be best to get feedback from someone who knows the WL resizing protocols ect before reporting upstream.

With decorations:
 - -When resizing mpv quickly it jumps back to its previous size but can change position while doing so.
 - -When resizing mpv while playing audio the interactive resize may stall, and mpv does the final resize when I release right mouse button

without decorations:
 - -Resizing makes the video wiggle position often
 - +Resizing audio does not jump back to its previous size.
 - +Resizing audio does not stall

### Videos:
no-csd wiggles: 

https://github.com/user-attachments/assets/cdef53bb-9620-4450-b12f-1a43c1dd2070

csd jumps:

https://github.com/user-attachments/assets/6c033705-1752-4a61-bef2-63833c02a95f

csd audio resize stalls:

https://github.com/user-attachments/assets/b9831249-358b-4ab0-8288-5651eb0810bd

### System Information
* niri version: niri 0.1.10 (v0.1.10-154-g4741ab2e)
* Distro: 6.12.7-arch1-1
* GPU: AMD Radeon RX 6650 XT [Discrete]
* CPU: AMD Ryzen 5 5600X (12) @ 4.65 GHz

**Comment by YaLTeR** [comment]
So I'm fairly sure these are mpv issues. I noticed that some of them go away when mpv is forced to commit frequently, like when playing a video, or when disabling resize throttling in niri with a debug option. This in particular should be fixed in mpv by making it ack and commit to a configure even if doesn't result in a change in size (a similar thing has been fixed in chromium some time ago).

**Comment by YaLTeR** [comment]
I'll close this for now; we can reopen if there's a niri issue after all

**Comment by ToxicMushroom** [comment]
fwiw, the mp3 resizing stall does not happen on sway, but it does feel very laggy on sway

**Comment by ToxicMushroom** [comment]
GTK2 has the same quirks. tested with verifast's `vfide`
