### ISSUE TITLE
Cursor disappears

### ISSUE THREAD

**Issue by AlexD97** [YaLTeR/niri#98]
Without the option `disable-cursor-plane` my cursor disappears immediately after any action (e.g. moving the mouse, opening a window).

**Comment by YaLTeR** [comment]
Any warnings in the niri output? Do other compositors (mutter, weston, sway) show the problem?

This is likely either a driver bug or a Smithay bug; niri itself doesn't do much special with cursors.

**Comment by kchibisov** [comment]
if you're using nvidia GPUs they are known to have broken cursor planes.

**Comment by AlexD97** [comment]
Yes, it works on sway. I'm using an integrated intel GPU.

**Comment by YaLTeR** [comment]
Would you mind checking if [anvil](https://github.com/Smithay/smithay/tree/master/anvil) shows the same problem?

**Comment by AlexD97** [comment]
I'd like to but I couldn't manage to build it on NixOS.

**Comment by YaLTeR** [comment]
What's the error if you try building it, say, in the niri nix devshell?

**Comment by AlexD97** [comment]
Now, in the niri nix shell, I was able to build it. There is no cursor in anvil.

**Comment by YaLTeR** [comment]
I guess this issue should be reopened in Smithay then

**Comment by AlexD97** [comment]
Before filing an issue in the Smithay repository: Am I supposed to see just a gray screen in anvil?

**Comment by YaLTeR** [comment]
Yeah, I think you can press something like Alt+Enter to spawn `weston-terminal` if you have it installed.

**Comment by AlexD97** [comment]
Okay, can confirm that anvil works, but there is no cursor. So it's probably a problem with smithay (see https://github.com/Smithay/smithay/issues/1275).

**Comment by YaLTeR** [comment]
Thanks for testing!

**Comment by AlexD97** [comment]
Works fine now, thanks!
